Repository ankidroid/Anki-Android, pull requests merged in 2019-12, with the labels that each got.

#5671 Fix crash occurring when trying to open rating activity
  AnkiDroid/src/main/java/com/ichi2/anki/Info.java
  AnkiDroid/src/main/res/values/05-feedback.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: 2.9.x, Review High Priority, waitingforfeedback

#5670 Fix crash related to escaping html entites
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Labels: 2.9.x, Priority-Medium, Review High Priority

#5647 Change the img regex tag to match Anki desktop
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Labels: Anki Ecosystem Compatibility, Review High Priority, bug

#5645 Fix SchedV2 rev limit deck ID overflow
  AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Labels: 2.9.x, Review High Priority, bug

#5658 replace apache http w/okhttp, enable TLS1.2 for Android API<=21
  AnkiDroid/build.gradle
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/CountingFileRequestBody.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java
  AnkiDroid/src/main/java/org/apache/commons/httpclient/contrib/ssl/EasySSLSocketFactory.java
  AnkiDroid/src/main/java/org/apache/commons/httpclient/contrib/ssl/EasyX509TrustManager.java
Labels: Anki Ecosystem Compatibility, Priority-High, Review High Priority

#5571 Flag
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/res/drawable/flag_blue.png
  AnkiDroid/src/main/res/drawable/flag_green.png
  AnkiDroid/src/main/res/drawable/flag_orange.png
  AnkiDroid/src/main/res/drawable/flag_red.png
  AnkiDroid/src/main/res/drawable/flag_transparent.png
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Review High Priority
