Repository ankidroid/Anki-Android, pull requests merged in 2020-07, with the labels that each got.

#6596 Deck tree check deal with name map
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Pending Merge

#6586 NF: cache the result of "parent"
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Second Approval

#6603 NF: simplify _fill
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#6616 NF: remove a method unused
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6615 S tasks
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6625 LINT: Sched - Fix IntDef errors
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6629 NF: Warns if onPostExecute is done after cancellation
  AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.java
Labels: Needs Second Approval

#6617 Parents uses array
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Waiting For Feedback

#6624 AnkiDroidJS: display blank if button unavailable
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Labels: Waiting For Feedback

#6652 mLrnQueue has encoded as a class
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#6648 Decks: Strip whitespace in children as well as parents
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
Labels: Needs Second Approval

#6659 Correct 6658
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: 2.13.x

#6663 Protect against stale field info in CardTemplatePreviewer
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: 2.12.x, Pending Merge

#6662 Handle Exception from FileProvider in crop
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: 2.12.x

#6688 Correcting copy of JSONObject
  AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
Labels: Pending Merge

#6699 getUserFlag->userFlag
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
Labels: Needs Second Approval

#6703 NF: UnburyType is an enum
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#6714 Correcting test on phone
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
Labels: Needs Second Approval

#6697 Database: Replace "queryColumn" with "list" methods
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6723 Remove useless task data
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Labels: Needs Review

#6731 CollectionTask Constructor private
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval

#6729 NF: Move `new Listener` outside of function
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Labels: Needs Second Approval

#6730 NF: Single Listener
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Labels: Pending Merge

#6734 NF: move unburyCardsForDeck(UnburyType) to AbstractSched
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6735 Improve automated sync rate limit error
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#6736 NF: asserts that instead of asserts true
  AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
Labels: Pending Merge

#6746 Whiteboard: Add Toggle for Pen Color
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Labels: Needs Second Approval

#6740 NF: doInBackgroundDeleteDeck don't return
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6742 NF: listener's onProgressUpdate take a single element
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6753 NF: Task takes at most one task data
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval
