Repository ankidroid/Anki-Android, pull requests merged in 2020-02, with the labels that each got.

#5736 Okhttp interrupted crash
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Labels: Bug, Review High Priority

#5731 Avoid RuntimeException crash in Sound
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: 2.9.x, Audio, Bug, Review High Priority

#5727 Ignore android VM screen capture images
  .gitignore
Labels: Review High Priority

#5699 Card browser accepts empty answer string
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Labels: Review High Priority

#5584 Fix for: Latest update plays audio file twice #5530
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Review High Priority

#5745 Categorize more okhttp connection errors as harmless
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Labels: 2.9.x, Priority-Low

#5743 Fix ImportDialog IllegalStateException crash
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: 2.9.x, Bug, Priority-Medium, Review High Priority

#5748 Avoid crash if collection closes while reminder is building
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
Labels: 2.9.x, Bug, Review High Priority

#5752 Avoid crashing if initialization of CustomTabs fails
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java
Labels: 2.9.x, Bug, Review High Priority

#5760 Use application-level resources for Async fragments
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
Labels: 2.9.x, Accepted, Bug, Review High Priority

#5759 Applying correctly limit for top level new deck
  AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Labels: 2.9.x, Bug

#5764 Avoid crash on audio clip w/no extension or mime type
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Labels: 2.9.x, Bug
