Repository ankidroid/Anki-Android, pull requests merged in 2020-10, with the labels that each got.

#7319 NF: remove warning while does not loop
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java
Labels: Pending Merge

#7321 NF: remove warning inner class can be static
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
Labels: Pending Merge

#7322 NF: remove warning about pointless arithmetic
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Pending Merge

#7320 NF: remove warning if can be simplified
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: Pending Merge

#7323 NF: Remove warning about unatotated language
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectCalendarInstanceUsageTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectDateInstantiationTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiationTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsageTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSystemTimeInstantiationTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsageTest.java
Labels: Pending Merge

#7075 Show useful error when col version is too high
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/exception/UnknownDatabaseVersionException.java
  AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.java
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#7332 API 29 Dependency Updates
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
  AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.java
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
  AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.java
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java
  AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.java
  AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java
  AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java
  AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
Labels: Pending Merge

#7329 Card Browser: Display cards deleted when deleting notes
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Blocked by dependency, Pending Merge

#6641 Allow fileupload api
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
  api/build.gradle
  api/src/main/java/com/ichi2/anki/FlashCardsContract.java
  api/src/main/java/com/ichi2/anki/api/AddContentApi.java
Labels: Needs Review, Waiting For Feedback

#7347 Reordered menu items in the card template editor.
  AnkiDroid/src/main/res/menu/card_template_editor.xml
Labels: Pending Merge

#7312 NF: newCardName break sooner
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Labels: Needs Review

#7357 Iterate json
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
Labels: Pending Merge, Waiting For Feedback

#7362 NF: more Model as type
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Labels: Pending Merge

#7374 Fix AnkiDroidApp.sInstance-is-null crash during dialog inflation
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.java
Labels: Needs Review

#7381 Fix #7118: Adding Filter by flag icon to card browser.
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/res/menu/card_browser.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Pending Merge

#7065 Fix scrollbar's position not remembered in CardBrowser #6857
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Needs Second Approval, Pending Merge

#7385 Bump lint from 27.0.2 to 27.1.0
  lint-rules/build.gradle
Labels: Pending Merge

#7406 NF: remove duplicate ressource "repair"
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
  AnkiDroid/src/main/res/values/09-backup.xml
Labels: Needs Second Approval

#7402 NF: remove "Card Browser" duplication
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge

#7404 NF: remove duplicate "help"
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Needs Second Approval

#7422 Note Editor: Make Field Full Width
  AnkiDroid/build.gradle
  AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Note Editor, Pending Merge, UI

#7428 NF: remove duplicate "All decks"
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
  AnkiDroid/src/main/res/layout/dropdown_deck_selected_item.xml
  AnkiDroid/src/main/res/values/06-statistics.xml
Labels: Needs Second Approval

#7435 Fix images deleted after editing (issue #7377)
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: Needs Second Approval

#7437 Note Editor: Set Font Size Feature
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.java
  AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
  AnkiDroid/src/main/res/menu/note_editor.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
Labels: Enhancement, Note Editor

#7392 Fix for cards not showing up inside card browser if deck contains wildcard characters in its name.
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Labels: Needs Second Approval, hacktoberfest-accepted

#7444 Use Travis Workspaces to cache APK
  .travis.yml
Labels: Dev, Enhancement, Performance

#7398 Regression Test to check if Decks with wildcard characters in their name can be searched.
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
Labels: hacktoberfest-accepted

#7453 Less long
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#7462 NF: remove unused constructor
  AnkiDroid/src/main/java/com/ichi2/async/TaskData.java
Labels: Pending Merge

#6978 Regression 6898 2
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Labels: Needs Review, Pending Merge

#7463 NF: Avoid useless construction of array
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Pending Merge

#7461 NF: add non null
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge, Waiting For Feedback

#7473 NF: uses clone instead of creating string and reading it
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#7472 NF: _tmplsFromOrds quicker
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#7476 NF: remove duplicate "Edit note"
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Pending Merge

#7475 NF: optimize genCard
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
Labels: Pending Merge

#7507 NF: explain "translation"
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge

#7514 BugFix: Deck Override Default: Set to null
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Labels: Review High Priority

#7487 Duplicate create
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Waiting For Feedback

#7496 NF: Comment String "reviews"
  AnkiDroid/src/main/res/values/06-statistics.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Waiting For Feedback

#7495 NF: remove duplicate String "Ease"
  AnkiDroid/src/main/res/layout/card_info.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Waiting For Feedback

#7497 NF: Disambiguate Strings via Comment: "Learn"
  AnkiDroid/src/main/res/values/06-statistics.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Waiting For Feedback

#7502 NF: Explain duplicate String: "Preview"
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Waiting For Feedback

#7511 NF: Use interface instead of CollectionTask in libanki
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#7498 NF: remove duplicate "Lapses"
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge

#7499 Action to check for string ressources
  .github/pull_request_template.md
Labels: Waiting For Feedback

#7504 NF: duplicate rename
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge

#7426 NoteEditor: Expand/Collapse Field Content
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/ui/AnimationUtil.java
  AnkiDroid/src/main/res/drawable/ic_expand_less_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_expand_more_black_24dp_xml.xml
  AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Enhancement, Note Editor

#7544 Dependency updates 20201028
  AnkiDroid/build.gradle
Labels: Pending Merge

#7538 Allow 9-point touch tap gestures for tablets
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureTapProcessor.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureTapProcessorTest.java
Labels: Pending Merge

#7535 NF: save current search to avoid doing it twice
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#7546 NF: uses `contains` instead of looping over values
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Labels: Pending Merge

#7559 Card Info: Make data selectable
  AnkiDroid/src/main/res/values/styles.xml
Labels: Enhancement, Pending Merge

#7560 Note Editor Toolbar: Add Keyboard Shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
  AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.java
  AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
Labels: Enhancement

#7569 Fix test: checkDatabaseWithLockedCollectionReturnsLocked
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java
Labels: Pending Merge

#7542 NF: timber uses format
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
  AnkiDroid/src/main/java/com/ichi2/utils/Threads.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
Labels: Pending Merge

#7572 NF: Fix string removal: cancel_sync_confirm
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Labels: Pending Merge

#7574 Mark Navigation Drawer Strings as Used
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#7575 NF: Mark dialog_positive_disable as unused
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#7534 NF: remove DB.list
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
Labels: Needs Review
