Repository ankidroid/Anki-Android, pull requests merged in 2020-11, with the labels that each got.

#7605 NF: uses for-loop if possible
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
Labels: Pending Merge

#7588 feature #6726: make app resizable on Android desktops
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Pending Merge, hacktoberfest-accepted

#7634 Add gesture: Abort and Sync
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/utils/ThreadUtil.java
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge

#7636 TEST: Fix selectNoneIsVisibleOnceSelectAllCalled
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Pending Merge

#7618 [BugFix]: MyAccount - NullPointerException
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
Labels: Needs Review

#7650 BugFix: confirmDeckDeletion crash
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Pending Merge

#7653 Updated strings from Crowdin 20201111
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sk/01-core.xml
  AnkiDroid/src/main/res/values-sk/02-strings.xml
  AnkiDroid/src/main/res/values-sk/03-dialogs.xml
  AnkiDroid/src/main/res/values-sk/04-network.xml
  AnkiDroid/src/main/res/values-sk/06-statistics.xml
  AnkiDroid/src/main/res/values-sk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sk/09-backup.xml
  AnkiDroid/src/main/res/values-sk/10-preferences.xml
  AnkiDroid/src/main/res/values-sk/11-arrays.xml
  AnkiDroid/src/main/res/values-sk/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-sk/17-model-manager.xml
  AnkiDroid/src/main/res/values-sk/18-standard-models.xml
Labels: Pending Merge

#7655 Fix flaky test: confirmDeckDeletionDeletesEmptyDeck
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Pending Merge

#7656 NF: Improve string: locale_selection_dialog_title
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#7664 Updated strings from Crowdin 20201112
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/11-arrays.xml
Labels: Pending Merge

#7670 NF: Improve widget in designer
  AnkiDroid/src/main/res/layout/widget_small.xml
Labels: Pending Merge

#7669 Remove MIUI Keyboard Hack Preference
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Strings

#7672 NF: Remove Specific Error String
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Strings

#7591 NF: always int
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Needs Review

#7691 NF: Use sql to query distinct directly
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Labels: Pending Merge

#7697 Change rename field string
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Labels: Pending Merge

#7687 Deck Picker: Convert the dialog to a Toast
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
Labels: Pending Merge

#7718 Updated strings from Crowdin 20201118
  AnkiDroid/src/main/res/values-it/02-strings.xml
  AnkiDroid/src/main/res/values-it/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#7719 Fix overflow menu background
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: UI

#7189 Raw type
  AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/FabBehavior.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
Labels: Needs Second Approval

#7727 Undo direct
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java
Labels: Pending Merge

#7616 NF: simplify filling queues in sched
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Review

#7769 Fix image crop required twice
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: Pending Merge

#7778 Vivo Phones: Advise on create shortcut failure
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Strings

#7800 Arrays: Extract gestures_labels strings
  AnkiDroid/src/main/res/values/11-arrays.xml
Labels: Strings

#7803 Updated strings from Crowdin
  AnkiDroid/src/main/res/values-ar/11-arrays.xml
  AnkiDroid/src/main/res/values-az/11-arrays.xml
  AnkiDroid/src/main/res/values-be/11-arrays.xml
  AnkiDroid/src/main/res/values-bg/11-arrays.xml
  AnkiDroid/src/main/res/values-ca/11-arrays.xml
  AnkiDroid/src/main/res/values-ckb/11-arrays.xml
  AnkiDroid/src/main/res/values-cs/11-arrays.xml
  AnkiDroid/src/main/res/values-de/11-arrays.xml
  AnkiDroid/src/main/res/values-el/11-arrays.xml
  AnkiDroid/src/main/res/values-eo/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rES/11-arrays.xml
  AnkiDroid/src/main/res/values-et/11-arrays.xml
  AnkiDroid/src/main/res/values-eu/11-arrays.xml
  AnkiDroid/src/main/res/values-fa/11-arrays.xml
  AnkiDroid/src/main/res/values-fi/11-arrays.xml
  AnkiDroid/src/main/res/values-fil/11-arrays.xml
  AnkiDroid/src/main/res/values-fr/11-arrays.xml
  AnkiDroid/src/main/res/values-gl/11-arrays.xml
  AnkiDroid/src/main/res/values-heb/11-arrays.xml
  AnkiDroid/src/main/res/values-hi/11-arrays.xml
  AnkiDroid/src/main/res/values-hu/11-arrays.xml
  AnkiDroid/src/main/res/values-ind/11-arrays.xml
  AnkiDroid/src/main/res/values-it/11-arrays.xml
  AnkiDroid/src/main/res/values-ja/11-arrays.xml
  AnkiDroid/src/main/res/values-ko/11-arrays.xml
  AnkiDroid/src/main/res/values-ku/11-arrays.xml
  AnkiDroid/src/main/res/values-lt/11-arrays.xml
  AnkiDroid/src/main/res/values-mk/11-arrays.xml
  AnkiDroid/src/main/res/values-ms/11-arrays.xml
  AnkiDroid/src/main/res/values-nl/11-arrays.xml
  AnkiDroid/src/main/res/values-nn/11-arrays.xml
  AnkiDroid/src/main/res/values-no/11-arrays.xml
  AnkiDroid/src/main/res/values-pl/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rPT/11-arrays.xml
  AnkiDroid/src/main/res/values-ru/11-arrays.xml
  AnkiDroid/src/main/res/values-sat/11-arrays.xml
  AnkiDroid/src/main/res/values-sk/11-arrays.xml
  AnkiDroid/src/main/res/values-sl/11-arrays.xml
  AnkiDroid/src/main/res/values-sr/11-arrays.xml
  AnkiDroid/src/main/res/values-sv/11-arrays.xml
  AnkiDroid/src/main/res/values-ta/11-arrays.xml
  AnkiDroid/src/main/res/values-te/11-arrays.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
  AnkiDroid/src/main/res/values-uk/11-arrays.xml
  AnkiDroid/src/main/res/values-vi/11-arrays.xml
  AnkiDroid/src/main/res/values-zh-rCN/11-arrays.xml
  AnkiDroid/src/main/res/values-zh-rTW/11-arrays.xml
Labels: Strings
