Repository ankidroid/Anki-Android, pull requests merged in 2020-08, with the labels that each got.

#6766 JS API: Add Remaining Card Properties
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Needs Review

#6761 Card Template Editor: Add Deck Override
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java
  AnkiDroid/src/main/res/layout/deck_picker_dialog.xml
  AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml
  AnkiDroid/src/main/res/menu/card_template_editor.xml
  AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/17-model-manager.xml
Labels: Anki Ecosystem Compatibility

#6807 Improve Non-full Sync Badge UI
  AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawable.java
  AnkiDroid/src/main/res/values/colors.xml
Labels: Pending Merge

#6708 Upstream test
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/ExportingTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/ImportingTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/MediaTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/StatsTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/TemplateTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
Labels: Pending Merge

#6816 Fix CI Failure: SchedV2Test.test_moveVersions
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Review High Priority

#6822 Bump material from 1.1.0 to 1.2.0
  AnkiDroid/build.gradle
Labels: Pending Merge

#6826 Sync Status: Remove badge when no changes
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Labels: Pending Merge

#6828 Improve Firebase test quality
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#6823 Update Readme.md
  README.md
  docs/graphics/logos/Amazon-app-store.png
  docs/graphics/logos/ankidroid_logo.png
  docs/graphics/logos/banner_readme.png
  docs/graphics/logos/discord_logo_color.png
  docs/graphics/logos/facebook_logo_color.png
  docs/graphics/logos/reddit_logo_color.png
  docs/graphics/logos/twitter_logo_color.png
Labels: Pending Merge

#6831 NF: move clearUndo to background
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6835 NoteEditor: Fix newlines when previewing
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Pending Merge

#6839 NF: remove "new Object[]" in queries
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6836 Card Template Preview: Preview Edited Note
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
Labels: Waiting For Feedback

#6749 Remove unused task
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Card Template Editor, Needs Second Approval

#6840 NF: remove methods not in libanki duplicated
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
Labels: Pending Merge

#6858 Port to maintained 3rd party diffutils
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
Labels: Pending Merge

#6859 Use new ACRA APIs to clear AcraLimiter
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Labels: Pending Merge

#6861 Added toast on debug info copy
  AnkiDroid/src/main/java/com/ichi2/anki/Info.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#6862 Allow the user to disable the Sync Status Badge
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Pending Merge

#6883 Diff patch update
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
Labels: Pending Merge

#6849 NF: add a class CardCache
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Needs Review, Needs Second Approval

#6890 NF: uses Integer.compare
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
Labels: Pending Merge

#6889 Add Scheduler version to Debug Info
  AnkiDroid/src/main/java/com/ichi2/anki/Info.java
Labels: Pending Merge

#6848 NF: Split mUndidCard
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6893 NF: Add test for card generation
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java
Labels: Pending Merge

#6901 NF: bigQuery - optimize memory usage to avoid OOM in tests
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
Labels: Needs Second Approval, Pending Merge

#6900 During slow operation, bury/suspend/flag/marked get correct alpha
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Labels: Pending Merge, Waiting For Feedback

#6907 Bump mockito-inline from 3.4.6 to 3.5.0
  AnkiDroid/build.gradle
Labels: Pending Merge

#6891 Init ACRA and analytics onAttachBaseContext
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Labels: Needs Review

#6863 onTrimMemory call super
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#6922 Ignore big model test on API29, flaky
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
Labels: Pending Merge

#6925 Unit test for daily increase
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
Labels: Pending Merge

#6957 NF: Use col's time instead of `new SystemTime`
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicControllerFactory.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: Pending Merge

#6855 Colin p hill templates
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
Labels: Needs Review

#6979 NF: Change of string are not reflected in crowdin
  AnkiDroid/src/main/res/values/12-dont-translate.xml
  tools/manage-crowdin.sh
Labels: Pending Merge

#6993 NF: correct creation of card cache
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#6998 Updated strings from Crowdin 20200829
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/04-network.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-fr/17-model-manager.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/04-network.xml
  AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-pt-rBR/17-model-manager.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
Labels: Pending Merge

#6999 Dependency updates 20200829
  AnkiDroid/build.gradle
Labels: Pending Merge

#7000 Second column of browser repaired
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#7002 NF: mSetLanugageId -> mSetLanguageId
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Pending Merge

#6994 Add Test: Ensure layouts can be used on all APIs
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java
Labels: Pending Merge

#7004 Correct 6970
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: 2.13.x, Needs Review
