Repository ankidroid/Anki-Android, pull requests merged in 2020-05, with the labels that each got.

#6112 BUGFIX: Play All Audio on card when viewed
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: Pending Merge

#6120 Revert "don't put "undo" to color enabled"
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Labels: Waiting For Feedback

#6150 Avoid crash if conditional is not found
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
Labels: Pending Merge

#6154 use localised field name during collection export
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Labels: Pending Merge

#6159 NoteEditor: Allow Exit before collection load
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/test/AndroidManifest.xml
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/NullCollectionNoteEditor.java
Labels: Pending Merge

#6151 Issue template: Suggest checking alpha release before reporting
  .github/issue_template.md
Labels: Pending Merge

#6163 Block file import if no storage permissions
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#6168 Fixed error with counting card in learn state
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6169 Fix "Basic (type in the answer)" in English and in other languages
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java
Labels: Pending Merge

#6166 Run various different locales in Travis
  .travis.yml
Labels: Pending Merge

#6194 Ignore API R even after adding LOCALE arg
  .travis.yml
Labels: Pending Merge

#6199 Render the official changelog for public releases
  tools/release.sh
Labels: Pending Merge

#6202 Vary lint config debug vs release, CI allows debug lint
  .travis.yml
  AnkiDroid/lint-baseline.xml
  lint.gradle
Labels: Pending Merge

#6223 Add Option: Display filenames in card browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.java
Labels: Pending Merge

#6225 Fix widget crash if external storage not mounted
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
Labels: Pending Merge

#6227 Trying to remove blink during review
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
Labels: Pending Merge

#6246 In night mode, add a white background to latex's svg
  AnkiDroid/src/main/assets/flashcard.css
Labels: Waiting For Feedback

#6275 Don't perform app init init if launched from ACRA sender
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Labels: Pending Merge

#6206 Introduce night mode compatibility with desktop Anki
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java
Labels: Anki Ecosystem Compatibility

#5387 Deprecation: SharedPreferences Version code from int to long
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV28.java
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.java
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Pending Merge, Waiting For Feedback

#6303 Correct count for undo of learning card V2
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6302 Travis: Set TERM=dumb to reduce log output
  .travis.yml
Labels: Pending Merge

#6319 Add USERTrust root certificate for older Android devices
  AnkiDroid/src/main/assets/USERTrust_RSA.crt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/UnifiedTrustManager.java
Labels: Review High Priority
