Repository ankidroid/Anki-Android, pull requests merged in 2020-06, with the labels that each got.

#6279 Correct Device "Back" Button in Restore From Backup
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
Labels: Needs Review

#6270 NF: Remove hook chess
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/hooks/ChessFilter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/hooks/Hooks.java
Labels: Pending Merge

#6269 Remove hook latex
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java
  AnkiDroid/src/main/java/com/ichi2/libanki/hooks/Hooks.java
Labels: Pending Merge, Waiting For Feedback

#6278 No tex in browser
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#6343 Bump gradle plugin to 4.0.0
  build.gradle
Labels: Pending Merge

#6350 Revert "Remove possibility of TagsDialog NullPointerException"
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
Labels: Pending Merge

#6347 Card Browser: Always show 'Search All'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#6360 NF: Better do in background search cards
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#6326 [Fixed] Wrong symbol for ascending/descending sorting in card browser #5802
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.java
Labels: Pending Merge

#6376 Fix typo noticed by translator in source strings
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge

#6391 Remove leftover comment overseen in #6268
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
Labels: Pending Merge

#6380 Remove unused parameter in saveCollectionInBackground
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
Labels: Needs Second Approval

#6438 Convert import/export zip file usage to library: commons-compress - Allows >2GB imports
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
Labels: Pending Merge

#6440 invert tex color in night mode
  AnkiDroid/src/main/assets/flashcard.css
Labels: Needs Second Approval

#6257 string consisting only of whitespace does not generate card (Previously NF: clean _renderQA)
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
Labels: Anki Ecosystem Compatibility, Pending Merge

#6495 Show two numbers in planification
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Needs Second Approval

#6437 sync: fix media sync with trailing slash on media sync url
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.java
Labels: Needs Second Approval

#6496 Reload card browser when tags/fields change in note edit
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Pending Merge

#6501 Show keyboard when adding note in NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Pending Merge

#6453 Strip spaces in deck name
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Anki Ecosystem Compatibility

#6502 Automated deck renaming
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Anki Ecosystem Compatibility

#6506 Deck import: Pre-validate zip file
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Labels: Pending Merge

#6505 Import: Improve error and don't report problem if cache is cleared
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#6509 Using different method for time in deck picker and review
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#6386 Show Toast using JavaScript function in WebView
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Needs Second Approval

#6534 Bugfix #6504 add mic tool bar in full screen mode
  AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
Labels: Needs Second Approval

#6533 Nested decks in pull request
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
Labels: Needs Second Approval

#6530 NF: introduce a variable
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Needs Second Approval

#6536 NF: deckDueList only if required (performance)
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge

#6529 NF: replace mModels by getModels()
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#6541 Move jacoco-agent test file to test directory
  AnkiDroid/src/androidTest/resources/jacoco-agent.properties
Labels: Pending Merge

#6503 Add volume buttons to gestures
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
Labels: Pending Merge

#6553 Carefully install JDKs, sensitive to transient failure
  .travis.yml
Labels: Dev

#6525 Update ic_flag_blue.xml
  AnkiDroid/src/main/res/drawable/ic_flag_blue.xml
Labels: Waiting For Feedback

#6550 Change whiteboard pen color while reviewing
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
  AnkiDroid/src/main/res/drawable/ic_color_lens_white_24dp.xml
  AnkiDroid/src/main/res/layout/reviewer.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
  AnkiDroid/src/main/res/layout/reviewer_whiteboard_pen_color.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/colors.xml
Labels: Needs Second Approval, Waiting For Feedback

#6567 Night mode status in Card
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Pending Merge

#6581 Add AutoSizeCheckBoxPreference
  AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.java
  AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.java
  AnkiDroid/src/main/res/xml/deck_options.xml
Labels: Pending Merge

#6574 NF: uses AbstractSched before DeckDueTreeNode (performance)
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java
Labels: Pending Merge

#6593 Improved blue flag contrast against blue app bar
  AnkiDroid/src/main/res/drawable/ic_flag_blue.xml
Labels: Pending Merge
