Repository ankidroid/Anki-Android, pull requests merged in 2020-03, with the labels that each got.

#5782 Manually grant permissions <= Lollipop to avoid camera crash
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: 2.9.x, Priority-Medium, Reproduced, Review High Priority

#5789 Avoid crash on browser QA render if cancelled
  AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Labels: 2.9.x, Review High Priority

#5788 Gracefully handle deck deletion while building reminders
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
Labels: 2.9.x, Advanced Reminders, Review High Priority

#5791 Gracefully handle MediaRecorder.stop exceptions
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
Labels: 2.8.x, 2.9.x, Review High Priority

#5797 Gracefully handle any exception while building reminder
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
Labels: 2.9.x, Advanced Reminders, Priority-Critical, Review High Priority

#5700 Correcting: onMark/onFlag raises nullPointException
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Bug, Waiting For Feedback

#5589 Adds constant string before equal
  AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CustomFontsReviewerExt.java
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Labels: Waiting For Feedback

#5592 All missing columns in browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Waiting For Feedback

#5626 Subtitle in DeckPicker indicates hours if more than 60 minutes
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Waiting For Feedback

#5830 Fix "AnkiDroid directory is inaccessible" Bug
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java
  AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
Labels: 2.9.x, Review High Priority

#5861 Deck Description: Handle Newlines
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
  AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.java
  AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.java
Labels: Anki Ecosystem Compatibility

#5862 Made image HTML identical to AnkiDesktop when inserting
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java
Labels: Anki Ecosystem Compatibility
