Repository ankidroid/Anki-Android, pull requests merged in 2021-01, with the labels that each got.

#8009 Ignore revlog.ease == 0 in stats, Fixes #8008
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Needs Review

#7976 "Unknown field" message gets translated
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Waiting For Feedback

#8058 Opt out of WebView metrics collection
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Pending Merge

#8060 UX: Hide full screen after user input
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
Labels: Pending Merge

#8068 TEST: fix flaky test: collectionIsVersion11AfterOpen
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/RustTest.java
Labels: Pending Merge

#8054 Sched: Enable New Timezone Handling Code
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/BackendNotSupportedException.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingTodayProto.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Pending Merge

#8061 Indicate we incorporate AGPLv3 code.
  README.md
Labels: Needs Second Approval
