Repository ankidroid/Anki-Android, pull requests merged in 2021-11, with the labels that each got.

#9757 Ensure a single note type is highlighted
  AnkiDroid/src/main/java/com/ichi2/anki/ui/NoteTypeSpinnerUtils.kt
Labels: Needs Second Approval

#9756 [EditNote][DeckSpinner] Display long name
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
Labels: Needs Second Approval

#9759 feat(v16): Load Audio from backend
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
Labels: Needs Review

#9767 Migration to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
Labels: Needs Second Approval

#9766 Migrate to Kotlin- Time
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.kt
Labels: Needs Second Approval

#9774 fix(android, api31): implement compileSdkVersion 31 compatibility
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioRecorderTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java
  api/build.gradle
Labels: Pending Merge

#9773 Migrate to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.kt
Labels: Pending Merge

#9782 Kotlin migration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
Labels: Needs Second Approval

#9787 Kotlin migration: StyledProgressDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
Labels: Review High Priority, Needs Second Approval

#9790 Kotlin migration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
Labels: Needs Second Approval

#9791 [Kotlin Migration] ClipboardUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
Labels: Needs Second Approval

#9802 fix(miui): disable "force dark" mode
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
  AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
  AnkiDroid/src/main/res/values-v29/xiaomi-theme-overlay.xml
  AnkiDroid/src/main/res/values/xiaomi-theme-overlay.xml
Labels: Needs Review

#9803 Kotlin migration IntegerDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Labels: Needs Second Approval

#9804 Kotlin migration CardBrowserOrderDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
Labels: Needs Second Approval

#9805 Kotlin migration DeckPickerNoSpaceToDowngradeDialog.kt
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceToDowngradeDialog.kt
Labels: Needs Second Approval

#9806 Kotlin migration ExportCompleteDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
Labels: Needs Second Approval

#9807 Kotlin migration InsertFieldDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
Labels: Needs Second Approval

#9808 Kotlin migration WhiteBoardWidthDialog.kt
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.kt
Labels: Needs Second Approval

#9809 Kotlin migration ImportDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
Labels: Needs Second Approval

#9800 [Kotlin Migration][Follow-Up] Time
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.kt
Labels: Needs Second Approval

#9816 [Kotlin Migration] IntentUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/IntentUtil.kt
Labels: Needs Second Approval

#9765 [EditNote][DeckSelectionDialog] Highlight Selected item
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
Labels: Needs Second Approval

#9819 [Kotlin Migration] FileUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
Labels: Waiting For Feedback, Needs Second Approval

#9827 Kotlin migration CardBrowserMySearchesDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Labels: Needs Second Approval

#9829 Kotlin migration CreateDeckDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
Labels: Needs Second Approval

#9831 Kotlin migration DeckPickerContextMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
Labels: Needs Second Approval

#9828 Kotlin migration MediaCheckDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
Labels: Needs Second Approval

#9830 Kotlin migration RecursivePictureMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
Labels: Needs Second Approval

#9833 Kotlin migration SyncErrorDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Needs Second Approval

#9839 [Kotlin Migration] VersionUtils
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
Labels: Needs Second Approval

#9835 Kotlin migration DatabaseErrorDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Needs Second Approval

#9848 Kotlin migration CustomStudyDialogTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Labels: Needs Second Approval

#9851 Kotlin migration ModelFieldEditorTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
Labels: Needs Second Approval

#9849 Kotlin migration CreateDeckDialogTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Labels: Pending Merge

#9860 [Kotlin Migration] SystemContextMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/SystemContextMenu.kt
Labels: Needs Second Approval

#9858 [Kotlin Migration] AnkiCardContextMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt
Labels: Needs Second Approval

#9859 [Kotlin Migration] ImportExportException
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/exception/ImportExportException.kt
Labels: Pending Merge

#9865 [Kotlin Migration] CardBrowserContextMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt
Labels: Needs Second Approval

#9867 fix build
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt
Labels: Pending Merge

#9866 Updated strings from Crowdin 20211110
  AnkiDroid/src/main/res/values-be/01-core.xml
  AnkiDroid/src/main/res/values-be/02-strings.xml
  AnkiDroid/src/main/res/values-be/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-be/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-or/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/04-network.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/11-arrays.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ro/01-core.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/11-arrays.xml
  AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-uz/01-core.xml
Labels: Pending Merge

#9877 [Kotlin Migration] AudioClipField
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioClipField.kt
Labels: Needs Second Approval

#9876 [Kotlin Migration] UserSubmittedException
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/exception/UserSubmittedException.kt
Labels: Needs Second Approval

#9872 [Kotlin Migration] ExportDialogsFactory
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt
Labels: Needs Second Approval

#9870 [Kotlin Migration] MediaSyncException
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/exception/MediaSyncException.kt
Labels: Needs Second Approval

#9874 [Kotlin Migration] WhiteboardPenColor
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/model/WhiteboardPenColor.kt
Labels: Pending Merge

#9875 [Kotlin Migration] BasicAudioClipFieldController
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
Labels: Needs Second Approval

#9868 Kotlin Migration: TtsParser.java -> .kt
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
Labels: Pending Merge

#9880 [Kotlin Migration] AudioRecordingField
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt
Labels: Needs Second Approval

#9888 refactor(v16): Use libAnki class for TTS
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
  AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
Labels: Pending Merge

#9832 Kotlin migration TagsDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
Labels: Needs Second Approval

#9893 feat(record-audio): Show Preview of Fields
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/IMultimediaEditableNote.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.java
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Needs Review, Strings

#9823 [Kotlin Migration] DatabaseChangeDecorator
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.kt
Labels: Needs Second Approval

#9907 Fixed alpha issues for FAB menu
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
  AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
Labels: Needs Second Approval

#9918 Updated strings from Crowdin 20221118
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-be/02-strings.xml
  AnkiDroid/src/main/res/values-be/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-cs/18-standard-models.xml
  AnkiDroid/src/main/res/values-or/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/04-network.xml
  AnkiDroid/src/main/res/values-or/05-feedback.xml
  AnkiDroid/src/main/res/values-or/06-statistics.xml
  AnkiDroid/src/main/res/values-or/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-or/09-backup.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/11-arrays.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/06-statistics.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
  AnkiDroid/src/main/res/values-tr/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-tr/17-model-manager.xml
  AnkiDroid/src/main/res/values-tr/18-standard-models.xml
  AnkiDroid/src/main/res/values-zh-rCN/16-multimedia-editor.xml
  docs/marketing/localized_description/marketdescription-or.txt
Labels: Pending Merge

#9909 Changes for Issue 5844 - Forgotten AnkiWeb e-mail
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
  AnkiDroid/src/main/res/layout/my_account.xml
  AnkiDroid/src/main/res/values/04-network.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Needs Second Approval

#9917 revert: Highlight Selected Deck (f96bdfb)
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Review High Priority

#9928 [Kotlin Migration] AudioRecorder
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
Labels: Needs Second Approval

#9927 [Kotlin Migration] AudioPlayer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt
Labels: Needs Second Approval

#9926 [Kotlin Migration] ActionButtonStatus
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
Labels: Needs Second Approval

#9924 [Kotlin Migration] FieldState
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
Labels: Needs Second Approval

#9921 [Kotlin Migration] ActionButtons
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
Labels: Needs Second Approval

#9920 [Kotlin Migration] CardMarker
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.kt
Labels: Needs Second Approval

#9931 fix: there was a nullability merge dispute in ActionButtons
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
Labels: Review High Priority

#9932 Dependency updates 20211118
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  api/build.gradle
  build.gradle
  lint-release.xml
Labels: Pending Merge

#9948 Removed the unused string and updated the used link
  AnkiDroid/src/main/java/com/ichi2/anki/Info.java
  AnkiDroid/src/main/res/values/constants.xml
Labels: Needs Second Approval
