Repository ankidroid/Anki-Android, pull requests merged in 2021-06, with the labels that each got.

#9028 Add Ktlint pre-commit hook
  AnkiDroid/build.gradle
  pre-commit
Labels: Needs Second Approval

#9033 Fix link to help section of cloze deletion
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
  AnkiDroid/src/main/res/values/constants.xml
Labels: Needs Second Approval

#9011 Fixed Bug Crash TagsDialog not attached to a Context
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval

#9018 fix: open nav menu clears search
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.java
  AnkiDroid/src/main/res/menu/card_browser.xml
Labels: Pending Merge

#9015 Add preference for full screen navigation drawer
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
  AnkiDroid/src/main/res/layout-television/reviewer.xml
  AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
  AnkiDroid/src/main/res/layout/activity_anki_stats.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
  AnkiDroid/src/main/res/layout/homescreen.xml
  AnkiDroid/src/main/res/layout/navigation_drawer_layout.xml
  AnkiDroid/src/main/res/layout/reviewer.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
  AnkiDroid/src/main/res/layout/studyoptions.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
Labels: Needs Second Approval, Review High Priority

#8998 Fix for empty search results and wrong card count
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Needs Second Approval

#9040 Fixed Cloze Card Preview
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
Labels: Needs Second Approval

#8800 Test for card browser changing color when card flag changes
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Needs Second Approval

#9036 Update list when field reposition is done
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Labels: Needs Second Approval

#8756 Display study options properly on start on tablet
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Needs Second Approval

#8790 Enhanced card and tag buttons in Add Note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/res/drawable/button_background.xml
  AnkiDroid/src/main/res/layout/note_editor.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
Labels: Needs Second Approval

#9020 #8976: Add optional 2x2 grid for answer buttons
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Strings

#8600 Fixes #8598: Pop DeckPicker from back stack on return via Navigation Drawer
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Labels: Needs Review

#9091 feat: Add password & email icon to login form
  AnkiDroid/src/main/res/drawable/ic_baseline_email_24.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_lock_24.xml
  AnkiDroid/src/main/res/layout/my_account.xml
Labels: Needs Review, Priority-Low

#9060 Remove boolean check in onProgressUpdate of DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Strings

#9099 Increasing privacy policy compliance
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
  AnkiDroid/src/main/res/drawable/ic_baseline_description_24.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_policy_24.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_privacy_tip_24.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.java
Labels: Needs Second Approval

#9133 Dependency updates 20210622
  .github/dependabot.yml
  AnkiDroid/build.gradle
Labels: Pending Merge

#9108 Kotlin: enable `AutoCloseable.use { }`
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
  lint-rules/build.gradle
Labels: Needs Review

#9143 Show total card count in DeckPicker when no cards are due
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Strings

#9137 fix: Use primary color for Custom Tabs top bar
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Needs Review

#9062 Add preference for setting double click time interval in study screen
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java
Labels: Strings

#9156 Updated strings from Crowdin 20210627
  AnkiDroid/src/main/res/values-cs/01-core.xml
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/03-dialogs.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-heb/01-core.xml
  AnkiDroid/src/main/res/values-heb/17-model-manager.xml
  AnkiDroid/src/main/res/values-heb/18-standard-models.xml
  AnkiDroid/src/main/res/values-or/01-core.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#8718 NF: comment and rename Task related classes
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
  AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
Labels: Pending Merge

#8591 Don't count 'forget' and 'set due date' cards as reviews
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Pending Merge

#9166 Added additional unit tests to MissingImageHandlerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java
Labels: Needs Second Approval

#9157 Preferences constant
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Labels: Needs Second Approval

#9080 [Preference] Paste clipboard image as PNG
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Pending Merge, Strings
