Repository ankidroid/Anki-Android, pull requests merged in 2021-09, with the labels that each got.

#9492 NF: uses string constant for current deck and active decks
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
Labels: Needs Second Approval

#8339 NF: uses hash set/map which take size as init instead of capacity
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/language/LanguagesListerGlosbe.java
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvSniffer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
  AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java
  AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.java
  AnkiDroid/src/main/java/com/wildplot/android/parsing/TopLevelParser.java
Labels: Pending Merge

#9493 Updated strings from Crowdin 20210904
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  AnkiDroid/src/main/res/values-sat/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#9248 Rename Note Type: randomizeName if it is already exist
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
Labels: Pending Merge

#9517 Storage: in V16 - don't add collection data
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
  AnkiDroid/src/test/java/com/ichi2/libanki/NoteWithColTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
Labels: Pending Merge

#9534 Dependency updates 20210921
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge

#9539 refactor: onboarding
  AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingUtilsTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ReflectionUtils.kt
Labels: Pending Merge

#9551 translations: add 'Sardinian' (ISO 'sc')
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
  tools/update-localizations.py
Labels: Pending Merge, Strings

#9554 style(lint): report lint errors via text on stdout
  lint.gradle
Labels: Pending Merge

#9552 Updated strings from Crowdin 20210924
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rAR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rES/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rES/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-it/01-core.xml
  AnkiDroid/src/main/res/values-it/02-strings.xml
  AnkiDroid/src/main/res/values-it/03-dialogs.xml
  AnkiDroid/src/main/res/values-it/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-it/10-preferences.xml
  AnkiDroid/src/main/res/values-it/11-arrays.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/04-network.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/06-statistics.xml
  AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/04-network.xml
  AnkiDroid/src/main/res/values-sc/01-core.xml
  AnkiDroid/src/main/res/values-sc/02-strings.xml
  AnkiDroid/src/main/res/values-sc/03-dialogs.xml
  AnkiDroid/src/main/res/values-sc/04-network.xml
  AnkiDroid/src/main/res/values-sc/05-feedback.xml
  AnkiDroid/src/main/res/values-sc/06-statistics.xml
  AnkiDroid/src/main/res/values-sc/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sc/08-widget.xml
  AnkiDroid/src/main/res/values-sc/09-backup.xml
  AnkiDroid/src/main/res/values-sc/10-preferences.xml
  AnkiDroid/src/main/res/values-sc/11-arrays.xml
  AnkiDroid/src/main/res/values-sc/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-sc/17-model-manager.xml
  AnkiDroid/src/main/res/values-sc/18-standard-models.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  docs/marketing/localized_description/ankidroid-titles.txt
  docs/marketing/localized_description/marketdescription-pt-BR.txt
  docs/marketing/localized_description/marketdescription-sc.txt
Labels: Pending Merge

#9564 ecosystem compat: set default rev limit to 200
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Review

#9567 Updated strings from Crowdin 20210928
  AnkiDroid/src/main/res/values-be/02-strings.xml
  AnkiDroid/src/main/res/values-sat/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-sc/02-strings.xml
  AnkiDroid/src/main/res/values-sc/03-dialogs.xml
  AnkiDroid/src/main/res/values-sc/10-preferences.xml
  AnkiDroid/src/main/res/values-sk/01-core.xml
  AnkiDroid/src/main/res/values-sk/02-strings.xml
  AnkiDroid/src/main/res/values-sk/03-dialogs.xml
  AnkiDroid/src/main/res/values-sk/04-network.xml
  AnkiDroid/src/main/res/values-sk/10-preferences.xml
  AnkiDroid/src/main/res/values-sk/11-arrays.xml
  AnkiDroid/src/main/res/values-sk/16-multimedia-editor.xml
Labels: Pending Merge
