Repository ankidroid/Anki-Android, pull requests merged in 2021-08, with the labels that each got.

#9349 feat: pink, turquoise & purple flags
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/res/drawable/ic_flag_pink.xml
  AnkiDroid/src/main/res/drawable/ic_flag_purple.xml
  AnkiDroid/src/main/res/drawable/ic_flag_turquoise.xml
  AnkiDroid/src/main/res/menu-television/reviewer.xml
  AnkiDroid/src/main/res/menu/card_browser.xml
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.java
Labels: Needs Review, Strings

#9353 NF: remove `throws JSONException`
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
Labels: Needs Second Approval

#9351 NF: comment model/deck/deckconfig
  AnkiDroid/src/main/java/com/ichi2/libanki/Deck.java
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
Labels: Needs Second Approval

#9350 NF: assert double equals uses Delta
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
Labels: Needs Second Approval

#9213 Paste as PNG, if alpha channel exists
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
Labels: Needs Second Approval

#9326 SchemaV16: Implement Decks [WIP, but ready for review/merge]
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DecksBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
Labels: Pending Merge

#9245 New JS API for bury & suspend card and bury & suspend note and tag card
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Needs Review

#9290 NF: Start on Preference deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.java
Labels: Pending Merge

#9229 Implement better download and import system for shared decks
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
  AnkiDroid/src/main/res/drawable/close_icon.xml
  AnkiDroid/src/main/res/drawable/home_icon.xml
  AnkiDroid/src/main/res/layout/activity_shared_decks.xml
  AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
  AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
Labels: Strings

#9247 JS API to open card browser and search with query
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#9374 Make HTML/JS debugging default to true in prefs in DEBUG build
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Labels: Needs Second Approval

#9373 Dependency updates 20210805
  AnkiDroid/build.gradle
Labels: Pending Merge

#9362 Use MediaStore to save whiteboard for API>28
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
Labels: Pending Merge

#9388 Fix V2 Scheduler .colpkg collection import
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
Labels: Pending Merge

#9405 make "Add From Gallery" visible on Amazon Build Flavor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Labels: Waiting For Feedback, Pending Merge

#9409 CompatV21 & V29 saveImage(): return Uri instead path
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
Labels: Needs Second Approval

#9403 Dependency updates 20210812
  AnkiDroid/build.gradle
Labels: Pending Merge

#9429 Dependency updates 20210819
  AnkiDroid/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#9414 NF: improve activityHandlesRestoreBackup if create lead throws
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
Labels: Pending Merge

#9434 feat: keyboard shortcuts for new flags
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
Labels: Needs Review

#9412 fix: action bar button spacing
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
  AnkiDroid/src/main/res/layout/rtl_menu_item.xml
Labels: Needs Review

#9420 fix tests[EmptyApplication] Reset static state
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.java
  AnkiDroid/src/test/java/com/ichi2/testutils/EmptyApplication.java
Labels: Needs Review

#9410 Ensure that onboarding can be cancelled
  AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingUtilsTest.kt
Labels: Needs Second Approval

#9444 feat: convert preferences to support library
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.java
  AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java
  AnkiDroid/src/main/res/layout/preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Pending Merge

#9472 docs: animation[Enabled/Disabled]
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
Labels: Needs Review
