Repository ankidroid/Anki-Android, pull requests merged in 2021-04, with the labels that each got.

#8418 Updated strings from Crowdin 20210331
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/03-dialogs.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/03-dialogs.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-fa/02-strings.xml
  AnkiDroid/src/main/res/values-fa/03-dialogs.xml
  AnkiDroid/src/main/res/values-fa/04-network.xml
  AnkiDroid/src/main/res/values-fa/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-hi/03-dialogs.xml
  AnkiDroid/src/main/res/values-hi/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-hi/10-preferences.xml
  AnkiDroid/src/main/res/values-it/01-core.xml
  AnkiDroid/src/main/res/values-it/02-strings.xml
  AnkiDroid/src/main/res/values-it/03-dialogs.xml
  AnkiDroid/src/main/res/values-it/04-network.xml
  AnkiDroid/src/main/res/values-it/10-preferences.xml
  AnkiDroid/src/main/res/values-it/18-standard-models.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/04-network.xml
  AnkiDroid/src/main/res/values-or/09-backup.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/10-preferences.xml
  AnkiDroid/src/main/res/values-sv/01-core.xml
  AnkiDroid/src/main/res/values-tt/02-strings.xml
  AnkiDroid/src/main/res/values-tt/03-dialogs.xml
  AnkiDroid/src/main/res/values-tt/04-network.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-ar.txt
  docs/marketing/localized_description/marketdescription-fr.txt
  docs/marketing/localized_description/marketdescription-it.txt
Labels: Pending Merge

#8381 search deck in NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Needs Second Approval, Strings

#8338 Fixes #4759 'Custom study: Don't show "increase new card limit" when no new cards'
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
Labels: Needs Second Approval

#8433 Minor refactorings and SQL window size calculation fixed
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Labels: Pending Merge

#8410 NF: Introduce List assertion
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
  AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.java
Labels: Pending Merge

#8414 Preventing OR search query from bypassing RestrictOnDeck
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Pending Merge

#8456 Call super method in DeckPicker.onRequestPermissionResult
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Labels: Pending Merge

#8452 Improved UI for the Add Decks Button
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
  AnkiDroid/src/main/res/drawable-v21/fab_label_background.xml
  AnkiDroid/src/main/res/drawable/fab_label_background_black_pre21.xml
  AnkiDroid/src/main/res/drawable/fab_label_background_pre21.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Needs Second Approval

#8457 Implemented toast message when back is pressed
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval

#8455 chore: remove pre-API21 workaround for language icon in prefs
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Pending Merge

#8463 Set focus on 'Create deck' name field by default
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
Labels: Needs Second Approval

#8471 Upgrade ankidroid backend to 0.1.4
  AnkiDroid/build.gradle
Labels: Pending Merge

#8475 Use JDK-native immutable list implementation for locale list
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
Labels: Pending Merge

#8497 Added test for AssetHelper util class.
  AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.java
Labels: Needs Second Approval

#8492 Fix "A PART OF" Code style for non-public, non-static fields #8387
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
Labels: Needs Second Approval

#8504 Dependency updates 20210407
  AnkiDroid/build.gradle
Labels: Pending Merge

#8470 Reverse Activity transition for RTL language
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.java
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/Info.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Labels: Needs Second Approval

#8503 Fix "A PART OF" Code style for non-public, non-static fields #8387
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.java
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
Labels: Needs Second Approval

#8486 Fixes #8260 Moved Support AnkiDroid to navigation drawer
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
  AnkiDroid/src/main/res/drawable/ic_heart_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_support_ankidroid.xml
  AnkiDroid/src/main/res/menu/navigation_drawer.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.java
Labels: Needs Second Approval

#8500 Get deck name using JS API
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
Labels: Needs Second Approval

#8480 [Modified]: Action buttons for cards changed to OnTouch.
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Needs Second Approval

#8505 tests: Fix NullPointerException
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Labels: Needs Review

#8510 fix crash: NullPointerException while syncing
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
  AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.java
Labels: Needs Review

#8498 Add unit test for TextCardExporter
  AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
Labels: Pending Merge

#8484 Replace timebox notice with a popup
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#8519 Improved the icons of community menu with officials icon
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
  AnkiDroid/src/main/res/drawable/discord.xml
  AnkiDroid/src/main/res/drawable/facebook.xml
  AnkiDroid/src/main/res/drawable/ic_link_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_mail_outline_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_message_black_24dp.xml
  AnkiDroid/src/main/res/drawable/reddit.xml
  AnkiDroid/src/main/res/drawable/twitter.xml
Labels: Pending Merge

#8521 Fix "A PART OF" Code style for non-public, non-static fields #8387
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Meaning.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Phrase.java
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvDialect.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReader.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvSniffer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/CountingFileRequestBody.java
  AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java
  AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.java
  AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONException.java
Labels: Needs Second Approval

#8393 Unit Test for DeckNameComparator
  AnkiDroid/src/test/java/com/ichi2/utils/DeckNameComparatorTest.java
Labels: Needs Second Approval

#8514 NF: Adding a reset to default button for setting default directory path
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Labels: Needs Second Approval

#8511 Added tests to the utility functions of the Tags class
  AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.java
Labels: Pending Merge, Waiting For Feedback

#8535 Unit Tests for JSONObject
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
Labels: Needs Second Approval

#8532 Fixes Code style for non-public, non-static fields #8387
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Response.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Tuc.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
  AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/UnifiedTrustManager.java
  AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.java
Labels: Needs Second Approval

#8574 NF: NonNull note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Labels: Pending Merge

#8585 NF: rename: id_dont_create -> id_for_name
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
Labels: Needs Review

#8540 NF: comment and simplify DismissNote
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval

#8544 NF: `DismissNotes`'s `actualTask` return whether it succeeded
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval

#8549 NF: Improve DeckPreviewStatistics type
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
Labels: Needs Second Approval

#8559 Added a test to check all the constants in actions class are annotated
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java
Labels: Needs Second Approval

#8568 NF: Card and Note constructors are not-python like
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
Labels: Anki Ecosystem Compatibility, Needs Second Approval

#8557 Add unit tests for NamedJSONComparator class
  AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
Labels: Needs Second Approval, Waiting For Feedback

#8569 NF: PreviewerCard's note is final
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
Labels: Needs Second Approval

#8531 Fixes #5404: Fix AnkiStatsTaskHandler's AsyncTasks' memory leaks & singleton pattern
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
Labels: Needs Second Approval, Waiting For Feedback

#8553 Display Order of Card Browser corrected
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Needs Second Approval, Waiting For Feedback

#8590 test: parsing hours as JUnit parameterized test
  AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
Labels: Needs Second Approval

#8595 Added test to ensure deepClone() returns a new instance
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
Labels: Needs Second Approval

#8596 strip does nothing on stripped string
  AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java
Labels: Needs Second Approval

#8518 Improve dialog usage by setting default focus on EditText
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
  AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.java
Labels: Pending Merge, Waiting For Feedback

#8441 Fixes #7679 Lookup button enabled/disabled depending on Lookup Dictionary preference
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.java
Labels: Pending Merge

#8605 Attempt to de-flake "regression_test_preview" with sleeps
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Pending Merge

#8599 Fix analytics constants tests
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java
Labels: Needs Review

#8536 Deprecate getCol().getDecks().getDecks()
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Review

#8538 confForDid: use default on invalid configuration
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
Labels: Anki Ecosystem Compatibility, Needs Review

#8580 NF: Extract helper method from Decks
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Review

#8581 NF: Convert Deck methods to return List
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Needs Review

#8582 Decks: refactor restoreToDefault for Rust
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
Labels: Needs Review

#8606 fix: Open DeckPicker if collection path changes
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Labels: Needs Review

#8571 NF: NonNull on task
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge, Waiting For Feedback

#8389 Ensures forbidden symbols are removed from new field names
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Labels: Waiting For Feedback

#8615 lint: fix build errors
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Labels: Pending Merge

#8619 nf: remove mOnStatisticsActivityResult
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Labels: Pending Merge

#8617 feat: Enable jacoco reports to be opened
  AnkiDroid/jacoco.gradle
Labels: Pending Merge

#8528 NF: Refactor `Finder`
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Labels: Needs Review, Waiting For Feedback

#8629 Clear ACRA on cancel, use ACRA data for rate limit
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
Labels: Pending Merge

#8625 Lint: Lint rule for use of UIUtils.showSnackbar instead of Snackbar.make
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsage.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsageTest.java
Labels: Needs Second Approval

#8626 Repair a crash on tablet
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
Labels: Needs Second Approval

#8642 Fix: Duplicate cards shown in Card Browser
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskSearchCardsTest.java
Labels: Review High Priority

#8633 NF: Progress dialog deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
  AnkiDroid/src/main/res/layout/activity_translation.xml
Labels: Needs Second Approval, Waiting For Feedback

#8579 Fixing gestures with answer buttons not working
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Labels: Pending Merge, Waiting For Feedback

#8427 Fixes #8151 Build flavors for Amazon Appstore and Google Playstore
  .github/workflows/lint.yml
  AnkiDroid/build.gradle
  AnkiDroid/jacoco.gradle
  AnkiDroid/src/amazon/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
  AnkiDroid/src/main/java/com/ichi2/utils/CheckCameraPermission.java
  tools/parallel-package-release.sh
  tools/release.sh
Labels: Needs Review

#8663 Add copyright headers
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialogFactory.java
  AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java
  AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.java
Labels: Pending Merge

#8438 Implement Create New Deck Function In Add Note Activity
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
  AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.java
Labels: Pending Merge, Strings

#8622 Test: Check if Illegal Characters at the start of Fields get handled
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
Labels: Pending Merge

#8664 lint: add missing copyright
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java
  AnkiDroid/src/main/java/com/ichi2/anki/exception/ManuallyReportedException.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.java
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java
  AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.java
  AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java
  AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.java
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
  AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java
  AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.java
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java
  AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java
Labels: Needs Review

#8552 Simplify schedule collection task listener
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Labels: Pending Merge, Waiting For Feedback

#8665 Fix: Prevent crash on long pressing at end of card browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Labels: Pending Merge

#8655 Add Statistics regression test to #8626
  AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java
Labels: Pending Merge

#8683 NF: add copyrights for Mike Hardy files
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AcraAnalyticsInteraction.java
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnalyticsDialogFragment.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.java
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Labels: Pending Merge

#8657 Labels added to dayOffset preference dialog seekbar
  AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Pending Merge

#8688 NF: add copyright header for Arthur Milchior with year
  AnkiDroid/src/main/java/com/ichi2/async/ProgressSenderAndCancelListener.java
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskListener.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java
  AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.java
  AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/EmptyNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/NegatedConditional.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateError.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Text.java
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java
  AnkiDroid/src/main/java/com/ichi2/utils/BooleanGetter.java
  AnkiDroid/src/main/java/com/ichi2/utils/CardGetter.java
  AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.java
  AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java
  AnkiDroid/src/main/java/com/ichi2/utils/NamedJSONComparator.java
  AnkiDroid/src/main/java/com/ichi2/utils/PairWithBoolean.java
  AnkiDroid/src/main/java/com/ichi2/utils/PairWithCard.java
  AnkiDroid/src/main/java/com/ichi2/utils/Triple.java
Labels: Pending Merge

#8698 NF: Add copyright header for Enno Hermann
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.java
Labels: Pending Merge

#8699 Add Tests: BackupManager
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.java
Labels: Pending Merge

#8695 Use framework / built-in sqlite implementation
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
Labels: Needs Review

#8701 Test: Fix ConcurrentModificationException
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
Labels: Pending Merge

#8700 docs: Add clarification to LanguageUtilsTest
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
Labels: Pending Merge

#8714 Change mic icon to audio in advanced editor of notes
  AnkiDroid/src/main/res/drawable/ic_audioclip_white.xml
  AnkiDroid/src/main/res/menu/activity_edit_text.xml
Labels: Waiting For Feedback

#8738 NF: RepairCollectionn typo
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Pending Merge

#8735 Ensure that CheckCardSelection gets only checked cards
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval
