Repository ankidroid/Anki-Android, pull requests merged in 2021-10, with the labels that each got.

#9481 Migrate CardAppearance to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
Labels: Pending Merge

#9579 lint[tests]: VariableNamingDetector
  AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.java
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.java
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
Labels: hacktoberfest-accepted

#9494 Migrate AnkiFont to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.kt
Labels: Needs Second Approval

#9495 Migrate CardTemplate to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardTemplate.kt
Labels: Needs Second Approval

#9578 Add class name example in kotlinMigration.gradle
  AnkiDroid/kotlinMigration.gradle
Labels: Pending Merge, hacktoberfest-accepted

#9737 Migrate ActivityTransitionAnimation to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
Labels: Needs Second Approval

#9744 build(deps): dependency updates 20211031
  AnkiDroid/build.gradle
Labels: Pending Merge

#9748 docs: Improve Kotlin Migration
  docs/kotlin-migration.md
Labels: Needs Review
