Repository ankidroid/Anki-Android, pull requests merged in 2021-05, with the labels that each got.

#8707 Convert remaining PNG files to SVG where possible
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java
  AnkiDroid/src/main/res/drawable-hdpi/anki.png
  AnkiDroid/src/main/res/drawable-hdpi/av_pause.png
  AnkiDroid/src/main/res/drawable-hdpi/av_play.png
  AnkiDroid/src/main/res/drawable-hdpi/av_rec.png
  AnkiDroid/src/main/res/drawable-hdpi/av_rec_stop.png
  AnkiDroid/src/main/res/drawable-hdpi/av_stop.png
  AnkiDroid/src/main/res/drawable-hdpi/ic_action_suspend_dropdown.png
  AnkiDroid/src/main/res/drawable-hdpi/ic_eraser_variant_white_24dp.png
  AnkiDroid/src/main/res/drawable-hdpi/ic_flip_to_back_white_24px_dropdown.png
  AnkiDroid/src/main/res/drawable-hdpi/ic_stat_notify.png
  AnkiDroid/src/main/res/drawable-hdpi/spinner_triangle.png
  AnkiDroid/src/main/res/drawable-hdpi/widget_add_note.png
  AnkiDroid/src/main/res/drawable-mdpi/av_pause.png
  AnkiDroid/src/main/res/drawable-mdpi/av_play.png
  AnkiDroid/src/main/res/drawable-mdpi/av_rec.png
  AnkiDroid/src/main/res/drawable-mdpi/av_rec_stop.png
  AnkiDroid/src/main/res/drawable-mdpi/av_stop.png
  AnkiDroid/src/main/res/drawable-mdpi/ic_action_suspend_dropdown.png
  AnkiDroid/src/main/res/drawable-mdpi/ic_eraser_variant_white_24dp.png
  AnkiDroid/src/main/res/drawable-mdpi/ic_stat_notify.png
  AnkiDroid/src/main/res/drawable-mdpi/spinner_triangle.png
  AnkiDroid/src/main/res/drawable-xhdpi/av_pause.png
  AnkiDroid/src/main/res/drawable-xhdpi/av_play.png
  AnkiDroid/src/main/res/drawable-xhdpi/av_rec.png
  AnkiDroid/src/main/res/drawable-xhdpi/av_rec_stop.png
  AnkiDroid/src/main/res/drawable-xhdpi/av_stop.png
  AnkiDroid/src/main/res/drawable-xhdpi/ic_action_suspend_dropdown.png
  AnkiDroid/src/main/res/drawable-xhdpi/ic_eraser_variant_white_24dp.png
  AnkiDroid/src/main/res/drawable-xhdpi/ic_flip_to_back_white_24px_dropdown.png
  AnkiDroid/src/main/res/drawable-xhdpi/ic_stat_notify.png
  AnkiDroid/src/main/res/drawable-xhdpi/spinner_triangle.png
  AnkiDroid/src/main/res/drawable-xhdpi/widget_add_note.png
  AnkiDroid/src/main/res/drawable-xxhdpi/ic_action_suspend_dropdown.png
  AnkiDroid/src/main/res/drawable-xxhdpi/ic_eraser_variant_white_24dp.png
  AnkiDroid/src/main/res/drawable-xxhdpi/ic_flip_to_back_white_24px_dropdown.png
  AnkiDroid/src/main/res/drawable-xxhdpi/ic_stat_notify.png
  AnkiDroid/src/main/res/drawable-xxhdpi/spinner_triangle.png
  AnkiDroid/src/main/res/drawable-xxhdpi/widget_add_note.png
  AnkiDroid/src/main/res/drawable-xxxhdpi/ic_eraser_variant_white_24dp.png
  AnkiDroid/src/main/res/drawable-xxxhdpi/ic_flip_to_back_white_24px_dropdown.png
  AnkiDroid/src/main/res/drawable-xxxhdpi/widget_add_note.png
  AnkiDroid/src/main/res/drawable/eraser.xml
  AnkiDroid/src/main/res/drawable/ic_action_suspend_dropdown.xml
  AnkiDroid/src/main/res/drawable/ic_anki.xml
  AnkiDroid/src/main/res/drawable/ic_flip_to_back_dropdown.xml
  AnkiDroid/src/main/res/drawable/ic_pause_white_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_play_arrow_white_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_rec.xml
  AnkiDroid/src/main/res/drawable/ic_rec_stop.xml
  AnkiDroid/src/main/res/drawable/ic_spinner_triangle.xml
  AnkiDroid/src/main/res/drawable/ic_stat_notify.xml
  AnkiDroid/src/main/res/drawable/ic_stop_white_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_widget_add_note.xml
  AnkiDroid/src/main/res/layout/dropdown_deck_selected_item.xml
  AnkiDroid/src/main/res/layout/widget_add_note.xml
Labels: Needs Second Approval, Waiting For Feedback

#8724 NF: remove mDismissCardHandler
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Pending Merge, Waiting For Feedback

#8734 NF: introduce TaskWithoutCol to simplify code
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Labels: Needs Second Approval

#8746 test: `ExtendedFragmentFactory#attachToFragmentManager`
  AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.java
Labels: Needs Second Approval

#8715 WhiteBoard : Improve UX
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.java
  AnkiDroid/src/main/res/layout-television/reviewer.xml
  AnkiDroid/src/main/res/layout/reviewer.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
  AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml
  AnkiDroid/src/main/res/menu-television/reviewer.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/styles.xml
Labels: Waiting For Feedback

#8730 [ Enhancement ] Card Template Editor UI
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/res/color/bottom_navigation_icon_color.xml
  AnkiDroid/src/main/res/color/bottom_navigation_text_color.xml
  AnkiDroid/src/main/res/drawable/ic_back.xml
  AnkiDroid/src/main/res/drawable/ic_css.xml
  AnkiDroid/src/main/res/drawable/ic_front.xml
  AnkiDroid/src/main/res/layout/card_template_editor_activity.xml
  AnkiDroid/src/main/res/layout/card_template_editor_item.xml
  AnkiDroid/src/main/res/menu/card_template_editor_navigation_bar_menu.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Labels: Needs Second Approval

#8570 NF: add some NonNull for notes
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Labels: Needs Second Approval

#8733 NF: Allow to execute task and listener without manager
  AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
Labels: Needs Second Approval, Waiting For Feedback

#8760 fixes: no custom study steps on schedv2
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/res/xml/cram_deck_options.xml
Labels: Needs Review

#8644 Card Browser, NoteEditor And Statistics : Improve "Search Deck" UX
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
Labels: Needs Second Approval

#8772 Add Tests for Card Template Editor BottomNavigationView
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Labels: Needs Second Approval

#8777 Speed up card browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Needs Review

#8792 build: android-gradle-plugin 4.2.0 + others
  AnkiDroid/build.gradle
  build.gradle
  lint-rules/build.gradle
Labels: Pending Merge

#8802 Fix jacoco reports w/correct per-flavor class dirs
  AnkiDroid/jacoco.gradle
Labels: Pending Merge

#8827 [Bug Fix] handled JSONException in cardTemplateEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Labels: Pending Merge, Waiting For Feedback

#8840 Dependency updates 20210514
  AnkiDroid/build.gradle
  build.gradle
  lint-rules/build.gradle
Labels: dependencies

#8824 Can open collection with no deck
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Second Approval

#8851 Updated strings from Crowdin 20210516
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-be/01-core.xml
  AnkiDroid/src/main/res/values-ca/01-core.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-ko/01-core.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-ko/11-arrays.xml
  AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ko/17-model-manager.xml
  AnkiDroid/src/main/res/values-ko/18-standard-models.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
  AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rTW/04-network.xml
  AnkiDroid/src/main/res/values-zh-rTW/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rTW/11-arrays.xml
Labels: Pending Merge, Strings

#8852 NumberFormatException fixed
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java
Labels: Needs Review

#8863 NF: change json null check
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Labels: Pending Merge

#8873 keep selected deck same after changing type of note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Pending Merge, Waiting For Feedback

#8872 set last selected deck Id in statistics
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
Labels: Waiting For Feedback

#8786 Card template editor save states
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Labels: Pending Merge

#8859 Fixed problem with aggregated data to one day in weeklyBreakdown in stats page
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Needs Review

#8878 Updated strings from Crowdin 20210519
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/18-standard-models.xml
  AnkiDroid/src/main/res/values-vi/01-core.xml
Labels: Pending Merge

#8898 NF: copy android's json tests
  AnkiDroid/src/main/java/com/ichi2/utils/JSON.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
  AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
Labels: Pending Merge

#8891 Fixed Bugs when image is pasted from clipboard.
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Waiting For Feedback

#8887 Fixed crash on file selection
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Labels: Pending Merge

#8894 Fix NullPointerException in DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Needs Triage, Waiting For Feedback

#8906 Dependency updates 20210522
  AnkiDroid/build.gradle
  api/build.gradle
  lint-rules/build.gradle
Labels: Pending Merge

#8911 Updated strings from Crowdin 20210522
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
Labels: Pending Merge

#8909 fix(login): bubble custom sync server exception up during login
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Labels: Review High Priority

#8914 fix(StudyOptionsFragment): attempt to avert crash returning from review
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Labels: Needs Review

#8916 Uses correct locale
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Labels: Pending Merge

#8929 fix: SchedV2 was used instead of SchedV1
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.java
Labels: Review High Priority

#8932 Updated strings from Crowdin 20210525
  AnkiDroid/src/main/res/values-ms/01-core.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
  AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rTW/04-network.xml
  AnkiDroid/src/main/res/values-zh-rTW/10-preferences.xml
Labels: Pending Merge

#8922 lint: remove unknown issues from lint.xml
  lint-release.xml
Labels: Needs Review, Waiting For Feedback

#8949 fix ContentProvider/API related crashes
  AnkiDroid/build.gradle
Labels: Pending Merge

#8953 fix(amazon): assemble amazon release w/universal APK, publish correct path
  AnkiDroid/build.gradle
  tools/release.sh
Labels: Pending Merge

#8964 Set deck to default if selected id doesn't exist
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Pending Merge

#8923 Fix timing for Automatic Display Answer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Labels: Pending Merge

#9000 Updated strings from Crowdin 20210528
  AnkiDroid/src/main/res/values-bn/01-core.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-hi/01-core.xml
  AnkiDroid/src/main/res/values-ko/01-core.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-ru/01-core.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  docs/marketing/localized_description/ankidroid-titles.txt
Labels: Strings

#9001 language: Add Kannada
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
  tools/update-localizations.py
Labels: Pending Merge, Strings

#9009 Fix floating point numbers for steps in Deck Options
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
Labels: Pending Merge

#9025 fix[Audio Import]: mpeg converted to mp3
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldControllerTest.java
Labels: Needs Review

#9026 increase max backups from 10 to 99
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Needs Review

#8987 Legacy template
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java
Labels: Pending Merge
