Repository ankidroid/Anki-Android, pull requests merged in 2021-07, with the labels that each got.

#9183 fix: remove maxLength on `paste_as_png_summary`
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Needs Review, Strings

#8782 Fixes #8761: Enabling second feature added in FilteredDeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/cram_deck_options.xml
Labels: Needs Second Approval

#9200 Populate all hours in hourly stats chart
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Needs Review

#9201 Updated strings from Crowdin 20210704
  AnkiDroid/src/main/res/values-cs/01-core.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-hi/01-core.xml
  AnkiDroid/src/main/res/values-hi/02-strings.xml
  AnkiDroid/src/main/res/values-hi/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-hi/10-preferences.xml
  AnkiDroid/src/main/res/values-km/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#9202 NF: more model
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Labels: Pending Merge

#9211 Fix DeckPickerTest tablet special cases to run in background
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Pending Merge

#9212 Added unit test documentation to ActivityStartupUnderBackupTest
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
Labels: Needs Second Approval

#9209 fix: Flaky tests failing on my Windows Machine
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Labels: Pending Merge

#9228 fix[Audio Insert]: Allow .ogg on Android 8
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Labels: Needs Review

#9224 fix[lint]: allow Kotlin companion objects
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.java
Labels: Needs Review

#9236 fix(stats): set hourly breakdown stats into 0-23 range by modulus
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
Labels: Pending Merge

#9237 Updated strings from Crowdin 20210710
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/06-statistics.xml
  AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ar/11-arrays.xml
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ar/17-model-manager.xml
  AnkiDroid/src/main/res/values-de/01-core.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-fa/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-it/01-core.xml
  AnkiDroid/src/main/res/values-it/10-preferences.xml
  AnkiDroid/src/main/res/values-it/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-mr/01-core.xml
  AnkiDroid/src/main/res/values-ms/01-core.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-pt-rPT/18-standard-models.xml
  AnkiDroid/src/main/res/values-te/01-core.xml
  docs/marketing/localized_description/marketdescription-ar.txt
Labels: Pending Merge

#9217 Added unit tests for 3 functions in NoteService
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
Labels: Needs Second Approval

#9243 fix: lint was not working in Anki-Android
  AnkiDroid/build.gradle
Labels: Review High Priority

#9253 Add preference for enabling onboarding in debug build
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
  AnkiDroid/src/main/res/values/constants.xml
Labels: Needs Second Approval

#9275 deprecation: fix createVideoThumbnail
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: Needs Review

#9258 Dependency updates 20210713
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
  gradle.properties
Labels: Pending Merge

#9261 rename: tap -> touch
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Needs Review

#9252 NF: clarify the actual set of API in CompatVN
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
Labels: Pending Merge

#9268 Added unit tests for OverviewStatsBuilder
  AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.java
Labels: Waiting For Feedback

#9240 NF: launchCollectionTask return Cancellable
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/async/Cancellable.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
  AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
  AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
  AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java
Labels: Pending Merge

#9205 Test: stabilize study options click test
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java
Labels: Pending Merge

#9284 fix: reviewer fullscreen ui
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Labels: Pending Merge

#9285 Fix issue of extra whitespace on top of study options in tablet
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Labels: Needs Second Approval

#9280 Update usage of deprecated stream types in MediaPlayer and AudioManager
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: Pending Merge, Waiting For Feedback

#9288 Add audio ducking back and use same instance of AudioFocusRequest
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: Needs Second Approval

#9294 fix tests: detect CI - use build config
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java
Labels: Review High Priority

#9296 Implement elevation for popup menus in Night themes
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Pending Merge, UI, Waiting For Feedback

#9310 NF: Extract "Preference Upgrade" code from DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
Labels: Needs Second Approval, Pending Merge

#9325 Updated strings from Crowdin 20210728
  AnkiDroid/src/main/res/values-de/01-core.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/03-dialogs.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-de/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-sv/04-network.xml
  AnkiDroid/src/main/res/values-sv/06-statistics.xml
  AnkiDroid/src/main/res/values-sv/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sv/10-preferences.xml
  AnkiDroid/src/main/res/values-sv/11-arrays.xml
  AnkiDroid/src/main/res/values-sv/17-model-manager.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
Labels: Pending Merge

#9322 fix[Audio Insert]: Make audio files selectable
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Labels: Pending Merge

#9330 build(deps): bump lint_version from 27.2.2 to 30.0.0
  build.gradle
  lint-rules/build.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderExistsTest.java
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
Labels: Pending Merge

#9340 Use MediaStore instead of direct file path access for DeckPicker background preference
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Labels: Needs Second Approval
