Repository ankidroid/Anki-Android, pull requests merged in 2022-04, with the labels that each got.

#10673 Add merged PR to milestone and remove specific labels
  .github/workflows/label.yml
  .github/workflows/milestone.yml
Labels: Waiting For Feedback, Pending Merge, Needs Second Approval

#10676 Fix auto label and milestone to PR
  .github/workflows/label.yml
  .github/workflows/milestone.yml
Labels: Needs Review, Needs Second Approval, CI

#10464 Edit feature added to custom toolbar button
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
  AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml
  AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, squash-merge

#10668 [kotlinCleanUp] ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
Labels: Needs Second Approval

#10692 fix: crash opening DeckOptions
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt
Labels: Needs Second Approval

#10678 [Kotlin Migration ] CardInfo to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
Labels: Needs Second Approval

#10699 fix(deck-selection): don't keep activities crash
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Needs Review

#10707 Kotlin Cleanup of StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Pending Merge

#10714 lint: Flashcard Viewer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
Labels: Pending Merge

#10717 style: fix emails
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Needs Review

#10718 lint: Add user dictionaries to reduce typos
  .gitignore
  .idea/dictionaries/android.xml
  .idea/dictionaries/anki.xml
  .idea/dictionaries/davidallison.xml
  .idea/dictionaries/usernames.xml
Labels: Needs Review

#10726 [Kotlin migration] MyAccount
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
Labels: Needs Second Approval

#10735 An icon added to the item of "Deck options" on Actionbar
  AnkiDroid/src/main/res/drawable/ic_tune_white.xml
  AnkiDroid/src/main/res/menu-television/reviewer.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
Labels: Pending Merge, squash-merge

#10727 [Bug] reschedule icon color isn't same as one of other icons
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#10566 Display instructions in generated translated files
  tools/update-localizations.py
Labels: squash-merge

#10761 [Kotlin migration] Statistics
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
Labels: Needs Second Approval

#10754 @KotlinCleanup("iteration with i") in Preferences.kt done
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Needs Second Approval

#10758 Close the Nav Drawer if same screen selected which was already opened
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Labels: Pending Merge

#10747 Kotlin Cleanup for HelpDialog.kt file
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
Labels: squash-merge

#10760 Rename the Reviews shortcut option to Study for clarity
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Labels: Needs Second Approval

#10753 Cleanup Kotlin in MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
Labels: Pending Merge, squash-merge

#10768 Updated strings from Crowdin 20220409
  AnkiDroid/src/main/res/values-nl/01-core.xml
  AnkiDroid/src/main/res/values-nl/02-strings.xml
Labels: Pending Merge

#10771 feat: Make Kotlin Cleanup Repeatable
  AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
Labels: Pending Merge

#10788 Dependency updates 20220411
  build.gradle
Labels: Pending Merge

#10798 fix: MIUI on Android 12 crash
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Labels: Needs Review, MIUI

#10775 [@KotlinCleanup] file AutoSizeCheckBoxPreference.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
Labels: Pending Merge, squash-merge

#10736 [Kotlin migration] CardTemplateBrowserAppearanceEditor
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
Labels: Pending Merge

#10730 Migrate LanguageUtil to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Labels: Pending Merge

#10778 Minor Fix for DeckPicker Translation/String Resource Issue
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Labels: Pending Merge

#10802 Updated strings from Crowdin 20220412
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-heb/01-core.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
Labels: Pending Merge

#10801 Test Matrix
  .github/workflows/tests_unit.yml
Labels: Pending Merge, squash-merge

#10642 Migrate ModelBrowser to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
Labels: Needs Second Approval

#10806 [Kotlin Migration] StringUtilTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
Labels: Needs Second Approval

#10808 refactor: convert CardTemplateTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.kt
Labels: Needs Review

#10812 refactor: convert ActionButtonStatusTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
Labels: Needs Review

#10810 refactor: convert MissingImageHandlerTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt
Labels: Needs Review

#10814 docs: improve JUnitNullAssertionDetector message
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
Labels: Needs Review

#10817 refactor: convert PeripheralKeymapTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Needs Review

#10819 refactor: convert ReminderServiceTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
Labels: Needs Review

#10821 refactor: convert OverviewStatsBuilderTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
Labels: Needs Review

#10822 refactor: convert AbstractFlashcardViewerKeyboardInputTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.kt
Labels: Pending Merge

#10809 refactor: convert GestureProcessorTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
Labels: Pending Merge

#10811 refactor: convert OnRenderProcessGoneDelegateTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
Labels: Pending Merge

#10816 refactor: convert KeyboardShortcutIntegrationTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
Labels: Pending Merge

#10690 kotlin cleanup of Reviewer.kt,BasicAudioRecordingFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
Labels: Needs Second Approval

#10825 refactor: convert ActivityStartupUnderBackupTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
Labels: Pending Merge

#10824 refactor: convert AbstractFlashcardViewerTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java
Labels: Pending Merge

#10828 refactor: convert CardBrowserNonAndroidTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt
Labels: Pending Merge

#10827 refactor: convert CardBrowser_CardCollectionTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowser_CardCollectionTest.kt
Labels: Pending Merge

#10826 refactor: convert BackupManagerIntegrationTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerIntegrationTest.kt
Labels: Pending Merge

#10803 refactor: Kotlin migration of CardBrowser
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.kt
Labels: Pending Merge

#10830 refactor: convert DeckOptionsTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/DeckOptionsTest.kt
Labels: Pending Merge

#10833 refactor: convert WhiteboardDefaultForegroundColorTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt
Labels: Pending Merge

#10834 refactor: convert TestCardTemplatePreviewer to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.kt
Labels: Pending Merge

#10836 refactor: convert IntentHandlerTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
Labels: Pending Merge

#10835 refactor: convert InitialActivityWithConflictTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
Labels: Pending Merge

#10844 fix build: conflicted conversion of CardBrowser
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowser_CardCollectionTest.kt
Labels: Pending Merge

#10831 refactor: convert PeripheralKeymapTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
Labels: Pending Merge, Blocked by dependency

#10720 fix: Minibar Flag Inconsistency
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnPageFinishedCallback.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#10842 [KotlinCleanUp] PreferencesTest
  AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Labels: Pending Merge

#10848 refactor: remove duplicate class: NullApplication
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/NullApplication.java
Labels: Needs Review

#10849 Add missing argument for the `onPageFinishedCallback`
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Second Approval

#10635 [Bug] After creating a subdeck, the parent deck's menu is displayed again
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Labels: Needs Second Approval

#10847 Migrate RecyclerSingleTouchAdapter to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RecyclerSingleTouchAdapter.kt
Labels: Pending Merge

#10859 Function to get `File` size
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
Labels: Review High Priority

#10852 Add language icon for Set TTS Language
  AnkiDroid/src/main/res/drawable/ic_language_white.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
Labels: Waiting For Feedback

#10845 Resolve @KotlinCleanup and fix build for CardBrowser_CardCollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserCardCollectionTest.kt
Labels: Pending Merge

#10865 refactor: Convert NoteEditorTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Needs Review

#10869 refactor: Convert RobolectricTestAnnotationTest to Kotlin
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTestAnnotationTest.kt
Labels: Pending Merge

#10864 refactor: Convert UsageAnalytics to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.kt
Labels: Pending Merge

#10870 refactor: Convert StudyOptionsFragmentTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.kt
Labels: Pending Merge

#10871 refactor: Convert TemporaryModelTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.kt
Labels: Pending Merge

#10872 refactor: Convert AbstractCollectionTaskTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.kt
Labels: Pending Merge

#10875 refactor: Convert MockTime to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
Labels: Pending Merge

#10880 refactor: Convert AnkiPackageExporter to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
Labels: Needs Review

#10881 refactor: Convert DeckAdapter to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
Labels: Needs Review

#10861 Fix: app name now shows parallel name for parallel packages
  tools/parallel-package-name.sh
Labels: Pending Merge

#10884 [KotlinCleanUp] KeyboardShortcutIntegrationTest
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
Labels: Needs Second Approval, squash-merge

#10912 CI: ignore flaky test on Windows [version16CollectionOpen]
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Review High Priority

#10856 Added more choices for customButtonDeckOption Preference
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Needs Second Approval

#10879 Resolves accessiblity issue in toolbar hamburger icon
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval, Strings, squash-merge

#10850 [Kotlin migration ] AnalyticsTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
Labels: Pending Merge

#10888 Kotlin clean up recyler single touch adapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RecyclerSingleTouchAdapter.kt
Labels: Pending Merge, squash-merge

#10889 Migrate AppCompatPreferenceActivity to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Pending Merge

#10890 [Kotlin Migration] TagsTest.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
Labels: Pending Merge

#10891 Don't hide flag and marked icons from minibar on fullscreen
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#10885 refactor: extract TreeNode from AbstractDeckTreeNode
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Pending Merge

#10904 Migrate ActionBarOverflow to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.kt
Labels: Pending Merge

#10905 [Kotlin Migration] ClipBoardUtilTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/ClipboardUtilTest.kt
Labels: Pending Merge

#10921 refactor: SyncErrorDialogListener: collection access
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Pending Merge

#10854 Update when FAB should close or hide while navigating the app
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Pending Merge, squash-merge

#10907 [Kotlin Migration] TagsListTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt
Labels: Pending Merge

#10908 [Kotlin Migration] HtmlUtilsTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/HtmlUtilsTest.kt
Labels: Pending Merge

#10910 [Kotlin Migration] BackupManagerTestUtilities
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.kt
Labels: Pending Merge

#10911 [Kotlin Migration] MapUtilTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.kt
Labels: Pending Merge

#10913 [Kotlin Migration] BundleUtilsTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
Labels: Pending Merge

#10914 [kotlin Migration ] CompatCopyFileTest.kt
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.kt
Labels: Pending Merge

#10915 [Kotlin Migration] ImageFieldTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.kt
Labels: Pending Merge

#10916 [Kotlin Migration] ListUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.kt
Labels: Pending Merge

#10919 refactor: Convert LegacyDecksTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt
Labels: Pending Merge

#10920 Decks: Add JSON highlighting
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Labels: Pending Merge

#10918 refactor: Convert LaTeXTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt
Labels: Pending Merge

#10924 refactor: Convert DeckPicker to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
Labels: Pending Merge

#10928 Kotlin Cleanup: DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#10926 Fixed "CheckMedia" causing crash
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#10929 Migrate SeekBarPreferenceCompat to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
Labels: Pending Merge

#10933 Unit test: for catch part in JSONObject
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Pending Merge, squash-merge

#10934 refactor: convert AnkiAssertTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertTest.kt
Labels: Pending Merge

#10936 refactor: IField - add nullability annotations
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.java
Labels: Pending Merge

#10938 Fix ModelBrowser activity title
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
Labels: Pending Merge

#10946 refactor: Convert UndoAction to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.kt
Labels: Pending Merge

#10951 refactor: Convert PreferenceUtils to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.kt
Labels: Pending Merge

#10956 refactor: AnalyticsTest - Kotlin Cleanup
  AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
Labels: Pending Merge

#10957 refactor: Convert RtlCompliantActionProviderTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/ui/RtlCompliantActionProviderTest.kt
Labels: Pending Merge

#10960 Migrate ServiceConnection to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/ServiceConnection.kt
Labels: Pending Merge

#10963 JSONObjectTest.kt : changing the variable name from Object to testObject
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Pending Merge

#10964 Fixed "don't keep activities" crash on HelpDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
Labels: Waiting For Feedback, Needs Second Approval

#10959 Migrate CustomTabsHelper to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Labels: Pending Merge

#10940 [Kotlin migration] PreviewerTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
Labels: Pending Merge

#10193 [Kotlin Pre-Migration] Compat
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.kt
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Pending Merge, squash-merge

#10897 Improved Preferences instantiation
  AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Labels: Pending Merge, squash-merge

#10971 refactor: Convert BackendEmulatingOpenConflict to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.kt
Labels: Pending Merge

#10972 refactor: Convert CollectionUtils to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.kt
Labels: Pending Merge

#10962 [Kotlin Cleanup] CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
Labels: Pending Merge

#10974 refactor: remove `ArrayUtil[Test]`
  AnkiDroid/src/main/java/com/ichi2/utils/ArrayUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ArrayUtilTest.java
Labels: Pending Merge

#10975 refactor: convert ExceptionUtilTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ExceptionUtilTest.kt
Labels: Pending Merge

#10977 refactor: convert FileUtilTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt
Labels: Pending Merge

#10978 Implement `Add note` gesture
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/MappableBindingTest.kt
Labels: Pending Merge

#10979 refactor: convert FragmentFactoryUtilsTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/FragmentFactoryUtilsTest.kt
Labels: Pending Merge

#10992 chore(lint): fix lint compile warning re: missing Vendor
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
Labels: Dev

#10995 fix: forward-port to non-deprecated gradle properties
  AnkiDroid/jacoco.gradle
  api/build.gradle
Labels: Needs Second Approval, Dev, CI, Lint

#10993 fix: forward-port to non-deprecated APIs in DuplicateCrowdInStrings rule
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java
Labels: Pending Merge, Dev, Lint

#11016 [Kotlin Migration] Compat
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge

#11018 Move code related to LeakCanary outside of AnkiDroidApp
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/LeakCanaryConfiguration.kt
Labels: Pending Merge

#11025 refactor(ci): use built-in concurrency features
  .github/workflows/lint.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Dev, CI

#10983 refactor: Convert CollectionTask to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.kt
Labels: Needs Review

#10991 build(deps): kotlin stdlib deps are implicit now
  AnkiDroid/build.gradle
  lint-rules/build.gradle
Labels: Pending Merge, Dev, dependencies

#11031 refactor: prepare CollectionUtils for removal
  AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
Labels: Needs Review

#10994 fix: nonPositionalFormatSubstitution rule should use same param name as super
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
Labels: Pending Merge, Dev, CI

#11000 Migrate CollectionUtilsTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
Labels: Pending Merge

#10779 Add a tools/migrate.sh file for Kotlin migration
  tools/migrate.sh
Labels: Needs Second Approval

#11001 Migrate ContentResolverUtilTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
Labels: Pending Merge

#11002 Migrate DeckNameComparatorTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/DeckNameComparatorTest.kt
Labels: Pending Merge

#11037 feat: Allow Kotlin Migration on lint-rules
  lint-rules/build.gradle
  lint-rules/kotlinMigration-lint.gradle
Labels: Pending Merge, squash-merge

#11009 Migrate MaxExecFunctionTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
Labels: Pending Merge

#11010 [Kotlin Migration] LanguageUtilsTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt
Labels: Pending Merge

#11011 [Kotlin Migration] ReviewerNoParamTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Pending Merge

#11027 [Kotlin Migration] BeolingusParserTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
Labels: Pending Merge

#11028 [Kotlin migration] AudioPlayerTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.kt
Labels: Pending Merge

#11052 refactor: Convert DuplicateCrowdInStrings to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/KotlinCleanup.kt
Labels: Pending Merge
