Repository ankidroid/Anki-Android, pull requests merged in 2022-11, with the labels that each got.

#12725 [Kotlin CleanUp ] CardTemplatePreviewerTest.kt,DeckPickerCheckDataBaseListener.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
Labels: Pending Merge

#12782 build(deps): new coordinates for image cropper / bump to 4.5.0
  AnkiDroid/build.gradle
Labels: Pending Merge

#12783 Dependency updates 20221105
  AnkiDroid/build.gradle
Labels: Pending Merge

#12791 fix "yes" and "no" actions in Empty Cards alert dialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#12795 NF: IDE lint in ImportTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
Labels: Pending Merge

#12797 NF: remove extra `if` block in TypeAnswerTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
Labels: Needs Second Approval

#12789 Capitalize the first letter of ”yes” of alert dialog button
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Needs Second Approval, Strings, squash-merge

#12786 Remove "SD cards" from strings Fix #12777
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/04-network.xml
  AnkiDroid/src/main/res/values/09-backup.xml
Labels: Pending Merge, Strings, squash-merge

#12329 Fix Title to recall what gesture the window is for
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Labels: Needs Second Approval, squash-merge

#12623 [Kotlin CleanUp] AbstractFlashcardViewerCommandTest
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
Labels: Needs Second Approval

#12735 kotlin code cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
Labels: Needs Second Approval, squash-merge

#12801 Used val instead of var
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
Labels: Needs Second Approval

#12802 [KotlinCleanup] Utils
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
Labels: Needs Second Approval

#12811 scope function
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
Labels: Needs Second Approval, squash-merge

#12817 Dependency updates 20221111
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#12816 CropException fix
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
Labels: Waiting For Feedback, Needs Second Approval

#12823 kotlin cleanup scope function
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
Labels: Needs Second Approval

#12798 Unbury without loop
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
Labels: Pending Merge

#12830 scope function on sched.kt kotlincleanup
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
Labels: Needs Second Approval, squash-merge

#12828 Rearrange string and move to `03-dialogs.xml`
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge, squash-merge

#12840 Fix regression on marshmallow due to gradient usage
  AnkiDroid/src/main/res/drawable/horizontal_gradient_separator.xml
  AnkiDroid/src/main/res/layout/introduction_layout.xml
  AnkiDroid/src/main/res/values/colors.xml
Labels: Needs Review

#12845 Fix menu item crash when Reschedule set to appear in toolbar
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Review

#12841 Fix missing sync menu item badge in marshmallow
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
Labels: Needs Second Approval

#12781 Migrate the DeleteField task to coroutine
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Needs Review, Needs Second Approval, squash-merge

#12849 Changed String.format to String template
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/IntentAssert.kt
Labels: Needs Second Approval, squash-merge

#12831 Used val instead of var
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
Labels: Needs Second Approval, squash-merge

#12771 Migrate the LoadDeckCounts task to coroutine
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Labels: Needs Second Approval, squash-merge

#12794 KotlinCleanup: convert to Parcelize in FieldEditText
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Needs Second Approval, squash-merge

#12848 Used """ instead of " to avoid \"
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
Labels: Needs Second Approval

#12836 kotlin cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Labels: Needs Author Reply, Needs Second Approval, squash-merge

#12867 Fix crash when editing note and adding audio
  AnkiDroid/src/main/java/com/ichi2/ui/FixedTextView.kt
Labels: Needs Second Approval

#12868 [KotlinCleanup] FileUtil
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
Labels: Needs Second Approval, squash-merge

#12838 kotlin code cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
Labels: Needs Second Approval, squash-merge

#12871 Changed String.format to String template
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
Labels: Needs Author Reply

#12869 [KotlinCleanup] TreeNode
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
Labels: Needs Second Approval

#12875 crash fix due to null pointer exception
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
Labels: Needs Author Reply

#12879 Changed var to val
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.kt
Labels: Needs Second Approval

#12884 Changed var to val
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
Labels: Needs Author Reply

#12787 Migrate the RepositionField task to coroutine
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Needs Second Approval, squash-merge

#12852 Make undo button work in StudyOptions
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
Labels: Needs Second Approval, squash-merge

#12854 Use "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge, squash-merge

#12892 Fix Deck Options with new backend
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
Labels: Needs Second Approval

#12891 [KotlinCleanUp] ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
Labels: Needs Second Approval

#12877 Used """ instead of " to avoid \"
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
Labels: Needs Second Approval, squash-merge

#12895 Fix prettier throwing errors
  pre-commit
Labels: Needs Second Approval
