Repository ankidroid/Anki-Android, pull requests merged in 2022-01, with the labels that each got.

#10040 Updated strings from Crowdin 20211231
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-hu/01-core.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/04-network.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-uz/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Labels: Pending Merge

#10036 [Kotlin Migration] Themes
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Needs Second Approval

#10037 [Kotlin Migration] media registration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
Labels: Needs Second Approval

#10038 [Kotlin Migration] deck spinner selection
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
Labels: Needs Second Approval

#10041 [Kotlin Migration] DeckPickerFloatingActionMenu
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Waiting For Feedback, Needs Second Approval

#10042 [Kotlin Migration] IncrementerNumberRangePreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.kt
Labels: Needs Second Approval

#10039 fix: persist seek bar value on change
  AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.java
  AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java
Labels: Needs Second Approval

#10025 Added Unit Test to verify audioFocusRequest is NonNull argument
  AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
Labels: Waiting For Feedback, Needs Second Approval

#10043 [Kotlin Migration] Htmlcolors
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
Labels: Waiting For Feedback, Needs Second Approval

#10044 [Kotlin Migration] Videoplayer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
Labels: Needs Second Approval

#10051 [Kotlin Migration] NoteFieldDecorator
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
Labels: Needs Second Approval

#10032 Add LeakCanary
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/res/values/leakcanary.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.java
Labels: Pending Merge

#10054 [Kotlin Migration] StringUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
Labels: Needs Second Approval

#10055 [Kotlin Migration] TagsUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.kt
Labels: Needs Second Approval

#10058 [Kotlin Migration] TagsArrayAdapter
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
Labels: Needs Second Approval

#10062 [Kotlin Migration] HelpDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Labels: Needs Second Approval

#10063 [Kotlin Migration] RescheduleDialog
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.kt
Labels: Needs Second Approval

#10064 [Kotlin Migration] CreateCustomStudySessionListener
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
Labels: Needs Second Approval

#10065 [Kotlin Migration] CustomStudyDialogFactory
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialogFactory.kt
Labels: Needs Second Approval

#10067 [Kotlin Migration] CustomToolbarButton
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
Labels: Needs Second Approval

#10068 [Kotlin Migration] Toolbar
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Needs Second Approval

#10071 Dependency updates 20220102
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#9971 feat: improve asset helper mime type detect
  AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.java
  AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
  AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.java
Labels: Needs Second Approval

#10103 fix: Login crashing
  AnkiDroid/src/main/java/com/ichi2/anki/web/PreferenceBackedHostNum.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HostNum.java
  AnkiDroid/src/test/java/com/ichi2/anki/web/HostNumFactoryTest.kt
Labels: Review High Priority

#10110 fix(widget): maybe fix displaying crash dialog
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
Labels: Review High Priority

#10056 [Kotlin Migration] SyncStatus
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Labels: Needs Second Approval

#10061 [Kotlin Migration] DialogHandler
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
Labels: Needs Second Approval

#10073 [Kotlin Migration] AnkiStatsTaskHandler
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
Labels: Needs Second Approval

#10074 [Kotlin Migration] ChartBuilder
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Labels: Needs Second Approval

#10075 [Kotlin Migration] OverviewStatsBuilder
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
Labels: Needs Second Approval

#10077 [Kotlin Migration] HttpFetcher
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
Labels: Needs Second Approval

#10078 [Kotlin Migration] DeckDropDownAdapter
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
Labels: Needs Second Approval

#10080 [Kotlin Migration] CardUtils
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt
Labels: Needs Second Approval

#10083 [Kotlin Migration] Lookup
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Lookup.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
Labels: Needs Second Approval

#10085 [Kotlin Migration] StepsPreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
Labels: Needs Second Approval

#10086 [Kotlin Migration] TimePreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.kt
Labels: Needs Second Approval

#10087 [Kotlin Migration] StudyOptionsActivity
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
Labels: Needs Second Approval

#10088 [Kotlin Migration] StudyOptionsFragment
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Needs Second Approval

#10089 [Kotlin Migration] AnimationUtil
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/AnimationUtil.kt
Labels: Needs Second Approval

#10090 [Kotlin Migration] TvNavigationElement
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/TvNavigationElement.kt
Labels: Needs Second Approval

#10105 [Kotlin Migration] ImportUtils
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Needs Second Approval

#10106 [Kotlin Migration] NumberRangePreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
Labels: Needs Second Approval

#10109 [Kotlin Migration] AudioField
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioClipField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt
Labels: Needs Second Approval

#10114 [Kotlin Migration] MultimediaEditableNote
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
Labels: Needs Second Approval

#10116 [Kotlin Migration] BaseAsyncTask
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.kt
Labels: Needs Second Approval

#10115 [Kotlin Migration] GestureMapper
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.kt
Labels: Needs Second Approval

#10124 fix: param named views, optional, and send collection to newInstance optionally
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Labels: Review High Priority

#10151 [Kotlin Migration] RemoteServer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.kt
Labels: Needs Second Approval

#10174 Ensure that both Drawable kt are compatible
  AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt
  AnkiDroid/src/main/java/com/wildplot/android/rendering/interfaces/Drawable.kt
Labels: Priority-High, Waiting For Feedback, Pending Merge

#10177 fix: DeckOptions crash
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
Labels: Pending Merge, Blocked by dependency

#10229 test(connected): ignore flaky test completely
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
Labels: Needs Review, Dev

#10167 NF: Add more details to Kotlin Migration
  docs/kotlin-migration.md
Labels: Pending Merge

#10234 NF: change constant name for consistency with anki
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java
Labels: Pending Merge

#10171 NF: path is always non null
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.java
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.java
Labels: Pending Merge

#10166 NF: withChildren takes `@NonNull`
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
Labels: Pending Merge

#10140 [Kotlin Migration] AddNoteWidget
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
Labels: Pending Merge

#10187 [Kotlin Migration] ColorWrap
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/ColorWrap.kt
Labels: Pending Merge

#10190 [Kotlin Migration] PieChart
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.kt
Labels: Pending Merge

#10200 [Kotlin Migration] UnifiedTrustManager
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/UnifiedTrustManager.kt
Labels: Pending Merge

#10214 [Kotlin Migration] FragmentTestActivity
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/FragmentTestActivity.kt
Labels: Pending Merge

#10237 String feedback_manual_toast_text and the reference to it has been updated
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/res/values/05-feedback.xml
Labels: Pending Merge

#10249 [Kotlin Migration] CollectionLoader
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
Labels: Needs Second Approval

#10280 fix: nullability of Preference classes
  AnkiDroid/src/main/java/com/ichi2/preferences/ConfirmationPreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ResetLanguageDialogPreference.kt
Labels: Pending Merge
