Repository ankidroid/Anki-Android, pull requests merged in 2022-10, with the labels that each got.

#12547 [GSoC] Removed unused class UpdateValuesFromDeck
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12546 [GSoC] Migrated ConfRemove to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12555 Replace usages of String.format in with string templating
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
Labels: Pending Merge

#12541 [GSoC] Migrated CountModels to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/test/java/com/ichi2/async/CountModelsTest.kt
Labels: Review High Priority, Pending Merge, Needs Second Approval

#12551 [GSoC] Migrated EmptyCram to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge

#12558 converted some lines to lambda function and simplified the code
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
Labels: Needs Second Approval

#12572 NF: Cleanup AnkiDroidApp
  .idea/dictionaries/android.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
Labels: Pending Merge

#12575 NF: correct Compat documentation
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
Labels: Pending Merge

#12549 NF: replace requireNonNull by !!
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/RecursivePictureMenuUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/FileOperation.kt
Labels: Waiting For Feedback, Pending Merge

#12573 NF: simplify getting current language
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Labels: Pending Merge

#12570 [KotlinCleanup] Made card arg in onCardEdited not null.
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge, hacktoberfest-accepted

#12569 [KotlinCleanup] ModelBrowser
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
Labels: Pending Merge, hacktoberfest-accepted, squash-merge

#12560 NF: check media is a triple
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendMedia.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
Labels: Pending Merge

#12556 [GSoC] Migrated CheckCardSelection to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Pending Merge, squash-merge

#12543 Comment compat
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
Labels: Waiting For Feedback, Needs Second Approval, squash-merge

#12591 [GSoC] Migrated CollectionTask.Reorder to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12604 Dependency updates 20221008
  AnkiDroid/build.gradle
Labels: Pending Merge

#12592 [GSoC] Coroutines migration ConfSetSubdecks
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge

#12571 [GSoC] Coroutines migration RenderBrowserQA
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
Labels: Review High Priority, Pending Merge, squash-merge

#12593 Cleanup: Refactor Finder.kt and define `preds` as a `val` instead of `var`
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12577 [GSoC] Coroutines migration DeleteNoteMulti
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval, squash-merge

#12584 [GSoC] Coroutines migration RebuildCram
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval, squash-merge

#12619 [KotlinCleanup] DeckOptions
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12585 [GSoC] Coroutines migration SuspendCardMulti
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge, squash-merge

#12616 Kotlin CleanUp of ImportTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
Labels: Needs Second Approval, hacktoberfest-accepted

#12624 Cleanup: Refactor `LintUtils.isAnAllowedClass` to not use `var`
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/LintUtils.kt
Labels: hacktoberfest-accepted

#12629 Fix: getAllModelsAndNotesCount is now cancelled co-operatively
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/test/java/com/ichi2/async/CountModelsTest.kt
Labels: Pending Merge

#12633 Kotlin Cleanup: Simplify sync in deck picker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Pending Merge

#12639 fix: 'RescheduleDialog' memory leak
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.kt
Labels: Needs Review

#12641 Updated strings from Crowdin 20221013
  AnkiDroid/src/main/res/values-bn/01-core.xml
  AnkiDroid/src/main/res/values-bn/02-strings.xml
  AnkiDroid/src/main/res/values-bn/10-preferences.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/06-statistics.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-sv/01-core.xml
  AnkiDroid/src/main/res/values-sv/02-strings.xml
  docs/marketing/localized_description/marketdescription-ja.txt
Labels: Pending Merge

#12638 chore: remove 'welcome dialog'
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Blocked by dependency, Strings

#12566 Fix 0 bytes file output when exporting collection
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Review, Strings

#12607 Added snackbar instead of toast and format code
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
Labels: Needs Second Approval, squash-merge

#12618 Change the order of audio-related items on action menu of study screen
  AnkiDroid/src/main/res/menu/reviewer.xml
Labels: Needs Second Approval

#12643 fix(test): we need notification permission on tests that measure screen
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Needs Second Approval

#12598 NF: refactor DeckOption conf change handler
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
Labels: Pending Merge

#12646 test(perf): avoid OOM while running big batches of commit tests
  tools/test-commits.sh
Labels: Needs Review, Dev

#12642 Add the InMigration sync state
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Waiting For Feedback, Pending Merge, Strings, squash-merge

#12654 NF: add NotificationChannels enum params
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
Labels: Needs Second Approval

#12652 NF: MigrateUserData limit its use of TaskListener
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
Labels: Needs Second Approval, squash-merge

#12658 Correct `testChannelCreation`
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
Labels: Needs Second Approval

#12644 [Kotlin CleanUp] AnkiPackageExporterTest.kt and TextNoteExporterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
Labels: Needs Second Approval

#12664 Updated strings from Crowdin 20221015
  AnkiDroid/src/main/res/values-af/01-core.xml
  AnkiDroid/src/main/res/values-bn/02-strings.xml
  AnkiDroid/src/main/res/values-cs/01-core.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-it/01-core.xml
  AnkiDroid/src/main/res/values-it/02-strings.xml
  AnkiDroid/src/main/res/values-it/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-yue/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
Labels: Pending Merge

#12663 NF: FileUtil returns more information about folder content
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt
Labels: Review High Priority, Pending Merge

#12660 Task non null
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt
Labels: Pending Merge

#12677 Fix crash when user aborts file selection while exporting
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Needs Second Approval

#12680 NF: rename deck to col
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
Labels: Priority-Low, Pending Merge

#12653 Adding a scoped storage migration channel
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
Labels: Pending Merge, squash-merge

#12611 NF: uses edit with block
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/FullScreenMode.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
Labels: Needs Second Approval

#12678 NF: introduce a hasSyncAccount method
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
Labels: Priority-Low, Needs Second Approval

#12679 NF: cleanup compatV26
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
Labels: Priority-Low, Pending Merge

#12687 Make whiteboard related items grouped
  AnkiDroid/src/main/res/menu/reviewer.xml
Labels: Needs Second Approval

#12689 Updated strings from Crowdin 20221017-1
  AnkiDroid/src/main/res/values-ru/01-core.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
Labels: Pending Merge

#12625 Cleanup in [FieldEditText.kt]
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Waiting For Feedback, Needs Second Approval

#12700 Coroutine migration ChangeDeckMulti
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Needs Second Approval, squash-merge

#12649 NF: Add "postpone migration" backend util
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Review High Priority, Needs Second Approval

#12667 Kotlin Cleanup: Changed to scope function in DeckPickerTest
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Pending Merge, hacktoberfest-accepted, squash-merge

#12714 refactor: Changed ACRA toastText init to ToastType enum
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
Labels: Needs Second Approval

#12719 fix: crash showing error if activity is destroyed
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#12698 [Kotlin CleanUp] CollectionTest.kt,Shared.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
Labels: Needs Second Approval

#12691 Replaced String.format() with string template in Collection
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12717 Kotlin Cleanup in ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
Labels: Needs Second Approval, squash-merge

#12662 Correcting Hyperlink Color In About Section
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Needs Review, Needs Second Approval, squash-merge

#12626 Cleanup in [AbstractFlashcardViewer]
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge, hacktoberfest-accepted

#12627 Kotlin Cleanup [Reviewer.kt]
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge, hacktoberfest-accepted

#12621 [KotlinCleanup] NavigationDrawerActivity
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12723 [Kotlin CleanUp] TextCardExporterTest.kt,ForegroundTaskManager.kt
  AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.kt
Labels: Needs Second Approval, hacktoberfest-accepted

#12690 Replaced String.format() with string template in Anki2Importer
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12707 Coroutine migration ExportApkg
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval, squash-merge

#12740 fixes crash caused by cast exception
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
Labels: Needs Second Approval

#12745 show snackbar instead of toast
  AnkiDroid/src/main/java/com/ichi2/utils/IntentUtil.kt
Labels: hacktoberfest-accepted

#12734 Fixed a crash on images exceed 1MB
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
Labels: Pending Merge, hacktoberfest-accepted

#12695 KotlinCleanup: AbstractFlashcardViewer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge, squash-merge

#12743 Fix permission missing crash when sharing exported collection
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Needs Review

#12746 build: support JDK11 and JDK17 (the two LTSs) and JDK18
  build.gradle
Labels: Needs Second Approval

#12645 Dont sync in migration
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings, squash-merge

#12659 Kotlin cleanup, improving nullability
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Pending Merge

#12648 Introduce an upgrade icon
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/drawable/ic_migrate.xml
  AnkiDroid/src/main/res/menu/deck_picker.xml
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#12696 Fix options group not updating in deck options
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
Labels: Needs Second Approval

#12726 UI fixes and enhancements
  AnkiDroid/src/main/res/drawable/horizontal_gradient_separator.xml
  AnkiDroid/src/main/res/layout/introduction_layout.xml
  AnkiDroid/src/main/res/values/colors.xml
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#12486 Implement new backend for note types activity
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeUiModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
  AnkiDroid/src/main/res/layout/dialog_new_note_type.xml
  AnkiDroid/src/main/res/layout/item_manage_note_type.xml
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Needs Second Approval

#12666 Add `migrate` in DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#12450 Improve nullability for methods in the api module
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
  api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
Labels: API, Needs Review

#12686 Accept Manual back-up
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#12563 [KotlinCleanup] - turn set/hasTemporaryMedia into a property
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Labels: Pending Merge, hacktoberfest-accepted, squash-merge
