Repository ankidroid/Anki-Android, pull requests merged in 2022-03, with the labels that each got.

#10396 Localize backups date and add Choose another button
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.java
Labels: Waiting For Feedback, Needs Second Approval, Strings

#10414 Added `Try Anyway` button for login screen
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Labels: Pending Merge

#10407 Don't show `Full sync` option if not logged on database error dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Labels: Pending Merge

#10329 Keep image file names
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
Labels: Pending Merge

#10222 [Kotlin Migration] UtilsIntegrationTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.kt
Labels: Needs Review

#10172 NF: replace tab by spaces
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
  AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/importer/python/CsvProcessIntegrationTest.java
Labels: Pending Merge

#10219 [Kotlin Migration] FlagTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
Labels: Pending Merge

#10215 [Kotlin Migration] MultimediaEditFieldActivityTestBase
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
Labels: Pending Merge

#10418 `hasFile` throw FileNotFoundException instead of NoSuchFile
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
Labels: Pending Merge

#10398 `hasFiles` raises exception
  AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/compat/FileStream.kt
  AnkiDroid/src/test/java/com/ichi2/anki/compat/CompatHasFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
Labels: Needs Second Approval

#10426 use lazy delegate to create non-nullable ObjectMapper
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiSerialization.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
Labels: Pending Merge

#10425 [Kotlin Migration] BackupManager
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
Labels: Pending Merge

#10430 NF: add test for contentOfDirectory for file access exception
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
Labels: Pending Merge

#10444 NF: remove `val col = col`
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionPersistentTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
Labels: Pending Merge

#10437 NF: Replace `when` by whenever
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Labels: Waiting For Feedback, Needs Second Approval

#10435 Fix `setDid()` when did is null
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
Labels: Needs Second Approval

#10440 DirectoryTest for API 21 and 26
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Labels: Pending Merge

#10456 chore(kotlin): Convert Preferences.java to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Needs Review

#10461 refactor(preferences): Post-Kotlin Cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Pending Merge

#10447 Check if TTS available on device
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
Labels: Needs Second Approval

#10421 Add option to show all deck stats by default
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Strings

#10320 Image paste clipboard
  AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
Labels: Needs Second Approval

#10462 Add hint gesture/command
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Pending Merge

#10263 [Kotlin Migration] Consts
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
Labels: Needs Second Approval

#10492 Dependency updates 20220311
  AnkiDroid/build.gradle
Labels: Pending Merge

#10496 [Kotlin Cleanup] BackupManager
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceToDowngradeDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
Labels: Pending Merge

#10494 Convert WhiteboardMultiTouchMethods.java -> kt
  AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMultiTouchMethods.kt
Labels: Pending Merge

#10497 Enable LogConditional lint
  AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.java
  lint-release.xml
Labels: Pending Merge

#10519 Kotlin cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt
Labels: Pending Merge

#10522 removed redundant @KotlinCleanup from Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Pending Merge

#10514 NF: Directory.createTransientDirectory return File
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
Labels: Pending Merge

#10512 NF: factorize createPermissionDenied
  AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
Labels: Pending Merge

#10509 NF: rename folder to directory
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/Utils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDeleteFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ExportingTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/ImportingTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/MediaTest.java
  AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXml.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
Labels: Needs Second Approval

#10487 refactor(tests): Improve Performance
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Needs Second Approval

#10524 KotlinCleanup in AnkiDroidWidgetSmall.kt and Java Util methods to kotlin equivalents
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
Labels: Needs Second Approval

#10506 Enable TextFields lint
  AnkiDroid/src/main/res/layout/feedback.xml
  lint-release.xml
Labels: Waiting For Feedback

#10500 added prettier check
  .github/workflows/lint.yml
  .prettierignore
  .prettierrc
  AnkiDroid/src/main/assets/scripts/card.js
  pre-commit
Labels: Needs Second Approval

#10529 docs: Drawing Activity
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
Labels: Needs Review

#10532 fix(docs): Wrong tag value
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
Labels: Needs Review

#10498 Enabled lint check "ObsoleteLayoutParam"
  AnkiDroid/src/main/res/layout/activity_drawing.xml
  lint-release.xml
Labels: Pending Merge

#10534 KotlinCleanup File-> Storage Test changed var to val
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
Labels: Pending Merge

#10539 fix(compat): Add Nullability annotations
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
Labels: Needs Review

#10533 migration from startActivityForResult to new API in ModelBrowser.java
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
Labels: Pending Merge

#10535 startActivityForResult migration in Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Needs Second Approval

#10542 fix(prettier): Ignore 'build' folder
  .prettierignore
Labels: Review High Priority

#10559 [Kotlin Migration] Upgrade
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/upgrade/Upgrade.kt
Labels: Needs Second Approval

#10556 fix(translations): make arrays constant
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Needs Review

#10567 nf: reorder strings
  AnkiDroid/src/main/res/values/11-arrays.xml
Labels: Pending Merge

#10568 Change .prettierrc endOfLine to auto
  .prettierrc
Labels: Needs Second Approval

#10560 search_deck ambiguity resolved.
  AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, squash-merge

#10527 [Kotlin Cleanup] CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ContextMenuHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Labels: Pending Merge

#10579 refactor(CompatSoundTest): Speed up
  AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
Labels: Needs Review

#10197 [Kotlin Migration] DroidBackend
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
Labels: Needs Second Approval

#10572 [lint] enable-redundantNamespace-lint
  AnkiDroid/src/main/res/layout/model_browser.xml
  AnkiDroid/src/main/res/layout/model_field_editor.xml
  AnkiDroid/src/main/res/layout/multimedia_edit_field_activity.xml
  AnkiDroid/src/main/res/layout/studyoptions.xml
  lint-release.xml
Labels: Pending Merge

#10564 Kotlin conversion preferences test
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Labels: Needs Second Approval

#10570 [lint ] enable_implictSamInstance_lint
  lint-release.xml
Labels: Needs Second Approval

#10490 Enabled UselessParent Lint
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/res/layout/card_info.xml
  AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
  lint-release.xml
Labels: Needs Second Approval, squash-merge

#10580 feat(tests): Add Mockk dependency
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
Labels: Needs Review

#10553 [Kotlin Migration] BasicAudioRecordingFieldController
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/IMultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.kt
Labels: Pending Merge

#10537 KotlinCleanup : (localeCodeStr)
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/JavaScriptTTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/LanguageUtils.kt
Labels: Pending Merge, squash-merge

#10558 Added message explanations
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerTimerTest.kt
Labels: Pending Merge, squash-merge

#10520 Follow system dark mode
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/res/drawable/ic_brightness_3_black.xml
  AnkiDroid/src/main/res/layout/night_mode_switch.xml
  AnkiDroid/src/main/res/menu/navigation_drawer.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Labels: Waiting For Feedback, Pending Merge

#10578 [Kotlin Migration] CompatHelper
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.kt
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
Labels: Needs Review

#10587 fix: Crash opening Deck Options
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Needs Second Approval

#10576 [Kotlin Cleanup] ImportUtils.kt Polish
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Needs Second Approval

#10599 Fix translation of MultimediaEditFieldActivity title
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
Labels: Pending Merge

#10536 Migrate FieldEditText to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Needs Review

#10605 Updated strings from Crowdin 20220322
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ar/11-arrays.xml
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/11-arrays.xml
  AnkiDroid/src/main/res/values-hi/01-core.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/06-statistics.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/11-arrays.xml
  AnkiDroid/src/main/res/values-ja/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ja/17-model-manager.xml
  AnkiDroid/src/main/res/values-ml/01-core.xml
  AnkiDroid/src/main/res/values-mr/01-core.xml
  AnkiDroid/src/main/res/values-or/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/11-arrays.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-ru/01-core.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  AnkiDroid/src/main/res/values-ru/11-arrays.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/04-network.xml
  AnkiDroid/src/main/res/values-uk/06-statistics.xml
  AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/11-arrays.xml
  AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/11-arrays.xml
  docs/marketing/localized_description/marketdescription-ja.txt
Labels: Pending Merge

#10526 Kotlin cleanup for CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
Labels: Waiting For Feedback

#10593 open keyboard when rescheduling a card
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Labels: Pending Merge

#10583 [Kotlin Migration] TriStateCheckBox
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
Labels: Needs Review

#10608 chore(ktlint): bump ktlint to 0.45.1 / spacing changes w/new version
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DecksBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONException.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONTokener.kt
  lint-rules/build.gradle
Labels: Pending Merge

#10609 Kotlin Migration: Threads
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/utils/Threads.kt
Labels: Pending Merge

#10607 [Kotlin Migration] FilteredDeckOptions
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
Labels: Pending Merge

#10610 Kotlin Migration: RtlCompliantActionProvider
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
Labels: Pending Merge

#10614 Kotlin Migration: Reviewer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
Labels: Pending Merge

#10612 refactor: Threads
  AnkiDroid/src/main/java/com/ichi2/utils/Threads.kt
Labels: Needs Review

#10613 Kotlin Migration: AutoSizeCheckboxPreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
Labels: Needs Review

#10611 [Kotlin Conversion] SeekBarPreference
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt
Labels: Pending Merge

#10617 [Deprecation] create wrapper deprecation api change
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Pending Merge

#10625 feat(tests): Apple Silicon Support
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  build.gradle
Labels: Pending Merge

#10624 Fix ModelBrowser Activity title
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
Labels: Pending Merge

#10629 perf(tests): Use EmptyApplication
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java
Labels: Needs Review

#10630 fix(tests): Fix tests on Apple Silicon
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Labels: Needs Review

#10631 feat(compat): createDirectories
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/test/java/com/ichi2/compat/CreateDirectoriesTest.kt
Labels: Review High Priority

#10451 [JS Addons] Extract .tgz file to provided directory with tests
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/TgzPackageExtractTest.kt
  AnkiDroid/src/test/resources/valid-ankidroid-js-addon-test-1.0.0.tgz
Labels: Review High Priority, Needs Second Approval

#10650 Enable ObsoleteSdkInt lint check
  AnkiDroid/src/main/res/drawable-v21/item_background_light_selectable_borderless.xml
  AnkiDroid/src/main/res/drawable-v21/shadow_left.xml
  AnkiDroid/src/main/res/drawable/fab_label_background.xml
  AnkiDroid/src/main/res/drawable/fab_label_background_black.xml
  AnkiDroid/src/main/res/drawable/fab_label_background_pre21.xml
  AnkiDroid/src/main/res/drawable/footer_button_again_dark_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_again_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_all_black_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_all_plain_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_easy_dark_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_easy_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_good_dark_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_good_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_hard_dark_ripple.xml
  AnkiDroid/src/main/res/drawable/footer_button_hard_ripple.xml
  AnkiDroid/src/main/res/drawable/item_background_light_selectable_borderless.xml
  AnkiDroid/src/main/res/drawable/item_background_selected.xml
  AnkiDroid/src/main/res/drawable/item_background_selected_pre21.xml
  AnkiDroid/src/main/res/drawable/item_background_selected_pre21_black.xml
  AnkiDroid/src/main/res/drawable/item_background_selected_pre21_dark.xml
  AnkiDroid/src/main/res/drawable/shadow_left.xml
  AnkiDroid/src/main/res/values-v21/styles.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  lint-release.xml
Labels: Needs Second Approval

#10653 [Kotlin Conversion] ReviewerKeyboardInputTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
Labels: Needs Review

#10656 [kotlinCleanUp] Upgrade.kt
  AnkiDroid/src/main/java/com/ichi2/upgrade/Upgrade.kt
Labels: Needs Second Approval

#10652 Fix tests on macOS+ refactoring
  AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/TgzPackageExtractTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.java
  AnkiDroid/src/test/java/com/ichi2/testutils/ShadowStatFs.kt
Labels: Pending Merge

#10667 Strings format for size and number of files in tar archive
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#10662 fix crash opening FIlteredDeckOptions
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/annotations/NeedsTest.kt
Labels: Needs Second Approval

#10645 fix(NoteEditor): MIUI Android 12 Crash
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Labels: Waiting For Feedback, Pending Merge

#10628 added New Lint rule for Detecting invalid string formats.
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetectorTest.kt
Labels: Pending Merge, Strings
