Repository ankidroid/Anki-Android, pull requests merged in 2022-09, with the labels that each got.

#12241 refactor: Cleanup: CustomTabActivityHelperTest
  AnkiDroid/src/test/java/com/ichi2/compat/customtabs/CustomTabActivityHelperTest.kt
Labels: Pending Merge

#12262 Use snackbar on `Press back to exit`
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#12250 Made joinFields accept not null arr string in list
  api/src/main/java/com/ichi2/anki/api/Utils.kt
Labels: Pending Merge

#12215 Simplify SingleTaskManager.kt
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
Labels: Pending Merge, squash-merge

#12212 Migrate ParsedNodes to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.kt
Labels: Pending Merge

#12279 fix: build
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
Labels: Review High Priority, Needs Second Approval

#12211 refactor: Convert ApiUtilsTest to Kotlin
  api/build.gradle
  api/kotlinMigration-api.gradle
  api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
Labels: Pending Merge

#12260 Switch JDK in GitHub Actions from adopt to temurin
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Waiting For Feedback, Needs Second Approval

#12202 Migrate FunctionXAtom to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXAtom.kt
Labels: Pending Merge

#12203 Migrate FunctionXYAtom to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXYAtom.kt
Labels: Pending Merge

#12206 Migrate Factor to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/Factor.kt
Labels: Pending Merge

#12208 Migrate Term to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/Term.kt
Labels: Pending Merge

#12271 Migrate Expression to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/Expression.kt
Labels: Pending Merge

#12218 NF: Kotlin Cleanup
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
Labels: Pending Merge, Needs Second Approval, squash-merge

#12220 NF: KotlinCleanup
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/ui/RtlCompliantActionProviderTest.kt
Labels: Pending Merge, squash-merge

#12221 refactor: KotlinCleanup - HostNum
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/web/PreferenceBackedHostNum.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HostNum.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/web/HostNumFactoryTest.kt
Labels: Pending Merge

#12232 Migrate FlashCardsContract to kotlin
  api/kotlinMigration-api.gradle
  api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
Labels: Pending Merge

#12237 refactor: Kotlin Cleanup - TTSParser
  AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
Labels: Pending Merge

#12240 refactor: Convert SchedV2 to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
Labels: Pending Merge

#12270 Migrate BarGraph to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
  AnkiDroid/src/main/java/com/wildplot/android/rendering/BarGraph.kt
Labels: Pending Merge

#12287 Updated strings from Crowdin 20220902
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-et/08-widget.xml
  AnkiDroid/src/main/res/values-et/09-backup.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/11-arrays.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Labels: Pending Merge

#12204 Migrate TopLevelParser to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXAtom.kt
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXYAtom.kt
  AnkiDroid/src/main/java/com/wildplot/android/parsing/TopLevelParser.kt
Labels: Pending Merge

#11553 NF: async task result is not necessarily nullable
  AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Labels: Pending Merge

#12216 refactor: Convert CollectionHelper to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/receiver/SdCardReceiver.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflictTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/CollectionDBCorruption.kt
Labels: Pending Merge

#12297 [GSOC] Convert `FlagsAdapter` to Inner Class
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
Labels: Review High Priority, Pending Merge

#12299 Dependency Updates 20220903
  AnkiDroid/build.gradle
Labels: Pending Merge

#12296 Removed "Created deck" toast after tapping OK on filtered deck dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
Labels: Pending Merge, squash-merge

#12300 Migrate ParsedNode to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.kt
Labels: Pending Merge

#12313 fix(docs): fix link to remove ktlint override
  build.gradle
Labels: Needs Review

#12314 [GSoC] moved doInBackgroundUpdateMultipleNotes to CollectionOperations
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge

#12301 refactor: Convert Sched to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
  AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt
Labels: Needs Second Approval

#12306 Add non nullability on selected tags class
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
Labels: Pending Merge, squash-merge

#12293 NF: move Preferences.kt and tests to `com.ichi2.anki.preferences` package
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesSimpleTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.kt
Labels: Pending Merge, squash-merge

#12309 refactor!: Convert AddContentApi to Kotlin
  api/kotlinMigration-api.gradle
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Pending Merge

#12035 [GSoC] Add ability to browse one Card per Note in Browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
  AnkiDroid/src/main/res/layout/browser_options_dialog.xml
  AnkiDroid/src/main/res/menu/card_browser.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/06-statistics.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Review High Priority, Pending Merge, Strings, squash-merge

#12318 Fix nullable type bug with NoteEditor menu item
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#11391 Fix some of the issues with CardContentProvider
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
Labels: Pending Merge

#12207 Solved backendUndoAndShowPopup() snackbar on top of answer button
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
Labels: Needs Second Approval, squash-merge

#12321 Fix dialog getting skipped on pressing back
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
Labels: Pending Merge

#11366 Fixed AudioPlayer giving IllegalStateException on stop
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
Labels: Pending Merge

#12332 fix: CI
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
Labels: Pending Merge

#12145 [GSoC] Make Filters persistent in Filter Sheet
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml
Labels: Pending Merge, squash-merge

#12331 ci: mark Stale issues as 'not_planned'
  .github/workflows/stale.yml
Labels: Needs Review

#11914 [Kotlin Cleanup] NoteEditor nullability cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#12336 Replace the title of the note-adding screen ("Add note") with "Add"
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, squash-merge

#12328 [GSoC] Migrated LoadDeck to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge, squash-merge

#12338 docs: add NeedsTest for onCreateDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
Labels: Needs Second Approval

#11418 Factorize deck pref
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Pending Merge

#12361 [GSoC] Migrated LoadCollectionComplete to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12272 [GSoC] Migrated CollectionTask.UpdateMultipleNotes to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12348 fix: Replace the name of note-adding shortcut ("Add note") with "Add"
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Pending Merge

#12352 Adding kotlin-test-junit to androidTestImplementation
  AnkiDroid/build.gradle
Labels: Pending Merge

#12354 NF: apply ide suggestion on ContentProviderTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
Labels: Pending Merge

#12374 [GSoC] Replaced usage of catchingLifecycleScope with launchCatchingTask
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
Labels: Review High Priority, Pending Merge

#12373 [GSoC] Coroutines migration DeleteMedia
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Review, Needs Second Approval, squash-merge

#12365 [GSoC] Coroutines migration CollectionTask.DeleteModel
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, squash-merge

#12380 Re-throw CancellationException in runCatchingTask
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Needs Second Approval

#12372 Fix languages order in set TTS language dialog
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Labels: Pending Merge

#12376 Kotlin Cleanup: scoped functions
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
Labels: Pending Merge, squash-merge

#12383 NF: depends of junit5
  AnkiDroid/build.gradle
Labels: Pending Merge

#12393 Dependency updates 20220913
  AnkiDroid/build.gradle
Labels: Pending Merge, squash-merge

#12392 Delete dialog icon from help/support/import dialogs
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
  AnkiDroid/src/main/res/drawable/ic_menu_back_black_24dp.xml
Labels: Pending Merge

#12386 NF: cleanup tagsList lateinit
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt
Labels: Needs Second Approval

#11727 docs: improve docs for Apple Silicon dylib load
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Labels: Pending Merge, Needs Second Approval, Dev

#12401 Set Basic2Model as internal to follow original visibility
  api/src/main/java/com/ichi2/anki/api/Basic2Model.kt
Labels: Needs Second Approval

#12389 Rename the string of "This deck is empty" snackbar action
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Needs Second Approval

#12391 [GSoC] Coroutines migration CollectionTask.DeleteDeck
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval, squash-merge

#12411 Kotlin Cleanup for Deck Picker Test
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Needs Second Approval, squash-merge

#12410 added CompatV33
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval

#12405 Cleanup IDE issues for AddContentApi
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Needs Second Approval

#12399 [GSoC] Show total lapses of note of card in notes mode (follow up to #12035)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
Labels: Needs Second Approval

#12400 [GSoC] Show total reviews in note mode (follow up to #12035)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
Labels: Needs Second Approval

#12418 fix(ci): lint was failing
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
Labels: Review High Priority, Pending Merge

#12421 [GSoC] Coroutines migration ChangeSortField
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval, squash-merge

#12396 [GSoC] Show Avg Interval in Notes Mode (follow up to #12035)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Labels: Pending Merge

#12398 [GSoC] Show date of last changed card of given note in notes mode (follow up to #12035)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#12397 [GSoC] Show number of cards in Notes Mode (follow up to #12035)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#12427 Dependency updates 20220917
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge

#12403 Cleanup NoteInfo for api release
  api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
Labels: API, Needs Second Approval

#12417 Kotlin Cleanup in [LrnCard]
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
Labels: Needs Second Approval

#12416 Kotlin Cleanup [Activity List]
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Needs Second Approval

#12423 Enable again sending error reports from launchCatchingTask
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Needs Second Approval

#12422 Compat33 parcelable fix
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval, squash-merge

#12330 [GSoC] Coroutines migration CollectionTask.SaveCollection
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#12415 More cleanups for AddContentApi
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Needs Second Approval

#12429 Localised the string "clear"
  AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml
Labels: Needs Second Approval, squash-merge

#12334 Cleanup FlashCardContract for new api release
  api/build.gradle
  api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: API, Pending Merge

#12387 NF: Cleanup of SeekBarPreferenceCompat
  AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
Labels: Needs Second Approval, squash-merge

#11745 Fix System Default Language bug
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Labels: Pending Merge, squash-merge

#12431 Remove config for JavaCompile in gradle
  build.gradle
Labels: Needs Second Approval

#12283 Use upstream's new filtered deck name pattern
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
Labels: Pending Merge, squash-merge

#12436 Updated strings from Crowdin 20220918-2
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ka/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/04-network.xml
  AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/08-widget.xml
  AnkiDroid/src/main/res/values-ka/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/17-model-manager.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
Labels: Pending Merge

#11789 Fixed `ExportCompleteDialog`'s neutral buttons deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
Labels: Pending Merge, Needs Second Approval, Strings, squash-merge

#12447 OpenCollective automation documentation / fail-fastness
  .github/workflows/opencollective_notices.yml
Labels: Needs Review, Dev

#12469 [KotlinCleanup] use kotlin.test.* for asserting
  AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
  api/src/main/java/com/ichi2/anki/api/Utils.kt
  api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
Labels: Needs Second Approval

#12454 Migrated CollectionTask. ConfReset to Kotlin Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Review High Priority, Pending Merge, squash-merge

#12485 Kotlin Cleanup [EaseButton.kt]
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
Labels: Needs Second Approval

#12492 snackbar for leech
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
Labels: Needs Second Approval

#12493 Fix legacy importer
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
Labels: Pending Merge

#12502 Don't fail tests GH actions if codecov fails
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Pending Merge

#12497 Removed unused class SearchNotes
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Needs Second Approval

#12499 Replace String? = null by `String = ""`
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#11812 Added regression test for DeckPickerContextMenu
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Labels: Waiting For Feedback, Pending Merge, squash-merge

#12509 remove addAll
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
Labels: Needs Second Approval

#12491 Removed pin option from edit note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#12507 [Refactor] Replaced null checks with safe calls.
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
Labels: Needs Second Approval

#12515 Kotlin Cleanup [FinderTest.kt]
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
Labels: Pending Merge, squash-merge

#12514 [Refactor] NoteService
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
Labels: Pending Merge, squash-merge

#12516 Kotlin Cleanup [DeckPickerTest.kt]
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Waiting For Feedback

#12508 cleanup: inControlBlocked to property
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Pending Merge, squash-merge

#12533 Dependency updates 20220929
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge

#12523 Moved UndoAction helper classes to UndoAction.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/UndoActions.kt
Labels: Review High Priority, Pending Merge

#12498 [GSoC] Migrated RepairCollection to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt
Labels: Review High Priority, Needs Second Approval

#12517 refactor toolbar in NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, squash-merge

#12467 NF: uses listOf instead of asList
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
  AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
Labels: Waiting For Feedback, Pending Merge

#12513 Kotlin Cleanup [UndoTest.kt]
  AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
Labels: Needs Second Approval

#12522 Coroutines migration UpdateValuesFromDeck
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge
