Repository ankidroid/Anki-Android, pull requests merged in 2022-05, with the labels that each got.

#11190 [Kotlin Cleanup] RustTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/RustTest.kt
Labels: Needs Second Approval

#11197 Fix translation of `SharedDecksActivity`'s title
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Labels: Pending Merge

#11202 Use JUnit5 on tests
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardAppearanceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertKt.kt
  AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
  api/build.gradle
  build.gradle
  lint-rules/build.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
Labels: Review High Priority, Pending Merge

#11165 Category heading on the toolbar of settings section
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, squash-merge

#11200 refactor: CardBrowser - IDE Lint
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#11209 NF: Use same param names on NavigationDrawerActivity inheritors
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
Labels: Pending Merge

#11214 Kotlin Migration TemplateTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.kt
Labels: Pending Merge

#11216 [Kotlin Migration] PieChartParameterizedTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
Labels: Pending Merge

#11246 Update the material library dependency to 1.6.0
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Labels: Waiting For Feedback

#10906 DeckOverview screen Overflow menu icon changed #10868 error solved
  AnkiDroid/src/main/res/menu/study_options_fragment.xml
Labels: Needs Second Approval, squash-merge

#10941 Add the 'Always Show' and 'Show if room' to "Set TTS language"
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Needs Second Approval, squash-merge

#11158 refactor: convert DuplicateTextInPreferencesXml to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXml.kt
Labels: Pending Merge

#11242 Removed metadata elements from AndroidManifest.xml
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Needs Second Approval

#11184 [Kotlin Cleanup] GestureProcessorTest
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
Labels: Pending Merge

#11188 Add 'Any' constraint for 'CTX'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt
Labels: Pending Merge, squash-merge

#11199 Implement the long-click feature.
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Labels: Pending Merge, squash-merge

#11223 Migrate TemplateError to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateError.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java
Labels: Pending Merge

#11205 refactor: Convert MetaDB to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ResetLanguageDialogPreference.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.kt
Labels: Pending Merge

#11204 refactor: Convert Previewer to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
Labels: Pending Merge

#11212 [Kotlin Migration] PieChartTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt
Labels: Pending Merge

#11193 [Kotlin Cleanup] CopyrightHeaderExists
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.kt
Labels: Needs Second Approval

#11225 [Kotlin Cleanup] DirectCalendarInstanceUsage
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectCalendarInstanceUsage.kt
Labels: Waiting For Feedback, Needs Second Approval

#11263 [Kotlin Cleanup] PeripheralKeymapTest
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Waiting For Feedback

#11191 [Kotlin Cleanup] DirectGregorianInstantiation
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
Labels: Waiting For Feedback

#11258 [Kotlin Cleanup] ReviewerNoParamTest
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Waiting For Feedback

#11224 Migrate MathJax to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/template/MathJax.kt
Labels: Pending Merge

#11241 [Kotlin Migration ] PreferenceExtensionsTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
Labels: Pending Merge

#11262 [Kotlin Cleanup] ReadTextTest
  AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.kt
Labels: Waiting For Feedback, Pending Merge, squash-merge

#11203 refactor: Convert NoteEditor to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
Labels: Pending Merge

#11164 kotlin cleanup : CheckBoxTriState.kt
  AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
Labels: Pending Merge, squash-merge

#11208 Migrate TemporaryModel to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
Labels: Pending Merge

#11270 kotlinMigration for api project.
  api/build.gradle
  api/kotlinMigration-api.gradle
Labels: Needs Second Approval

#11233 Update general category title
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
Labels: Needs Second Approval

#11249 Kotlin Migration SchedUpgradeTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.kt
Labels: Pending Merge

#11252 [Kotlin migration] ParserTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
Labels: Pending Merge

#11274 [Kotlin Migration] DeckOptions
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
Labels: Pending Merge

#11279 Migrate CsvSniffer to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvSniffer.kt
Labels: Pending Merge

#11271 Migrate CsvReaderIterator to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReader.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/importer/python/CsvProcessIntegrationTest.kt
Labels: Waiting For Feedback, Pending Merge

#11290 Fix crash if no video or audio is selected on NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/MediaClipTest.kt
Labels: Pending Merge

#11285 [KotlinCleanup] Previewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
Labels: Pending Merge

#11276 [Kotlin Migration] CardTemplateEditor
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
Labels: Pending Merge

#10863 Truncate Option in Card Browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/res/menu/card_browser.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval

#11300 Added test message explanations
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
Labels: Pending Merge

#11061 Fix Overflow Icon Color Change on Config Change (Orientation Change)
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Review

#11293 [Kotlin Migration ] TokenizerTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
Labels: Pending Merge

#11306 test(ci): add tight timeout to gradle setup step
  .github/workflows/lint.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Needs Review

#11173 refactor: Convert MultimediaEditFieldActivity to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
Labels: Review High Priority, Needs Review

#11118 [KotlinCleanup] TranslationActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
Labels: Pending Merge

#11155 refactor: convert DirectSnackbarMakeUsage to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsage.kt
Labels: Pending Merge

#11156 refactor: convert DirectSystemCurrentTimeMillisUsage to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsage.kt
Labels: Pending Merge

#11157 refactor: convert DirectToastMakeTextUsage to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.kt
Labels: Pending Merge

#11159 refactor: convert FixedPreferencesTitleLength to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
Labels: Pending Merge

#11161 refactor: convert InconsistentAnnotationUsage to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.kt
Labels: Pending Merge

#11162 refactor: convert NonPublicNonStaticJavaFieldDetector to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticJavaFieldDetector.kt
Labels: Pending Merge

#11163 refactor: convert PreferIsEmptyOverSizeCheck to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheck.kt
Labels: Pending Merge

#11170 refactor: convert PrintStackTraceUsage to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/PrintStackTraceUsage.kt
Labels: Pending Merge

#11171 refactor: convert IssueRegistry to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
Labels: Pending Merge

#11294 Refactor ArgumentUtils into BundleUtils
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ArgumentUtilsTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsRobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
Labels: Pending Merge

#11310 Dependency updates 20220510
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge

#11312 Fix `supportInvalidateOptionsMenu` deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#11315 refactor: Convert ImportStatementDetector to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/ImportStatementDetector.kt
Labels: Pending Merge

#11316 refactor: Convert LintUtils to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/LintUtils.kt
Labels: Pending Merge

#11313 refactor: Convert JavaFieldNamingPatternDetector to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantJavaFieldDetector.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/JavaFieldNamingPatternDetector.kt
Labels: Pending Merge

#11314 refactor: Convert Constants to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.kt
Labels: Pending Merge

#11237 Migrate RemoteMediaServer to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
Labels: Pending Merge

#11318 refactor: Convert DirectSystemTimeInstantiation to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemTimeInstantiation.kt
Labels: Pending Merge

#11194 Remove the ability to translate from application
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Meaning.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Phrase.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Response.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Tuc.java
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/language/LanguagesListerGlosbe.kt
  AnkiDroid/src/main/res/layout/activity_translation.xml
  AnkiDroid/src/main/res/menu/activity_translation.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
Labels: Pending Merge

#11303 Allow only single imports on the .colpkg option.
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Labels: Pending Merge, squash-merge

#11296 [Kotlin Cleanup] Various
  AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
Labels: Pending Merge

#11166 [Kotlin Cleanup] ListUtil
  AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.kt
Labels: Pending Merge

#11287 [KotlinCleanup] AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Waiting For Feedback, Needs Second Approval

#11320 docs: Rationale for `@NeedsTest`
  AnkiDroid/src/main/java/com/ichi2/annotations/NeedsTest.kt
Labels: Needs Second Approval

#11323 Remove useless abstraction for IControllerFactory
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicControllerFactory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IControllerFactory.kt
Labels: Pending Merge

#11331 Ignore image and audio paths check for text based fields
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#11344 Fix ModelBrowser leaking its ModelBrowserContextMenu reference
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
Labels: Pending Merge

#11340 Fix AutoFocus EditText Preferences Back/Return Button Bug
  AnkiDroid/src/main/java/com/ichi2/preferences/AutoFocusEditTextPreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
Labels: Needs Second Approval

#11338 [Kotlin Cleanup] ReminderServiceTest
  AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
Labels: Needs Second Approval

#11335 [Kotlin Cleanup] CollectionUtils
  AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.kt
Labels: Needs Second Approval

#11342 feat: Speed up tests on Apple Silicon and CI
  build.gradle
Labels: Needs Review

#11348 [Kotlin Cleanup] JSONArrayTest
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
Labels: Pending Merge

#11350 [Kotlin Cleanup] Various Files
  AnkiDroid/src/androidTest/java/com/ichi2/libanki/DBTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.kt
Labels: Pending Merge

#11327 added test for CountModels
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCountModelsTest.kt
Labels: Needs Second Approval

#11309 refactor: Convert Collection to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckOptionsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
Labels: Review High Priority, Needs Review

#11005 Fixed a bug about NavigateUp Button on DeckOverview screen
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Labels: Pending Merge

#11364 Migrate TextNoteExporter to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
Labels: Pending Merge

#11362 [Kotlin Migration] CopyrightHeaderExistsTest Lint TEST
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderExistsTest.kt
Labels: Pending Merge

#11354 Kotlin Migration CheckMediaTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.kt
Labels: Pending Merge

#11269 [Kotlin Migration] NoteInfo
  api/kotlinMigration-api.gradle
  api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
Labels: Pending Merge

#11371 [Kotlin Migration] Basic2model
  api/kotlinMigration-api.gradle
  api/src/main/java/com/ichi2/anki/api/Basic2Model.kt
Labels: Pending Merge

#11370 Migrate Tags.java to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
Labels: Pending Merge

#11390 Add support to `<audio>` and `<object>` tags
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Labels: Anki Ecosystem Compatibility, Pending Merge

#11384 [Kotlin migration ] ActionBarOverflowTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.kt
Labels: Pending Merge

#11375 Kotlin migration PeripheralKeymapTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Pending Merge

#11328 Include Edgecases in kotlin migration script + Touch ups
  tools/migrate.sh
Labels: Needs Review

#11447 feat: enable dom storage in webview for localStorage
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#11445 NF: info use scoped function
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Pending Merge

#11435 [Kotlin Cleanup] ParserTest
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
Labels: Pending Merge

#11452 Dependency updates 20220529
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#11424 NF: move preference to lateinit in FilteredDeckOptions
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
Labels: Waiting For Feedback, Pending Merge

#11337 [Kotlin Cleanup] ActionButtonStatusTest
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
Labels: Waiting For Feedback

#11471 [Kotlin Cleanup] Cardbrowser pt14
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#11469 [Kotlin Cleanup] Cardbrowser pt12
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#11423 NF: factorize mPrefChanged
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Waiting For Feedback, Pending Merge
