Repository ankidroid/Anki-Android, pull requests merged in 2022-07, with the labels that each got.

#11739 [GSoC] Kotlin migration TextImporter.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
Labels: Pending Merge

#11490 Replaced String.format in CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Pending Merge

#11758 Make fullscreen reviewer occupy system bars
  AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
Labels: Needs Second Approval

#11759 Remove extra whitespace in collection synchronized dialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#11762 help dialog crash dont keep activity
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
Labels: Needs Second Approval

#11752 Add Toast for "max one word" pronunciation
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Needs Second Approval

#11757 [GSoC] Kotlin migration Anki2Importer.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
Labels: Review High Priority, Needs Second Approval

#11768 fix: remove duplicate "TextFields" lint
  lint-release.xml
Labels: Needs Review

#11756 Bump fragments library dependency to 1.5.0
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  build.gradle
Labels: Needs Review

#11725 [GSoC] Remove XXX replacement on preferences summaries
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_acessibility.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
  AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.kt
Labels: Review High Priority, Pending Merge, squash-merge

#11772 Kotlin migration Importer.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
Labels: Pending Merge

#11596 Kotlin CleanUp of IMultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/IMultimediaEditableNote.kt
Labels: Waiting For Feedback, Needs Second Approval

#11463 [Kotlin Cleanup] Cardbrowser pt6
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge, Needs Second Approval

#11774 Cleanup: TagsUtilTest
  AnkiDroid/src/test/java/com/ichi2/utils/TagsUtilTest.kt
Labels: Pending Merge, Needs Second Approval

#11604 [Kotlin Migrate] JSONObject
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
  AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Waiting For Feedback, Needs Second Approval

#11783 test(ci): ignore another flaky test
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
Labels: Pending Merge

#11788 Fix context menu selection for DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
Labels: Priority-High, Needs Review

#11791 Fix code style checks failures due to @CheckResult
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Labels: Pending Merge

#11765 Migrated preferences title length test [Lint Test]kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
Labels: Needs Second Approval

#11805 Fix context menu in CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Priority-High, Needs Review

#11792 fix: ide lint in TTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
Labels: Pending Merge

#11793 cleanup in CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Pending Merge, squash-merge

#11807 Fix functionality for dialogs of NoteEditor toolbar
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Review

#11799 refactor: make `fieldEditLine` as a function in FieldEditLineTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
Labels: Needs Second Approval

#11798 cleanup: ActionBarOverflowTest
  AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.kt
Labels: Needs Second Approval

#11800 cleanup: NoteEditorTabOrderTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
Labels: Needs Second Approval, squash-merge

#11797 fix: IDE lint in UniqueArrayList
  AnkiDroid/src/main/java/com/ichi2/utils/UniqueArrayList.kt
Labels: Needs Second Approval

#11796 [Kotlin Migrate] androidtest/DeckPickerTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Needs Second Approval

#11584 [Kotlin Cleanup] Cardbrowser pt20
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#11809 Fix some of the issues with material dialogs vertical padding
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
Labels: Needs Second Approval

#11802 Convert Sched2Test to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
Labels: Review High Priority, Pending Merge, Rust

#11817 ExportDialog "ok" button disabled fix
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
Labels: Needs Second Approval

#11820 [GSoC] Kotlin Cleanup AnkiStatsTaskHandler
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Labels: Pending Merge

#11823 Add new line between GPL and AGPL
  README.md
Labels: Needs Second Approval, squash-merge

#11761 Implementation for getting data for import csv
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/BackendCsvImportV16.kt
Labels: Review High Priority, Needs Second Approval

#11815 RemoteMediaServerTest Kotlin Migration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
Labels: Needs Second Approval

#11833 Refactor PreferenceUpgradeService to use prefs.edit{} extension
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
Labels: Needs Second Approval

#11832 Revert "Enable the preferences tests which were ignored for being flaky"
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
Labels: Waiting For Feedback, Pending Merge

#11839 Fix selection in incompatible database version dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Needs Review

#11816 [GSoC] migrated CollectionLoader to Coroutines
  AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
Labels: Review High Priority, Needs Second Approval

#11814 HttpSyncerTest Kotlin Migration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
Labels: Pending Merge

#11846 [GSoC] Kotlin Migration HttpSyncer.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.kt
Labels: Needs Second Approval

#11843 [Kotlin Migration ] DeckTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
Labels: Pending Merge

#11840 remove extra comment in BeolingusParser
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
Labels: Needs Second Approval

#11729 [GSoC] Kotlin migration TaskManager.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayerAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.kt
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskSearchCardsTest.kt
  AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
Labels: Review High Priority, Pending Merge

#11489 Replaced String.format in Info
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Pending Merge

#11713 [GSoC] Filter Sheet: Add filters for flags
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/res/drawable/filter_sheet_opened_list_icon.xml
  AnkiDroid/src/main/res/drawable/filter_sheet_unopened_list_icon.xml
  AnkiDroid/src/main/res/drawable/ic_filter_list.xml
  AnkiDroid/src/main/res/drawable/ic_flag_transparent.xml
  AnkiDroid/src/main/res/drawable/label_icon_flags.xml
  AnkiDroid/src/main/res/drawable/rounded_bottom_sheet.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
  AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml
  AnkiDroid/src/main/res/layout/filter_list_flag_item_layout.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Review High Priority, Needs Second Approval, squash-merge

#11858 [GSoC] Kotlin Migration FullSyncer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.kt
Labels: Review High Priority, Needs Second Approval

#11860 NF: Remove TaskOperations
  AnkiDroid/src/main/java/com/ichi2/anki/runtimetools/TaskOperations.kt
Labels: Needs Second Approval

#11864 [GSoC] Syncer.java Kotlin Migration
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
Labels: Review High Priority, Needs Second Approval

#11857 Migrate DeckPickerTest to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Needs Review, Needs Second Approval

#11866 [GSoC] NF: Move all preferences keys to constants on preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
  AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
  AnkiDroid/src/main/res/xml/preferences_sync.xml
Labels: Review High Priority, squash-merge

#11870 Fix Flag Colors on App Bar
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/res/drawable/ic_flag_transparent.xml
Labels: Needs Second Approval

#11869 [GSoC] Fix App bar buttons screen summaries
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Pending Merge

#11867 [GSoC] Add `SearchNotes()` function
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Needs Second Approval

#11863 Add `getThemedColor` helper function
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/java/com/ichi2/themes/ThemeUtils.kt
Labels: Needs Second Approval

#11828 Add translators to the credits
  README.md
Labels: Needs Second Approval, squash-merge

#11393 [Kotlin Migration] Atom
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/Atom.kt
Labels: Needs Second Approval

#11890 NF: findOneCardByNote
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Labels: Needs Second Approval

#11892 Change return type for `setGraphPreferencesRaw` to bytetarray
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/BackendStats.kt
Labels: Needs Second Approval

#11897 fix: 'pureAnswer' works with well-formed HTML
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
Labels: Needs Review

#11824 Fix styles textColorSecondary
  AnkiDroid/src/main/res/color/prefs_item_dark_secondary.xml
  AnkiDroid/src/main/res/color/prefs_item_light_secondary.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Needs Second Approval

#11880 Fix crash during deck filtering
  .idea/dictionaries/usernames.xml
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
Labels: Pending Merge, squash-merge

#11904 fixed NPE during sync
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
Labels: Needs Second Approval

#11901 fix: IDE lint in SchedTimingToday
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
Labels: Needs Second Approval

#11903 fix: Make the database error dialog not cancelable by outside touches
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Pending Merge

#11473 [Kotlin Cleanup] Cardbrowser pt16
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Waiting For Feedback, Needs Second Approval, squash-merge

#11907 fixed automatic creation of deck with name 'All decks'
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Blocked by dependency, Strings

#11912 NF: uses "when" in filtered deck options
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
Labels: Needs Second Approval

#11859 Fix Answer Buttons Pos "None" hiding everything else
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#11941 some cleanups in Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Pending Merge, squash-merge

#11351 Fix onActivityResult deprecation for NavigationActivity
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Needs Second Approval

#11494 [Kotlin Cleanup] Cardbrowser pt19
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#11666 Kotlin Migration TimePreferenceTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.kt
Labels: Needs Second Approval

#11749 cleanup: add scope function in CardTemplateBrowserAppearanceEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
Labels: Needs Second Approval, squash-merge

#11822 Kotlin migration BackendEmulatingOpenConflictTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflictTest.kt
Labels: Needs Second Approval

#11944 Updated strings from Crowdin 20220730
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
Labels: Pending Merge

#11943 Dependency updates 20220730
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#11850 CardBrowser truncate check update on change deck
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#11906 Fix FieldEditText context menu items not working
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Needs Second Approval

#11470 [Kotlin Cleanup] Cardbrowser pt13
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval, squash-merge

#11933 [GSoC] NF: Add a comment explaining setTargetFragment deprecation suppression
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
Labels: Pending Merge

#11947 NF: make Local mSlidingTabLayout
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
Labels: Pending Merge

#11665 Kotlin migration ModelTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
Labels: Waiting For Feedback, Needs Second Approval
