Repository ankidroid/Anki-Android, pull requests merged in 2022-02, with the labels that each got.

#10296 Dependency updates 20220201
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java
  build.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheckTest.java
Labels: Pending Merge

#10231 [Kotlin Migration] CardTemplatePreviewer
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
Labels: Pending Merge

#10225 [Kotlin Migration] BasicImageFieldControllerTest
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
Labels: Needs Second Approval

#10311 Updated strings from Crowdin 20220206
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-nl/10-preferences.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/05-feedback.xml
Labels: Pending Merge

#10309 [Kotlin Migration] BadgeDrawableBuilder
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
Labels: Needs Second Approval

#10328 chore(copyright): add copyright headers to androidTest files
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/RetryRule.java
Labels: Pending Merge

#10021 Clarified Sync Error Message
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Needs Second Approval

#10338 remove: Volume Gesture Option (replaced)
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
Labels: Needs Second Approval

#10342 Fix disabled gestures still appearing
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Labels: Needs Second Approval

#10337 Update e-mail message
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval

#10348 fix(strings): missing positional arguments
  AnkiDroid/src/main/java/com/ichi2/async/Connection.java
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Pending Merge

#10354 NF: suggestion of documentation improvement
  AnkiDroid/src/main/java/com/ichi2/anki/model/DiskFile.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
Labels: Needs Second Approval

#10350 Changed SVG type and name of `replaybutton` in order to be desktop compatible
  AnkiDroid/src/main/assets/flashcard.css
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Labels: Pending Merge

#10290 Note editor toolbar new item string as icon
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
Labels: Strings

#10316 Explicitly Add Video Clips in Note Editor [issue #10212]
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
  AnkiDroid/src/main/res/drawable/ic_popup_menu_item_video.xml
  AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
Labels: Needs Second Approval

#10357 feat(scoped-storage): MoveDirectory
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
Labels: Review High Priority, Needs Second Approval

#10365 Text pasted into Note Editor is now plain text by default
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
Labels: Waiting For Feedback

#10363 feat(lint): Verify Positional Format Strings
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutionsTest.kt
Labels: Needs Second Approval

#10359 breaking(css): remove answer and question css classes
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
Labels: Pending Merge

#10380 NF: test for file/directory created during directory transfer
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
Labels: Pending Merge

#10382 NF: rename context to executionContext in DeleteEmptyDirectoryTest
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
Labels: Needs Second Approval

#10369 NF: add contentOfDirectory method
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
  AnkiDroid/src/main/java/com/ichi2/compat/FileStream.kt
  AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
Labels: Needs Second Approval

#10393 [Kotlin Migration] BadgeDrawable
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawable.kt
Labels: Needs Second Approval
