Repository ankidroid/Anki-Android, pull requests merged in 2022-06, with the labels that each got.

#11482 [Kotlin Cleanup] Cardbrowser pt17
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#11454 Update JS library (jquery & mathjax) using GitHub action
  .github/workflows/update_js_libs.yml
  tools/update-js-libs.sh
Labels: Needs Second Approval

#11517 [GSoC] NF: Fix deprecations on `Preferences.kt`
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Pending Merge

#11497 feat: Introduce AggregateException
  AnkiDroid/src/main/java/com/ichi2/exceptions/AggregateException.kt
  AnkiDroid/src/test/java/com/ichi2/exceptions/AggregateExceptionTest.kt
Labels: Review High Priority, Needs Second Approval

#11374 Fix Type Answer Diff for combining marks not showing up
  AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt
  AnkiDroid/src/test/java/com/ichi2/utils/DiffEngineTest.kt
Labels: Waiting For Feedback, Needs Second Approval

#11519 Updated strings from Crowdin 20220603
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml
  docs/marketing/localized_description/marketdescription-or.txt
Labels: Pending Merge

#11439 Migrate Tls12SocketFactory to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.kt
Labels: Pending Merge

#11515 Remove deprecated LocalBroadcastManager
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
Labels: Pending Merge

#11513 Scoped Storage: Execution of a list of Operations + preemption
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
Labels: Review High Priority, Needs Second Approval

#11520 Replaced String.format in NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#11527 small factorization
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
Labels: Pending Merge

#11534 rot
  AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
Labels: Needs Second Approval

#11543 Mock time clean-up
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/MutableTime.java
Labels: Review High Priority, Needs Second Approval, squash-merge

#11545 NF: remove a useless test
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Labels: Pending Merge

#11540 Fix `follow system dark mode` on custom/auto schedule
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Pending Merge

#11542 Migrate mutable time
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/MutableTime.kt
Labels: Pending Merge

#11548 NF: Remove getbase:floatingactionbutton dependency
  AnkiDroid/build.gradle
  AnkiDroid/src/main/res/values-ldrtl/styles.xml
  AnkiDroid/src/main/res/values/styles.xml
Labels: Pending Merge

#11552 Clean mReviewer
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Labels: Needs Second Approval, squash-merge

#11562 [Kotlin Migration] Migrated DirectGregorianInstantiationTest to KOTLIN
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiationTest.kt
Labels: Pending Merge

#11563 refactor: Extract `Time` from `Collection`
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/TimeManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
  AnkiDroid/src/test/java/com/ichi2/testutils/Backup.kt
Labels: Review High Priority, Needs Second Approval, squash-merge

#11547 fix: exit message when using the review shortcut
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Pending Merge, squash-merge

#11603 Use IN_PROCESS compiler strategy only on CI builds
  build.gradle
  gradle.properties
Labels: Pending Merge

#11558 Fix bug around restoring InsertFieldDialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialogFactory.kt
Labels: Pending Merge

#11605 build(deps): use anki-android-backend:1.1.11
  build.gradle
Labels: Pending Merge

#11600 Switch sqlite temp storage to disk; fix failures in V16
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.kt
Labels: Blocked by dependency

#11614 Use `Settings` string instead of `Preferences`
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Needs Second Approval, Strings

#11611 Fix NoteEditor "Scroll toolbar" menu item sync bug
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#11556 [GSoC] migrated AnkiStatsTaskHandler.createChart() to suspend function
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
Labels: Needs Second Approval

#11617 Dependency updates 20220613
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#11379 [Kotlin Migration] NoteEditorTabOrderTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
Labels: Pending Merge

#11550 Cleaning Meta db
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
Labels: Needs Second Approval

#11616 SyncErrorDialog: remove multiple type declarations after `_`
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Pending Merge

#11606 Replaced CollectionUtils.getLastListElement() with last() in FinderTest.
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
Labels: Pending Merge

#11607 NF: add MigrationException
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
Labels: Review High Priority, Needs Second Approval

#11521 [GSoC] Extract notifications preferences to a new category
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
  AnkiDroid/src/main/res/xml/preferences_notifications.xml
Labels: Review High Priority, Pending Merge

#11622 Extract NoteEditor preferences strings as constants
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Needs Second Approval

#11625 [GSoC] NF: Remove COMMAND_ prefix from ViewerCommand
  AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerButtons.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerSoundRenderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerButtonsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerActionTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeVolumeButtonsToBindingsTest.kt
Labels: Review High Priority, Pending Merge

#11632 lint: Note Editor
  .idea/dictionaries/anki.xml
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, squash-merge

#11639 Remove some usages of MaterialDialog
  AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DialogUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
Labels: Needs Second Approval

#11633 [GSoC] Kotlin migration Connection.java
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.java
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Labels: Review High Priority, Needs Second Approval

#11641 fix: Improve error if super.setUp() not called
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
  lint-release.xml
Labels: Pending Merge

#11601 Fix crash for Reviewer menu action providers when set to always show
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#11538 non null col
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Labels: Pending Merge, squash-merge

#11652 [GSoC] Add categories icons
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/res/drawable/ic_code.xml
  AnkiDroid/src/main/res/drawable/ic_notifications.xml
  AnkiDroid/src/main/res/drawable/ic_touch.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
Labels: Review High Priority, Pending Merge

#11653 Updated strings from Crowdin 20220617-1
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-de/11-arrays.xml
  AnkiDroid/src/main/res/values-de/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-et/01-core.xml
  AnkiDroid/src/main/res/values-et/02-strings.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-nl/01-core.xml
  AnkiDroid/src/main/res/values-nl/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#11647 [GSoC] Unify gestures with controls
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/GestureSelectionDialogBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/KeySelectionDialogBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_gestures.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
Labels: Pending Merge, Strings, squash-merge

#11628 [GSoC] migrated AnkiStatsTaskHandler.createStatisticsOverview() to suspend function
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
Labels: Review High Priority, Needs Second Approval

#11662 cleanup for ButtonItemAdaptor
  AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
Labels: Needs Second Approval

#11387 LoadPronunciationActivity now extends AnkiActivity
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
  AnkiDroid/src/main/res/layout/activity_load_pronounciation.xml
Labels: Needs Second Approval

#11522 [GSoC] Reorganize reviewing preferences
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
  AnkiDroid/src/main/res/drawable/ic_accessibility_24.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_acessibility.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Review High Priority, Needs Second Approval

#11637 refactor: Convert DirectSystemTimeInstantiationTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSystemTimeInstantiationTest.kt
Labels: Pending Merge

#11636 refactor: Convert DirectSystemCurrentTimeMillisUsageTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsageTest.kt
Labels: Pending Merge

#11593 Fix: deprecation in CardTemplateEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#11594 fix: `toLowerCase` deprecation in BeolingusParser
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
Labels: Pending Merge

#11682 [GSoC] Remove `ConfirmationPreferenceCompat.kt`
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ConfirmationPreferenceCompat.kt
  AnkiDroid/src/main/res/values/04-network.xml
  AnkiDroid/src/main/res/xml/preferences_sync.xml
Labels: Review High Priority

#11683 [GSoC] NF: Simplify devOptions preference's fragment assignment
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Review High Priority

#11685 [GSoC] NF: Remove `ResetLanguageDialogPreference.kt`
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ResetLanguageDialogPreference.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Waiting For Feedback, Pending Merge

#11635 docs: DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Labels: Pending Merge

#11651 [GSoC] migrate PerformDowngradeTask to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
Labels: Review High Priority, Pending Merge

#11580 Whiteboard Cleanup - scope function
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Pending Merge

#11591 fix: deprecation in FieldEditText
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Pending Merge

#11595 [Kotlin Cleanup] CheckMediaTest
  AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.kt
Labels: Pending Merge

#11631 Some small cleanups for the toolbar in NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Pending Merge

#11650 Cleanups for ModelFieldEditor
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge

#11658 replaced the format in ImageFilled.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
Labels: Pending Merge

#11684 [GSoC] NF: clean ControlPreference.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
Labels: Review High Priority, Pending Merge

#11602 [Kotlin Migration] Migrated DirectSnackbarMakeUsageTest to KOTLIN
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsageTest.kt
Labels: Pending Merge

#11676 Kotlin Migration TagsutilTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/utils/TagsUtilTest.kt
Labels: Needs Second Approval

#11385 Kotlin migration HttpTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt
Labels: Pending Merge

#11523 Enable DrawAllocation lint check
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.kt
  AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.kt
  lint-release.xml
Labels: Pending Merge, Needs Second Approval

#11378 [Kotlin migration] FieldEditLineTest.kt
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
Labels: Pending Merge, Needs Second Approval

#11113 Fixed SearchDecks Icon visibility not updating if DeckCount changed
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Labels: Pending Merge, Needs Second Approval, squash-merge

#10218 [Kotlin Migration] CollectionTest
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
Labels: Pending Merge

#11712 [GSoC] Filter Sheet: Create function to retrieve names of all models
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
Labels: Review High Priority, Pending Merge

#11679 [GSoC] enhanced error handling when launching coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
Labels: Review High Priority, Pending Merge, squash-merge

#11714 chore: Set permissions for GitHub actions
  .github/workflows/stale.yml
  .github/workflows/sync_translations.yml
Labels: Pending Merge

#11719 [GSoC] Refactor preferences fragments initialization
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Labels: Review High Priority, Pending Merge

#11718 chore: add ColorInt annotation
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Pending Merge

#11716 refactor: convert DuplicateCrowdInStringsTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStringsTest.kt
Labels: Pending Merge

#11715 refactor: convert DirectToastMakeTextUsageTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsageTest.kt
Labels: Pending Merge

#11720 rename: strings.xml to analytic_constants.xml
  AnkiDroid/src/main/res/values/analytic_constants.xml
Labels: Needs Second Approval

#11681 [GSoC] migrated LoadPronunciationActivity to Coroutines
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
Labels: Review High Priority, Needs Second Approval

#11707 Migrate DuplicateTextInPreferencesXmlTest to kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
Labels: Needs Second Approval

#11728 refactor: Convert Storage to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/RustTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.java
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/DbUtils.kt
Labels: Pending Merge
