Repository ankidroid/Anki-Android, pull requests merged in 2022-08, with the labels that each got.

#11954 NF: uses Apply on `mLatestInstance`
  AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
Labels: Needs Second Approval

#11950 NF: Create typealias DeckId
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TagManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TagsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextCardExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV3.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Pending Merge

#11958 NF: make currentSearchTerm local
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Labels: Needs Second Approval

#11962 Add a comment stating not to rename/remove credits
  README.md
Labels: Pending Merge

#11957 NF: Ensure searchTerm is non null
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#11927 [Kotlin Cleanup] if/elseif... to when in NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Pending Merge

#11934 [GSoC] Reorganize some preferences + refactors
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  AnkiDroid/src/main/res/xml/preferences_accessibility.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Review High Priority, Strings

#11961 View animation
  AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt
Labels: Needs Second Approval

#11909 [Kotlin Migration] ActivityList
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Needs Review, Needs Second Approval

#11988 Move the main testutils package to the unit test source set
  AnkiDroid/src/test/java/com/ichi2/testutils/DialogUtils.kt
Labels: Needs Review

#11990 NF: Remove StringUtil.strip()
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
Labels: Needs Second Approval

#11994 Replace use of String.format with a template expression
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.kt
Labels: Needs Second Approval

#11977 [GSoC] Add `Use new backend` (persistent) preference
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Pending Merge, Strings

#12005 NF: Exchange `.beginTransaction` for `.commit`
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
Labels: Needs Second Approval

#11461 [Kotlin Cleanup] CardBrowser pt4
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Labels: Stale

#12013 `data` in Card is lateinit
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
Labels: Needs Second Approval

#11987 NF: replace `is`
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
  AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskSearchCardsTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/NoteTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/importer/python/CsvProcessIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
Labels: Needs Second Approval

#11995 Make possible to commit hunks on Kotlin again
  pre-commit
Labels: Needs Second Approval

#11983 NF: converting Long to DeckId
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DeckService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuAndroidTest.kt
Labels: Pending Merge

#12015 NF: export without scheduling: remove all system tags
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
Labels: Needs Second Approval

#12016 Migrate db.java to kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/DbUtils.kt
Labels: Needs Second Approval

#11984 NF: uses NoteId instead of Long
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
Labels: Needs Second Approval

#12019 test: LeakCanary channels are auto-created / okay to have
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.java
Labels: Needs Second Approval

#12028 Updated strings from Crowdin 20220814
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ka/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/04-network.xml
  AnkiDroid/src/main/res/values-ka/06-statistics.xml
  AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/08-widget.xml
  AnkiDroid/src/main/res/values-ka/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/11-arrays.xml
  AnkiDroid/src/main/res/values-ka/17-model-manager.xml
  AnkiDroid/src/main/res/values-ka/18-standard-models.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#12017 NF: executeInTransaction returns value
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/UndoService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
Labels: Pending Merge

#12018 Query with null selection
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
Labels: Needs Second Approval

#11985 NF: replace Long by CardId
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
Labels: Needs Second Approval

#12036 Dependency updates 20220816
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge

#12041 Fix time taken in v3 scheduler being capped to maximum
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV3.kt
Labels: Pending Merge

#11986 NF: replace Long by NotetypeId
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
Labels: Pending Merge

#12059 Variable names cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Review High Priority, Pending Merge

#12043 refactor: Convert AbstractSchedTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
Labels: Needs Second Approval

#12044 refactor: Convert MediaTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
Labels: Needs Second Approval

#12046 refactor: Convert ProductionCrashReportingTreeTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.kt
Labels: Needs Second Approval

#12038 Fix crash if NumberRangePref value is empty on close
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
Labels: Pending Merge

#12067 refactor: Convert DBTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt
Labels: Pending Merge

#11998 Cleanup in CardBrowser Part 1
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#12068 refactor: Convert DeckConfig to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.kt
Labels: Pending Merge

#12058 Fix save search in CardBrowser when dialog has no list
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Labels: Needs Second Approval

#12062 perf: testAnswerCard
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
Labels: Needs Second Approval

#12069 refactor: Convert MathFunctionAtom to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/MathFunctionAtom.kt
Labels: Pending Merge

#12071 refactor: Convert StdModels to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
Labels: Pending Merge

#11908 Modify `findNotes()` to use V16 `searchNotes()` function
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
Labels: Pending Merge, squash-merge

#10968 Added custom layout to the spinner adapter in the card browser activity to prevent the overlapping of various interactive components on the screen
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/res/layout/spinner_custom_layout.xml
  AnkiDroid/src/main/res/values/styles.xml
Labels: Waiting For Feedback

#11236 [Enhancement] Matched the color of statusbar to actionbar & navbar to background.
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Pending Merge, squash-merge

#11401 Fixed the bug that filtered study decks don't show in Card browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
Labels: Pending Merge

#11388 [Kotlin Cleanup] CollectionUtils
  AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
Labels: Pending Merge

#11551 NF: Conversion to nullable, then non null simplified
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceToDowngradeDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheck.kt
Labels: Needs Review

#12042 refactor: Convert NotificationChannelTest to Kotlin
  AnkiDroid/build.gradle
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
Labels: Needs Review

#12047 refactor: Kotlin - fix nullability
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
Labels: Needs Review

#12078 refactor: Convert PrintStackTraceUsageTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/PrintStackTraceUsageTest.kt
Labels: Pending Merge

#12077 refactor: Convert PreferIsEmptyOverSizeCheckTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheckTest.kt
Labels: Pending Merge

#12076 refactor: Convert JavaNonPublicNonStaticFieldDetectorTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/JavaNonPublicNonStaticFieldDetectorTest.kt
Labels: Pending Merge

#12075 refactor: Convert JavaConstantFieldDetectorTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/JavaConstantFieldDetectorTest.kt
Labels: Pending Merge

#12074 refactor: Convert InconsistentAnnotationUsageTest to Kotlin
  lint-rules/kotlinMigration-lint.gradle
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsageTest.kt
Labels: Pending Merge, Needs Review

#11948 NF: remove unchecked cast when possible
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.kt
  AnkiDroid/src/main/java/com/ichi2/utils/FragmentFactoryUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/UniqueArrayList.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/RecyclerViewUtils.kt
Labels: Pending Merge

#12064 NF: Replace FragmentLayout with FragmentContainerView as the container for fragments
  AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
  AnkiDroid/src/main/res/layout/preferences.xml
Labels: Pending Merge

#11425 Factorize close
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Pending Merge

#12083 rename: Sound.kt -> SoundKt.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
  AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
Labels: Needs Second Approval

#12061 refactor: Convert NoteEditorTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Needs Second Approval

#12085 refactor: Convert AnkiAssert to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.kt
Labels: Pending Merge

#12086 refactor: Convert TestUtils to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
Labels: Pending Merge

#12090 Remove whitespace and code style checklist items
  .github/pull_request_template.md
Labels: Needs Review

#12087 refactor: Convert ACRATest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
Labels: Pending Merge

#12089 lint: fix IDE Lint issues
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
Labels: Pending Merge

#12094 refactor: Convert XAxis to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/rendering/XAxis.kt
Labels: Pending Merge

#12096 refactor: Convert YGrid to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/rendering/YGrid.kt
Labels: Pending Merge

#12097 refactor: Convert YAxis to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/rendering/YAxis.kt
Labels: Pending Merge

#12072 [GSoC] Add option to import text files
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt
Labels: Review High Priority, Pending Merge, Strings

#11899 open card browser and search using deep links
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#11925 Fix Rate menu item availability in help/support dialogs
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.kt
Labels: Pending Merge

#11862 fix: close previous dialog after full sync dialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge, squash-merge

#12100 refactor: Convert AnkiPackageExporterTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
Labels: Needs Second Approval

#12102 refactor: Convert ImportTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
Labels: Needs Second Approval

#12115 refactor: Convert AnkiActivity to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/FragmentTestActivity.kt
Labels: Review High Priority, Needs Second Approval

#12126 NF: Kotlin cleanup
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/RetryRule.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextCardExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.kt
Labels: Needs Second Approval, squash-merge

#12124 refactor: Convert Pow to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/wildplot/android/parsing/Pow.kt
Labels: Pending Merge

#12129 Updated finishActivityWithFade
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
Labels: Needs Second Approval

#12118 refactor: Convert TextNoteExporterTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
Labels: Pending Merge

#12116 refactor: Convert PlotSheet to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
  AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.kt
Labels: Pending Merge

#12109 Removed method name from translatable string "import_error_copy_file_to_cache"
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Strings, squash-merge

#12132 refactor: extract 'showedActivityFailedScreen'
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/AppLoadedFromBackupWorkaround.kt
Labels: Review High Priority, Pending Merge

#12093 Use snackbars instead of toasts on the reviewer's actions
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Second Approval

#12141 NF: put storageTest strings as lateinit
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
Labels: Pending Merge

#11956 NF: browser use two columns explicitly
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#12117 refactor: Convert Tokenizer to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
Labels: Pending Merge

#12127 refactor: convert Finder to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
Labels: Pending Merge

#12136 refactor: KotlinCleanup - CustomTabsHelper
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Labels: Pending Merge

#12151 refactor: make Note Fields non-null
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
Labels: Pending Merge

#12159 fix: margin of Floating Action Button in Card Browser
  AnkiDroid/src/main/res/layout/card_browser.xml
Labels: Needs Second Approval

#12162 Revert "NF: browser use two columns explicitly"
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Review High Priority, Pending Merge, Needs Review

#12142 NF: uses assertThrows instead of try{expectToFail}catch{}
  AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Needs Second Approval

#12149 refactor: Convert FloatMatcher to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/wildplot/android/rendering/FloatMatcher.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
  AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt
Labels: Needs Second Approval

#12148 refactor: Convert Replacement to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt
Labels: Pending Merge

#11974 Enlarge size of checkbox in Tag Picker dialog
  AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
  AnkiDroid/src/main/res/drawable/ic_baseline_check_box_24_inset.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_check_box_outline_blank_24_inset.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_indeterminate_check_box_24_inset.xml
  AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml
Labels: Pending Merge

#12168 build: bump compileSdkVersion to 32
  AnkiDroid/build.gradle
  api/build.gradle
Labels: Pending Merge

#12170 Dependency updates 20220825
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge

#12172 Add Anki's new CardInfo page
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
Labels: Needs Second Approval

#12176 [GSoC] Make the CSV importer accept .csv and .tsv extensions
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Labels: Review High Priority, Needs Second Approval

#12137 refactor: KotlinCleanup - DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Pending Merge

#11426 NF: factorize DeckPreferenceHack
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Waiting For Feedback, Pending Merge

#12160 refactor: Convert AnkiDroidApp to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/testutils/TestingApplication.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/JavaScriptTTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/snackbar/SensibleSwipeDismissBehavior.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/FabBehavior.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/AppLoadedFromBackupWorkaround.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
Labels: Pending Merge

#12146 refactor: Convert ContentProviderTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
Labels: Pending Merge

#12144 refactor: Convert SchedTest to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
Labels: Pending Merge

#12110 refactor: Convert Sound to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
Labels: Needs Second Approval

#12106 refactor: Convert Utils to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
  AnkiDroid/src/test/java/com/ichi2/utils/UnzipFile.kt
Labels: Pending Merge

#12190 Updated strings from Crowdin 20220826
  AnkiDroid/src/main/res/values-be/02-strings.xml
  AnkiDroid/src/main/res/values-be/03-dialogs.xml
  AnkiDroid/src/main/res/values-be/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
Labels: Pending Merge

#12191 NF: remove more files from the legacy CSV importer implementation
  AnkiDroid/src/main/java/com/ichi2/anki/importer/CsvMapping.kt
  AnkiDroid/src/main/java/com/ichi2/anki/importer/Domain.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/importer/CsvMappingTest.kt
Labels: Pending Merge, Strings

#12114 refactor: Convert Decks to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
Labels: Pending Merge

#12197 refactor: add MaterialDialog.iconAttr
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
Labels: Pending Merge

#12188 refactor: Convert Media to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt
Labels: Pending Merge

#12011 NF: simplify catchingLifecycleScope
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
Labels: Needs Second Approval

#11913 JSONObject nullability cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Model.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONTokener.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Pending Merge, squash-merge

#12192 NF: Kotlin Cleanup
  .idea/dictionaries/usernames.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
Labels: Pending Merge, squash-merge

#12193 nf: Kotlin Cleanup
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerImportTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiActivityUtils.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertKt.kt
Labels: Pending Merge, squash-merge

#12186 Add `strings` label when res/values dir changes
  .github/workflows/label.yml
Labels: Pending Merge, squash-merge

#12198 refactor: Convert JSONArray to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.kt
  AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/libanki/FilteredDeckUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
Labels: Pending Merge

#12219 feat: Include Kotlin files in code coverage
  AnkiDroid/jacoco.gradle
Labels: Needs Review

#12030 fixed: deck search not scrolling to current deck in statistics
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Pending Merge, squash-merge

#11753 Removed "paste as plain text"
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge, squash-merge

#12228 ci: stop codecov from failing CI
  .codecov.yml
  .idea/dictionaries/android.xml
Labels: Needs Review

#12236 fix: replace cloze with blank within <tts> tag
  AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TtsParserTest.kt
Labels: Needs Second Approval

#12235 NF: simplify UpdateNote
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Needs Second Approval

#12243 fix: suppressed stack trace when error in coroutine occurs.
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#12247 Added Anki Forum URL in Readme file in Join Us On section
  README.md
  docs/graphics/logos/anki_forums_logo.png
Labels: Pending Merge

#12177 [GSoC] Simplified UpdateMultipleNotes asynctask callbacks
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Labels: Review High Priority, Pending Merge

#12217 Kotlin Cleanup: prep for CollectionHelper migration
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
  AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.kt
Labels: Pending Merge, squash-merge

#12222 refactor: Convert AdvancedStatistics to Kotlin
  AnkiDroid/kotlinMigration.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.kt
Labels: Pending Merge

#12257 Fix Card info on the legacy schema if opened from the deck picker
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge
