Repository ankidroid/Anki-Android, pull requests merged in 2022-12, with the labels that each got.

#12697 [Bug] day/night mode is not switched when AnkiDroid closed by the back button
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiActivityTest.kt
Labels: Pending Merge

#12917 Fix expanders not appearing
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#12911 Fix app crashing if deck from shortcut does not exist anymore
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#12931 Fix position of buttons in change deck dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Needs Second Approval

#12945 Fix dialog language bug
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Needs Second Approval

#12959 TODO - Use string template and remove neutral button
  AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Needs Second Approval

#12964 Added contract for null -> null and non-null to non-null.
  api/src/main/java/com/ichi2/anki/api/Utils.kt
Labels: Needs Second Approval, cleanup

#12977 Fix custom study deck appearance with no delay
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Needs Author Reply

#12971 Changed the color of the zero count
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
Labels: Needs Second Approval

#12967 bug fix for deck export
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Needs Second Approval

#12970 string intent fix
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
Labels: Needs Author Reply, Needs Second Approval

#12976 Add CI job to append a special label to PRs made by new contributors
  .github/workflows/label.yml
Labels: Needs Review

#12982 NF: fix IDE lint in HttpSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
Labels: Priority-Low, cleanup

#12997 Fix typo in new contributor label workflow
  .github/workflows/label.yml
Labels: Needs Review

#12988 [KotlinCleanUp] OnRenderProcessGoneDelegateTest,SchedTest.kt,FragmentTestActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/FragmentTestActivity.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
Labels: Priority-Low, Needs Author Reply, cleanup

#13013 build(deps): use backend 0.1.17-2.1.55 now with TLS
  build.gradle
Labels: Pending Merge

#13014 fix(i18n): forward port to python3
  tools/update-localizations.py
Labels: Review High Priority, Needs Review, Dev, Strings

#12956 Make possible to disable leak canary on local.properties
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
Labels: Needs Second Approval

#13020 Dependency updates 20221221
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#13001 Kotlin cleanup of NoteEditorTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Priority-Low, Needs Author Reply, Needs Second Approval, cleanup

#13026 Fix incorrect timezone in new schema
  build.gradle
Labels: Pending Merge

#13024 [Kotlin cleanup] AnkiAssert.kt,CollectionAssert.kt,ExportingTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ExportingTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt
Labels: Priority-Low, cleanup

#12938 Renamed name to fullDeckName
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
Labels: Needs Second Approval, cleanup

#12568 [KotlinCleanup] FieldEditText
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Pending Merge, squash-merge

#13035 Make invisible expanders unclickable
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
Labels: Pending Merge, squash-merge

#13029 Solve TODO of secondary color on themes
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceActivity.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Theme.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/res/color/text_color_dark.xml
  AnkiDroid/src/main/res/color/text_color_light.xml
  AnkiDroid/src/main/res/color/text_color_secondary_dark.xml
  AnkiDroid/src/main/res/color/text_color_secondary_light.xml
  AnkiDroid/src/main/res/values/legacy_action_bar.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Needs Second Approval, squash-merge

#13031 fixed windows keyboard layout frame position
  AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
Labels: Pending Merge
