Repository ankidroid/Anki-Android, pull requests merged in 2023-06, with the labels that each got.

#13944 Remove launchWithCol()
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
Labels: Pending Merge

#13945 Catch some attempts to access UI inside withCol, and col within UI thread
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ConfigManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
  lint-release.xml
Labels: Needs Second Approval

#13959 Change preference category title color on the light theme
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Pending Merge

#13854 Adding develepor options to add fake media
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Review High Priority, Pending Merge, squash-merge

#12799 Migrate the ImportAdd task to coroutine
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt
Labels: Review High Priority, Pending Merge, squash-merge

#13950 NF: document that `withCol` and `withQueue` executes in IO
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
Labels: Pending Merge, squash-merge

#13910 Changed Material Dialog with Alert Dialog for ModelBrowserContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
Labels: Needs Second Approval

#12280 Update FAB UI for more intuitive double tapping
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
  AnkiDroid/src/main/res/drawable/ic_add_note.xml
  AnkiDroid/src/main/res/layout/floating_add_button.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerFloatingActionMenuTest.kt
Labels: Needs Second Approval, squash-merge

#13968 Migrate CardBrowserOrderDialog to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Pending Merge, Strings

#13971 Migrate the FindEmptyCards task to coroutines
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
Labels: Pending Merge, Strings, squash-merge

#13979 checking for null result to avoid class cast exception
  AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
Labels: Pending Merge, squash-merge

#13992 NF: `MetaDB` should run on worker thread
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
Labels: Needs Second Approval

#13980 NF: move selectDeckFomExtra to onCollectionLoaded
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#13964 Update androidx fragments library to 1.6.0
  AnkiDroid/build.gradle
  build.gradle
Labels: Needs Second Approval, dependencies

#13911 Fix background image distort for DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/layout/deck_picker.xml
  AnkiDroid/src/main/res/layout/homescreen.xml
Labels: Needs Second Approval

#13982 Remove FAB rotation and change duration
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Needs Second Approval

#13994 NF: Correct typing of getBundleEditFields
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
Labels: Needs Second Approval

#13996 fix: StudyOptionsFragment showing "Failed to create directory" message
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Review High Priority, Needs Second Approval

#14009 Dependency updates 20230621
  .github/dependabot.yml
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  build.gradle
Labels: Pending Merge, squash-merge

#13849 Improve stylus related functions(menu, controls)
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Strings

#14020 Dependency updates 20230622
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#13451 Show keyboard in onResume state of Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Review

#13616 #12451 Issue: Replace string with plurals
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Pending Merge, Strings, squash-merge, New contributor

#13952 Disable keep screen on while disabling automatic show answer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
Labels: Needs Review

#14022 fix build related to vanished transitive dependency of amazon publish plugin
  build.gradle
Labels: Pending Merge

#14008 NF: Remove setTitle in AbstractFlashCardViewer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
Labels: Needs Second Approval

#14001 checking for bitmap size to avoid `illegalArgumentException`
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Needs Second Approval

#14003 Moved cursor to end in IncrementerNumberRangePreferenceCompat
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt
Labels: Needs Author Reply

#14032 Fix crash when encountering bad storage volume UUID strings
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt
Labels: Needs Second Approval, Scoped storage

#13917 Added marketing images for play store
  docs/marketing/play_store/1.png
  docs/marketing/play_store/2.png
  docs/marketing/play_store/3.png
  docs/marketing/play_store/4.png
Labels: Pending Merge, New contributor

#14033 Fix card browser add icon appearing dark
  AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
Labels: Pending Merge

#14044 Fix empty front card
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, squash-merge, New contributor

#13640 horizontalPadding to FixedEditText and showing warning instead of Toast
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
Labels: Needs Second Approval

#14045 build(deps): gradle wrapper update PRs should target dependency-updates branch
  .github/workflows/update-gradle-wrapper.yml
Labels: Pending Merge

#14046 Dependency updates 20230628
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
  .github/workflows/update-gradle-wrapper.yml
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge

#14039 fix: Open changelog's link to development commits in an external browser
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Pending Merge
