Repository ankidroid/Anki-Android, pull requests merged in 2023-03, with the labels that each got.

#13376 Issue template: Use "render: text" for debug info
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Needs Second Approval, New contributor

#13379 fix: Disable "force full sync" preference when user is not logged in
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
Labels: Pending Merge

#13389 test(Windows): previewWorksAfterSort is flaky
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#13371 fix: "Backup Dialog" for users who sync
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
Labels: Pending Merge

#13395 test: mark flaky tests
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#13397 add tool: enable/disable scoped storage
  tools/storage/set_scoped_storage.sh
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13400 Fix opening AnkiWeb account preference
  AnkiDroid/build.gradle
Labels: Needs Second Approval

#13359 refactor: DialogHandler
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DatabaseErrorDialogTest.kt
Labels: Review High Priority, Needs Second Approval

#13086 fixed the crash that occured due to `getResources()` error
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
Labels: Needs Second Approval

#13378 Hide the Floating Action Button
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/res/layout/card_browser.xml
Labels: Needs Review, New contributor

#13409 fix: Replace toast with snackbar and format code
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Author Reply, Needs Second Approval

#13402 Fixed hardware keyboard search bug.
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#13421 use endpoint for custom sync server
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/BackendSync.kt
Labels: Pending Merge

#13037 refactor in Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Priority-Low, Needs Second Approval, cleanup

#13416 fix: Search box is filled with required query of filter marked and filter suspended
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#13430 NF: refactor "animationEnabled"
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Needs Second Approval

#13309 fix queryIntentActivities deprecation
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/test/java/com/ichi2/compat/customtabs/CustomTabActivityHelperTest.kt
Labels: Pending Merge, squash-merge

#13418 Set kotlin related task in lint-rules module to use JVM 11
  lint-rules/build.gradle
Labels: Needs Second Approval

#13422 remove unused 'ScopedStorageMigrationDialog'
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
  AnkiDroid/src/main/res/layout/scoped_storage_confirmation.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings, Scoped storage

#13423 fix: Rename performPermissionRequest
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
Labels: Needs Author Reply, Needs Second Approval

#13441 Used AlertDialog instead of MaterialDialog in DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#13445 Fix newly created deck not showing when changing card's deck in CardBrowser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval

#13345 refactor: Sound/Video
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerSoundRenderTest.kt
Labels: Priority-Low, Pending Merge

#13457 Fix AnswerTimer.resetTimerUI() not seting color correctly
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
Labels: Needs Second Approval, New contributor

#13459 Changed Material Dialog with Alert Dialog for ManageNotetypes.kt.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
Labels: Needs Second Approval

#13466 fix: Changed startup permission toast message in Android >= R
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#13481 Changed Material Dialog with Alert Dialog for CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Needs Author Reply, Needs Second Approval

#13467 Changed Material Dialog with Alert Dialog for Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Needs Author Reply, Needs Second Approval

#13476 Showing Warning on Reset to Default button in App bar buttons
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, Strings

#13478 recreate DeckPicker activity on Deleting collection from app settings
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, Strings

#13471 Fixed a conditional check for schedV2
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
Labels: Needs Second Approval

#13508 build: 'full' build with no manifest restrictions
  AnkiDroid/build.gradle
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13505 NF: Rename handleStoragePermissionsCheckForCheckMedia
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Priority-Low, cleanup

#13512 Remove unused method
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Second Approval

#13495 Fix some activityResult deprecations
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#13514 Use "full" flavor on parallel builds
  tools/parallel-package-release.sh
  tools/release.sh
Labels: Needs Review, Scoped storage

#13475 Whiteboard - Stylus Only Mode
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/res/drawable/ic_gesture_stylus.xml
  AnkiDroid/src/main/res/menu-television/reviewer.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Pending Merge, Strings, squash-merge, New contributor

#13511 fix deprecation and unchecked cast
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Needs Second Approval

#13517 refactor: toggleStylus - Kotlin Cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Priority-Low, Needs Second Approval

#13513 Replace MaterialDialog with AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.kt
Labels: Needs Second Approval

#13510 Fix bundle.get deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Review

#13519 Don't finish activity after requesting all files access permission
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13507 NF: rename DeleteOnUninstall
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
Labels: Priority-Low, Needs Second Approval, cleanup

#13488 Showing Snackbar instead of Toast in Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Author Reply, Needs Second Approval
