Repository ankidroid/Anki-Android, pull requests merged in 2023-12, with the labels that each got.

#14854 chore(lint): cleanup CI output on failure
  lint.gradle
Labels: Needs Review

#14852 Kotlin Cleanup: KDocs
  AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/DeckRenameException.kt
  AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.kt
Labels: Priority-Low, Needs Review, squash-merge

#14861 refactor(CardBrowser): rename method
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Priority-Low, Needs Review

#14862 chore: add SharedPreferencesProvider
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SharedPreferencesProvider.kt
Labels: Priority-Low, Needs Second Approval

#14830 8602 - NoteEditor startActivityForResult Migration
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Author Reply, Pending Merge

#14868 fix(ReviewerServer): return scheduling states with customData
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
  AnkiDroid/src/main/java/com/ichi2/annotations/DuplicatedCode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
Labels: New contributor

#14878 Refactor ImportFileSelectionFragment as a standalone DialogFragment
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Labels: Needs Author Reply, Pending Merge

#14879 Fix app bar color in tags dialog
  AnkiDroid/src/main/res/layout/tags_dialog_title.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Labels: Needs Second Approval, New contributor

#14877 stop timer on resuming the app after ans
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#14842 Issue 8602, Reviewer startActivityForResult Migration
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval, squash-merge

#14859 Fix changing the cards order to 'NoOrdering' after toggling to 'Notes'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval, squash-merge, New contributor

#14892 CardBrowser: refactor 'cardsOrNotes' to Flow
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Priority-Low, Needs Review, squash-merge

#14895 fix broken CI: checkDisplayOrderAfterTogglingCardsToNotes
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#14889 fix: Syncing handles notetype style changes
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
Labels: Pending Merge

#14679 Replaced Toast with Snackbar in ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Labels: Needs Second Approval

#14896 Enable merge queue trigger / remove CI-avoidance optimization event filters
  .github/workflows/lint.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Needs Review, CI

#14875 fix: adding tags should not unflip card
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt
Labels: Needs Second Approval

#14902 fix: TTS comment
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Strings

#14833 refactor: Key Bindings
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
  AnkiDroid/src/main/java/com/ichi2/ui/KeyPicker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
Labels: Priority-Low, Needs Review

#14899 fix: show card answer after custom scheduler completes
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
Labels: Review High Priority, Needs Second Approval

#14907 Dependency updates 20231208
  AnkiDroid/build.gradle
Labels: Pending Merge

#14910 feat: add backend version to debug info & cleanup
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Labels: Needs Second Approval

#14904 Browser: extract methods
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval, squash-merge

#14894 remove color inversion
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
  AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardAppearanceTest.kt
  AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt
Labels: Needs Second Approval

#14911 fix(api): render [sound:] tags
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
Labels: Needs Review

#14931 remove reviewer deck title
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Pending Merge

#14932 HACK: fix CI: BadWindowTokenException
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
Labels: Review High Priority

#14930 remove reviewer ETA
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
Labels: Pending Merge, Strings

#14929 fix: previewer crash when cast to CardTemplatePreviewer
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
Labels: Review High Priority, Pending Merge

#14872 Dismissed the BackupDialog on never show again selected
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
Labels: Needs Second Approval

#14900 Browser: refactor selected rows
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Priority-Medium, Needs Review, squash-merge

#14936 fix: show sync errors to user but no crash report
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Needs Review

#14951 test: wait for deck to load before clicking on it
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
Labels: Review High Priority, Pending Merge

#14958 test(ci): ignore merge queue branch push events
  .github/workflows/lint.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Pending Merge

#14960 test: fix JNI critical lock held error in instrumentation tests
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
Labels: Pending Merge, CI

#14914 Browser: refactor `mCards` partially
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Priority-Medium, Pending Merge, squash-merge

#14959 fix: CardBrowser - click row to deselect
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#14957 Warning when WebView (<77) is outdated
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge, squash-merge, New contributor

#14966 Update backend version to 0.1.32-anki23.10.1
  build.gradle
Labels: Review High Priority, Needs Second Approval

#14982 chore: extract test methods to tests
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Priority-Low, Needs Review

#14980 tests: remove dev options from PreferencesAnalyticsTest
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
Labels: Needs Second Approval

#14976 style: change some icons' tint to colorControlNormal
  AnkiDroid/src/main/res/drawable/ic_card_answer.xml
  AnkiDroid/src/main/res/drawable/ic_card_question.xml
  AnkiDroid/src/main/res/drawable/ic_mode_edit_white.xml
Labels: Needs Second Approval

#14983 fix: navigator.getGamepads() does not work
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gamepad.kt
Labels: Needs Review

#14979 refactor: create Flag Enum
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
Labels: Needs Second Approval

#14981 refactor: add SingleFragmentActivity class
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/res/layout/single_fragment_activity.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge

#14978 libanki: add `addPlayButtons()` and rename `addPlayIcons()`
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
Labels: Pending Merge

#15004 Fixed two naming convention issues in CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge, New contributor

#14884 Integrate image occlusion editor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiPackageImporterFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/res/layout/note_editor.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Review High Priority, Pending Merge, Strings, squash-merge

#14926 chore: speed up server & fix log spam
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
Labels: Needs Review

#15002 fix: play buttons being shown as big black buttons
  AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
Labels: Needs Second Approval

#15005 feat: print elapsed time of methods
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt
Labels: Pending Merge

#15007 Dependency updates 20231216
  AnkiDroid/build.gradle
Labels: Pending Merge, squash-merge

#15016 Revert "feat: speed up single tap gestures"
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Review High Priority, Pending Merge

#14797 use `SaveInstanceState` to avoid crash in export file when Activity is recreated
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Pending Merge, squash-merge

#15039 Various Rust cleanups
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendUndo.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.kt
Labels: Priority-Low, Pending Merge, cleanup, squash-merge

#15037 fix: allow seeking videos
  AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/RangeHeader.kt
Labels: Needs Second Approval

#15042 fix ide issues
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Needs Review, squash-merge, New contributor

#15032 cleanup: FlashardViewer - remove 'controlBlocked'
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Needs Review, cleanup, squash-merge

#14923 Remove most of custom activity transition animations in favor of consistency
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/AppLoadedFromBackupWorkaround.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/IntentUtil.kt
  AnkiDroid/src/main/res/anim/decelerate_cubic.xml
  AnkiDroid/src/main/res/anim/decelerate_quint.xml
  AnkiDroid/src/main/res/anim/dialog_exit.xml
Labels: Pending Merge, squash-merge

#14898 refactor: Browser sort order + direction
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/ReverseDirection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
Labels: Needs Second Approval, squash-merge

#14948 PERF: Use backend to load `Note`
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/exception/WrongId.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt
Labels: Pending Merge, squash-merge

#14972 feat: add device shake gesture detection
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Blocked by dependency, Strings, New contributor

#14945 refactor: extract 'CardBrowserLaunchOptions'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserLaunchOptions.kt
Labels: Needs Second Approval

#14946 refactor: Browser lastDeckId/restrictOnDeck
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Priority-Medium, Pending Merge, squash-merge

#15051 refactor: extract CardBrowserColumn
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserColumn.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval

#15056 chore: remove unused assets
  AnkiDroid/src/main/assets/fonts/OpenSans-Bold.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-BoldItalic.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-CondBold.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-CondLight.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-CondLightItalic.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-ExtraBold.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-Italic.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-Light.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-LightItalic.ttf
  AnkiDroid/src/main/assets/fonts/OpenSans-Regular.ttf
  AnkiDroid/src/main/assets/inline_play_button.png
Labels: Pending Merge

#15059 fix crash when sharing Export Collection
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Pending Merge

#15044 remove DeckRenameException
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/DeckRenameException.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge

#14947 Browser: Refactor filters (flag, suspend, marked, tags)
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Review, squash-merge

#15062 Use AlertDialog in control preferences
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Labels: Pending Merge

#15064 Kotlin Cleanup
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Priority-Low, Pending Merge, cleanup, squash-merge

#15074 refactor: Card Browser - Preview
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#15076 fix(cardbrowser): deck restriction not set
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Needs Review

#15060 refactor: Browser multi select
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge, squash-merge

#15073 fix : Placeholders in delete note type dialog
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
Labels: Pending Merge

#15078 refactor: updateSelectedCardsFlag
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Needs Second Approval

#15097 api upgrade from card.js to js-api.js
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, squash-merge

#14973 Changed color of ProgressBar
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Pending Merge

#15101 github action to check conflict in pr and add label
  .github/workflows/conflict.yaml
Labels: Pending Merge, squash-merge

#15099 test: maybe fix flaky test: typedLanguageIsSet
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Review High Priority, Pending Merge
