Repository ankidroid/Anki-Android, pull requests merged in 2023-11, with the labels that each got.

#14596 Upgrade to Material3 themes
  AnkiDroid/build.gradle
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/VersatileTextWithASwitchPreference.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Theme.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
  AnkiDroid/src/main/res/color/switch_thumb_tint.xml
  AnkiDroid/src/main/res/color/switch_track_tint.xml
  AnkiDroid/src/main/res/layout-land/introduction_layout.xml
  AnkiDroid/src/main/res/layout/about_layout.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
  AnkiDroid/src/main/res/layout/card_browser_appearance.xml
  AnkiDroid/src/main/res/layout/floating_add_button.xml
  AnkiDroid/src/main/res/layout/introduction_layout.xml
  AnkiDroid/src/main/res/layout/item_manage_note_type.xml
  AnkiDroid/src/main/res/layout/my_account.xml
  AnkiDroid/src/main/res/layout/my_account_logged_in.xml
  AnkiDroid/src/main/res/layout/permission_item.xml
  AnkiDroid/src/main/res/layout/permissions_activity.xml
  AnkiDroid/src/main/res/layout/preference_material_switch_widget.xml
  AnkiDroid/src/main/res/layout/preference_slider.xml
  AnkiDroid/src/main/res/layout/preference_widget_switch_with_separator.xml
  AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
  AnkiDroid/src/main/res/layout/toolbar.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerFloatingActionMenuTest.kt
Labels: Pending Merge, squash-merge

#14629 docs: update opencollective notice to remove GSoC reference
  .github/workflows/opencollective_notices.yml
Labels: Needs Review

#14634 chore(logs): 'blocked main thread' => warning
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
Labels: Priority-Low, Needs Review

#14632 Update to stable 23.10 backend version
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
  build.gradle
Labels: Pending Merge, Backend Related

#14658 fix: only close the permissions screen by tapping the continue button
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
Labels: Needs Second Approval

#14665 Allow first field to be empty in edit note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#14666 docs(NoteEditor): NeedsTest - After a note is saved, 'first field must not be empty' does not apply
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Priority-Low, Needs Review

#14591 replacing the existing audio recorder
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioTimer.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioWaveform.kt
  AnkiDroid/src/main/res/drawable/baseline_forward_5_24.xml
  AnkiDroid/src/main/res/drawable/baseline_replay_5_24.xml
  AnkiDroid/src/main/res/drawable/ic_delete.xml
  AnkiDroid/src/main/res/drawable/ic_record.xml
  AnkiDroid/src/main/res/drawable/round_audio_file_24.xml
  AnkiDroid/src/main/res/drawable/round_done_24.xml
  AnkiDroid/src/main/res/drawable/round_pause_24.xml
  AnkiDroid/src/main/res/drawable/round_play_arrow_24.xml
  AnkiDroid/src/main/res/layout/activity_audio_recording.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Second Approval, Strings, squash-merge

#14675 refactor: Set preferences single line title statically
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Needs Second Approval

#14684 build(deps): adopt android gradle plugin 8.1.3 vs 8.2.0-rc series
  build.gradle
Labels: Pending Merge

#14680 improve Info page UI
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
  AnkiDroid/src/main/res/layout/info.xml
Labels: Needs Second Approval

#14685 Dependency updates 2023108
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge

#14667 Fix active decks config not being updated on deck selection
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
Labels: Needs Review

#14176 Search text is in normal instead hint text
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#14700 Ensure media are detected correctly even with space in their name
  AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Needs Second Approval

#14704 fix: handle plural strings in SliderPreference
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Needs Second Approval, Strings

#14711 Handle android dialog cancellation when used as frontend for js dialogs
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
Labels: Needs Second Approval

#14712 Fix NoteEditor discarding changes on BACK when editing
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Needs Second Approval

#14710 23.10.1
  build.gradle
Labels: Pending Merge

#14716 tests: re-enable CardTemplatePreviewerTest
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
Labels: Needs Review

#14718 tests: add - 'Read Text' + Note Editor Preview
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
Labels: Priority-Low, Pending Merge

#14720 dev: add IDEA project icon
  .gitignore
  .idea/icon.svg
Labels: Priority-Low, Needs Second Approval, Dev

#14725 Preferences: add plurals for learn ahead/timebox
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Labels: Needs Review, Strings

#14728 chore: inline note.model() => note.notetype
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/NoteWithColTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
Labels: Needs Second Approval

#14657 fix permission margin
  AnkiDroid/src/main/res/layout/permission_item.xml
Labels: Pending Merge, squash-merge

#14739 feat: use material toolbar at manage space activity
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceActivity.kt
  AnkiDroid/src/main/res/layout/activity_manage_space.xml
Labels: Needs Second Approval

#14754 Fix ExportReadyDialog not being restored from notification
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt
Labels: Needs Second Approval

#14738 add redo button and control
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
  AnkiDroid/src/main/res/drawable/ic_redo.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Pending Merge, Strings, squash-merge

#14757 chore: remove ACTION_PROCESS_TEXT compat
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Needs Second Approval

#14765 Use ServiceCompat.stopForeground
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
Labels: Needs Second Approval, squash-merge

#14763 Dependency updates 20231117
  .github/dependabot.yml
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
  build.gradle
Labels: Pending Merge, squash-merge

#14721 tests: Previewer Ordinal handling: failing tests
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
Labels: Needs Review

#14770 fix custom study session is empty on "Limit to particular tags"
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Needs Second Approval, squash-merge, New contributor

#14775 feat: allow printing or exporting stats
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/res/drawable/ic_export_file.xml
  AnkiDroid/src/main/res/menu/statistics.xml
Labels: Pending Merge

#14774 Resolved weak warnings: converted objects into data objects
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportType.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/AsyncDialogs.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt
Labels: Needs Second Approval, squash-merge

#14761 8602 start activity for result new api
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#14772 Fix card not being suspended after first being buried
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#14783 build(deps): bump backend to 0.1.29-anki23.10.1
  build.gradle
Labels: Pending Merge

#14782 Resolved warnings: redundant constructs
  AnkiDroid/src/main/java/androidx/drawerlayout/widget/ClosableDrawerLayout.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt
  AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
  AnkiDroid/src/main/java/com/ichi2/ui/TextInputEditField.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.kt
Labels: Needs Second Approval

#14741 refactor: remove appIntro dependency
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/res/layout/introduction_activity.xml
Labels: Needs Second Approval

#14727 fix: timebox showing immediately
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#14779 Add implementation for "stopTimerOnAnswer" deck configuration option
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#14786 [Clean Up] : function naming conversion Warning
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
Labels: Needs Second Approval, squash-merge, New contributor

#11557 upload, build, download and update translations to/from Crowdin using js client api
  .github/workflows/sync_translations.yml
  tools/localization/.eslintrc.js
  tools/localization/.gitignore
  tools/localization/.prettierignore
  tools/localization/.prettierrc
  tools/localization/README.md
  tools/localization/jest.config.js
  tools/localization/package.json
  tools/localization/src/constants.ts
  tools/localization/src/download.ts
  tools/localization/src/index.ts
  tools/localization/src/update.ts
  tools/localization/src/upload.ts
  tools/localization/tsconfig.json
  tools/localization/yarn.lock
Labels: Priority-High, Review High Priority, Keep Open, Dev, squash-merge

#14697 NF: more timbers for getting data from http server
  AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
Labels: Pending Merge

#14805 use backgroundTint to apply color
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml
Labels: Pending Merge

#14807 chore: remove old crowdin v1 implementation
  tools/find-broken-strings-variables.sh
  tools/manage-crowdin.sh
  tools/update-localizations.py
Labels: Pending Merge

#14755 browser menu plural update
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/res/drawable/ic_pause_circle_filled.xml
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Needs Second Approval, Strings

#14815 regression tests: corrupt 'curDeck' value (Issue 14096)
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt
Labels: Priority-Low, Needs Review, Test process

#14811 refactor: extract SortType
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Review

#14820 refactor: Extract 'CardStateFilter'
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/CardStateFilter.kt
  AnkiDroid/src/main/res/layout/tags_dialog.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Labels: Needs Review

#14822 fix(CardBrowser): `toggleMark`: mark all if mixed selection of marked/unmarked
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Review

#14818 8602 - Finished fully migrating DeckPicker over to using registerForActivityResults API instead of the deprecated startActivityForResult
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Labels: Needs Second Approval, squash-merge

#14816 fix: Loading the deck count and toolbar takes more time if internet is enabled
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Labels: Needs Second Approval, Blocked by dependency

#14808 [Clean Up] : property naming conversion Warning
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
Labels: Needs Second Approval, squash-merge

#14836 fix: API crashes with UnsatisfiedLinkError
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
Labels: API, Pending Merge

#14840 fix: suspend all cards if mixed selection
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Review

#14848 refactor: remove unused method
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Priority-Low, Needs Review

#14855 Dependency updates 20231130
  AnkiDroid/build.gradle
  AnkiDroid/jacoco.gradle
  AnkiDroid/robolectricDownloader.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Pending Merge, squash-merge
