Repository ankidroid/Anki-Android, pull requests merged in 2023-09, with the labels that each got.

#14368 #14258 Fixed this issue.
  AnkiDroid/build.gradle
  api/build.gradle
Labels: Needs Second Approval, squash-merge

#14325 audio recording: hide 'contents' label if empty
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
Labels: Needs Second Approval

#14369 Remove answer recommended commands
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Pending Merge, Strings

#14208 Make the zero counts dimmer in black and dark themes
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
Labels: Needs Second Approval

#14398 build(deps): bump acra_version from 5.11.1 to 5.11.2
  build.gradle
Labels: Pending Merge

#14388 rename controls and add categories
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceTestUtils.kt
Labels: Pending Merge, Strings

#14421 Mark CardBrowserTest.flagsAreShownInBigDecksTest as flacky
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Priority-Low, Dev

#14422 Show type answer field in reviewer when answer buttons are hidden
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Second Approval

#14360 Fix note editor deck selection related issues
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval

#14140 Switch to use dokka for generating documentation in api module
  api/build.gradle
  api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
  build.gradle
Labels: Needs Second Approval, Dev

#14071 set horizontalPadding to HelpDialog Items
  AnkiDroid/src/main/res/layout/material_dialog_list_item.xml
Labels: Needs Second Approval

#14098 nf: remove setupSubMenu and SubMenuProvider
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Priority-Low, Needs Second Approval, cleanup

#14387 Update downloaded robolectric versions
  AnkiDroid/robolectricDownloader.gradle
Labels: New contributor

#14237 feature : minimal screen touch time to reveal answer
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_accessibility.xml
Labels: Pending Merge, Strings

#14408 Successfully showing snackbar above FAB in the deck picker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/FabBehavior.kt
  AnkiDroid/src/main/res/layout/floating_add_button.xml
Labels: Pending Merge, squash-merge

#14337 Tests for inverse animation
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Pending Merge, New contributor

#14450 Removes unnecessary API <= 23 checks
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Needs Second Approval, New contributor

#14466 [Clean up]: Fix Kotlin Function name conventions
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
  AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
Labels: Needs Second Approval, New contributor

#14468 fix: don't invalidate card if device doesn't have a browser
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#14474 Detect invalid capital letters
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetectorTest.kt
Labels: Pending Merge, New contributor

#14500 url loading from assets
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Needs Second Approval
