Repository ankidroid/Anki-Android, pull requests merged in 2023-04, with the labels that each got.

#13536 Kotlincleanup DeckOptionsActivity
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
Labels: Needs Second Approval, New contributor

#13404 Fix leech snackbar overlapping answer buttons
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
Labels: Needs Second Approval, New contributor

#13544 Fix IDE Warnings: Make eligible functions and fields private
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Pending Merge, New contributor

#13533 release: include universal build for each flavor in github releases
  tools/release.sh
Labels: Review High Priority, Dev, Scoped storage

#13545 Make all colors available to the JS API consumers
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Review

#13553 fix(deps): bump underlying backend to use anki 2.1.61 from upstream
  build.gradle
Labels: Pending Merge, dependencies

#13558 Replaced toast with Snackbar in NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#13538 Replaced Toast with Snackbar in CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Needs Second Approval

#13473 Used AlertDialog instead of MaterialDialog in NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml
  AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
Labels: Needs Second Approval, squash-merge

#13381 fix: Removed done button and bottom separator in Intro screen
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/res/layout/introduction_layout.xml
Labels: Needs Second Approval, squash-merge

#13575 Fix resolveActivity deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Labels: Needs Second Approval

#13578 fix: crash on Check Media
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13585 fix: Added product flavor to debug info
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Labels: Needs Second Approval

#13532 fixes the horizontal logged in UI
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
Labels: Needs Second Approval, squash-merge

#13525 Replace MaterialDialog with AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Labels: Pending Merge, squash-merge, New contributor

#13548 Replace MaterialDialog with AlertDialog in SimpleMessageDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Labels: Needs Author Reply, Needs Second Approval, squash-merge

#13587 fix: Changed title and action names of cancel share deck download dialog
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
Labels: Needs Author Reply

#13613 revert jacoco from 0.8.9 to 0.8.8 - macOS runner cannot find it
  AnkiDroid/jacoco.gradle
Labels: Review High Priority, Pending Merge

#13582 Crash fix due to `EditTextPreference` search field in CustomStudyDeck
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Review High Priority, Needs Second Approval

#13630 Fix "Access denied" errors after upgrading from 2.15.6
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
Labels: Review High Priority, Needs Second Approval, squash-merge, Scoped storage

#13643 build: update `targetSdkVersion` to 31
  .github/workflows/tests_emulator.yml
  AnkiDroid/build.gradle
  api/build.gradle
Labels: Review High Priority, Needs Second Approval

#13635 Find Key Shortcut for Card Browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval, squash-merge

#13614 Fix: storage migration shown on < API 30 & Amazon Builds
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13650 Dependency updates 20230421
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge

#13655 Changed Material Dialog with Alert Dialog for ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Labels: Needs Author Reply, Needs Second Approval

#13646 Use a not-cloud icon for suggesting backup if no sync
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
  AnkiDroid/src/main/res/drawable/ic_backup_restore.xml
Labels: Needs Second Approval

#13657 fix: Storage Migration not being offered
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
Labels: Review High Priority

#13621 Replace MaterialDialog with AlertDialog in SharedDecksDownloadFragment class
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
Labels: Needs Second Approval, squash-merge, New contributor

#13652 Fix: `StorageAccessException` shown after reinstall (API 30, non-Play Store build)
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13660 fixup: MigrationService: Progress is incorrect after service restart
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
Labels: Pending Merge

#13670 chore: fix typo [MigrateEssentialFiles]
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt
Labels: Priority-Low, Needs Review

#13661 fix: StackOverflowException in androidTest
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13664 Changed Material Dialog with Alert Dialog for CardSideSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
Labels: Needs Second Approval

#13673 NF: refactor close
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Needs Second Approval

#13636 added a Help button in the notification if the migration fails
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings, Scoped storage

#13651 Add dialogs for successful & failed storage migration
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings, squash-merge

#13642 Fix Warnings in ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
Labels: Pending Merge, squash-merge, New contributor

#13691 Fix issues with 'Shared Deck Download'
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
Labels: Review High Priority, Needs Second Approval

#13706 chore: remove 'MEDIA_CODEC_LIST' from crash reports
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
Labels: Needs Review

#13710 fix: Make the settings screen use a Coordinator layout
  AnkiDroid/src/main/res/layout/preferences.xml
Labels: Pending Merge

#13703 fix: storage permission checks on 'full' builds & broken Dialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
Labels: Review High Priority, Pending Merge

#13711 dev: better document user crash reports
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
Labels: Needs Review

#13685 docs: Android Tests: fail if 'All files' is needed and not granted
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/GrantPermissions.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/GrantAllFilesAccessRule.kt
Labels: Priority-Low, Needs Review

#13718 fix: crash if exporting deck name containing "'"
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
Labels: Review High Priority

#13713 fix: NullPointerException on `isLegacyStorage()` call
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAndroidTest.kt
Labels: Needs Second Approval

#13715 fix: not being open to open the login screen from settings on a parallel build
  AnkiDroid/build.gradle
Labels: Needs Second Approval

#13721 Dependency updates 20230425
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge

#13731 fix: crash importing decks on SDK 24 and below
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.kt
Labels: Review High Priority

#13732 fix: moving to note type with fewer sticky fields
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Review High Priority

#13730 Use `toList` first on `mAllTags` for collections tag
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
Labels: Review High Priority, Needs Second Approval

#13735 fix: nullability issues in FileUtils
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt
Labels: Pending Merge

#13741 DeckPickerMenuOption Bug fix
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
Labels: Needs Second Approval, New contributor

#13747 fix: automated sync leads to "collection not open"
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Labels: Review High Priority, Needs Second Approval

#13754 Resolve TODOs regarding ongoing migration button title
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/menu/deck_picker.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#13765 Setting the namespace via a source
  AnkiDroid/build.gradle
Labels: Needs Second Approval

#13769 fix: Custom study dialog language bug
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Needs Second Approval
