Repository ankidroid/Anki-Android, pull requests merged in 2023-10, with the labels that each got.

#14497 Remove television reviewer menu
  AnkiDroid/src/main/res/menu-television/reviewer.xml
Labels: Needs Review

#14493 Stop sound when card/note is buried or suspended
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Needs Second Approval

#14481 "lose current input" even when there is no input solved (#13821)
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, New contributor

#14509 Anchored SnackBar on top of NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Needs Author Reply, Needs Second Approval, squash-merge

#14521 [Clean up]: Fix Android studio warnings
  AnkiDroid/src/main/java/com/ichi2/anki/DatabaseCheck.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
  AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ExifUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
  api/src/main/java/com/ichi2/anki/api/Utils.kt
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge, New contributor

#14534 fix: show snackbar above toolbar if setting hasn't been set
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Review

#14531 Migrate lint-rules build file to kotlin dsl
  lint-rules/build.gradle
  lint-rules/build.gradle.kts
Labels: Priority-Low, Pending Merge, Dev, squash-merge

#14489 Handle the PR already existing when running the sync_translations workflow
  .github/workflows/sync_translations.yml
Labels: Priority-Low, Dev

#14452 Improves visibility of flags
  AnkiDroid/src/main/res/values/colors.xml
Labels: Needs Second Approval, hacktoberfest-accepted, squash-merge

#14542 Migrate api module's build file to kotlin dsl
  api/build.gradle
  api/build.gradle.kts
Labels: Priority-Low, Dev, squash-merge

#14543 Adds nothing to undo message
  AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
Labels: Needs Second Approval

#14512 fix- Can't disable "Show remaining" and "Show button time"
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
Labels: Needs Author Reply, Needs Second Approval, hacktoberfest-accepted, squash-merge, New contributor

#14545 fix: don't crash when replacing controls
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Labels: Needs Review

#14556 Bump compileSdk to 34, handle new deprecations
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ReflectionUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
  api/build.gradle.kts
Labels: Review High Priority, Needs Second Approval, dependencies, squash-merge

#14563 Dependency updates 20231019
  .github/dependabot.yml
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ReflectionUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
  api/build.gradle.kts
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  lint-release.xml
Labels: Pending Merge, squash-merge

#14533 Add same card cloze button
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/res/drawable/ic_cloze_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_cloze_new_card.xml
  AnkiDroid/src/main/res/drawable/ic_cloze_same_card.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/vector_source/cloze_icon.svg
Labels: Anki Ecosystem Compatibility, Pending Merge, Strings

#14559 wrap content tags and cards button's height
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Pending Merge

#14130 feat: Permission screen
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsRequestResults.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/Full30and31PermissionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionItem.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsUntil29Fragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/TiramisuPermissionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
  AnkiDroid/src/main/res/color/text_color_dark.xml
  AnkiDroid/src/main/res/layout/permission_item.xml
  AnkiDroid/src/main/res/layout/permissions_activity.xml
  AnkiDroid/src/main/res/layout/permissions_full_30_and_31.xml
  AnkiDroid/src/main/res/layout/permissions_tiramisu.xml
  AnkiDroid/src/main/res/layout/permissions_until_29.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge, Strings, squash-merge

#14575 fix: set icon colors to colorControlNormal
  AnkiDroid/src/main/res/drawable/ic_backup_restore.xml
  AnkiDroid/src/main/res/drawable/ic_baseline_backup_24.xml
Labels: Needs Second Approval

#14565 Issue #13411-ShowSnackbarInsteadOfToast,
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
Labels: Needs Second Approval, hacktoberfest-accepted, New contributor

#14578 Fix misaligned masks in image occlusion
  AnkiDroid/src/main/assets/card_template.html
Labels: Needs Second Approval

#14581 Remove the link to Huawei AppGallery from README.md
  README.md
  docs/graphics/logos/huawei-badge.png
Labels: Needs Second Approval

#13853 NF: `use` instead of `close`
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Labels: Priority-Low, Needs Second Approval, cleanup

#14577 Fix backgrounding freezing app until sync finishes
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Needs Second Approval, squash-merge

#14587 Ensure card timer started
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
Labels: Needs Second Approval

#14595 Dependency updates 20231026 / unblock releases
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/SystemContextMenu.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
  build.gradle
Labels: Review High Priority, Needs Review

#14594 refactor: remove filter bottom sheet
  AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
  AnkiDroid/src/main/res/drawable/filter_sheet_opened_list_icon.xml
  AnkiDroid/src/main/res/drawable/filter_sheet_unopened_list_icon.xml
  AnkiDroid/src/main/res/drawable/ic_filter_list.xml
  AnkiDroid/src/main/res/drawable/label_icon_flags.xml
  AnkiDroid/src/main/res/drawable/rounded_bottom_sheet.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
  AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml
  AnkiDroid/src/main/res/layout/filter_list_flag_item_layout.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Needs Second Approval

#14607 review count in deck picker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval, squash-merge

#14618 chore: remove AnkiDroid main module
  .gitignore
  .idea/modules.xml
  .idea/modules/AnkiDroid/Anki-Android.AnkiDroid.main.iml
Labels: Dev

#14626 Dependency updates 20231031
  AnkiDroid/robolectricDownloader.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
  AnkiDroid/src/test/resources/robolectric.properties
  build.gradle
Labels: Pending Merge, squash-merge

#14613 Remove estimated time
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/test/java/com/ichi2/utils/UtilsIntegrationTest.kt
Labels: Pending Merge, Strings, squash-merge
