Repository ankidroid/Anki-Android, pull requests merged in 2023-07, with the labels that each got.

#14041 Set translate icon tint color to blue
  AnkiDroid/src/main/res/drawable/ic_language_black_24dp.xml
Labels: Needs Second Approval

#14037 Replaced MaterialDialog with AlertDialog in ImportDialog.
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
Labels: Needs Second Approval

#13999 Replace MaterialDialog with Alertdialog for ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Labels: Pending Merge, squash-merge, New contributor

#14058 Dependency updates 20230630
  AnkiDroid/build.gradle
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  api/build.gradle
  build.gradle
  gradle.properties
Labels: Pending Merge

#14062 Migrate ConfirmDeleteDeck to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
Labels: Pending Merge, squash-merge

#14064 Migrate MediaCheck to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
Labels: Pending Merge

#14061 Migrate LocaleSelectionDialog to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
Labels: Pending Merge

#14067 fix: avoid concurrent change exception when removing card from queue
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
Labels: Review High Priority

#14059 Rename the strings related to "Collection exported successfully" to the ones for "Export ready"
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings, squash-merge

#14074 fix: make bqfmt and bafmt not crash if not found
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Pending Merge

#14065 Migrate SyncError to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Labels: Needs Second Approval

#14095 Remove animation of DeckPicker FAB when selecting menu item
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#14097 Remove chess notation support
  AnkiDroid/src/main/assets/chess.css
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/hooks/ChessFilter.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.kt
Labels: Pending Merge, Strings

#14005 ignore local .log files in git commit
  .gitignore
Labels: Needs Second Approval

#13844 WhiteBoard Editor item tint color to white
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
Labels: Needs Second Approval

#14124 Use wake lock while migrating storage
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Labels: Review High Priority, Pending Merge

#14126 revert #14061
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
Labels: Needs Second Approval

#14135 fix: Simplify 'Dont ask again string' in metered connection dialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#14136 Add icons to Study, Add, and Card Browser shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/res/drawable/add_shortcut.xml
  AnkiDroid/src/main/res/drawable/browse_shortcut.xml
  AnkiDroid/src/main/res/drawable/review_shortcut.xml
Labels: Needs Second Approval, New contributor
