Repository ankidroid/Anki-Android, pull requests merged in 2023-08, with the labels that each got.

#14164 fix: Use <i> instead of <em>
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Needs Second Approval, New contributor

#14168 Improved CardBrowserMySearchesDialog
  AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml
Labels: Needs Second Approval

#14182 Added gesture for rescheduling
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Needs Second Approval, squash-merge

#14195 Fix crash when exporting a deck with a name containing a path separator
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
Labels: Pending Merge, squash-merge

#14203 fix preferences in single line
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
Labels: Needs Second Approval

#14218 fixed README.md file
  README.md
Labels: New contributor

#14236 Enable third-party cookies in the webview
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Anki Ecosystem Compatibility, Pending Merge

#14105 Changed Material Dialog with Alert Dialog for DeckPickerNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
Labels: Needs Second Approval

#14249 fix: resolution of 'add_shortcut' launcher icon
  AnkiDroid/src/main/res/drawable/add_shortcut.xml
Labels: Needs Review

#14181 fix: Removed beolingus pronounce feature
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/language/LanguageListerBase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/language/LanguageListerBeolingus.kt
  AnkiDroid/src/main/res/layout/activity_load_pronounciation.xml
  AnkiDroid/src/main/res/layout/progress_bar_layout.xml
  AnkiDroid/src/main/res/menu/activity_load_pronounciation.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge, Strings, squash-merge

#14174 fix: Remove clear field option from attachment button
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/drawable/ic_popup_menu_item_clear.xml
  AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge, Strings, squash-merge

#14234 fix: 'Sync required' indicator doesn't go away
  AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
Labels: Review High Priority

#14233 fix: use supported JDK with "Update Gradle Wrapper"
  .github/workflows/update-gradle-wrapper.yml
Labels: Needs Second Approval

#14231 fix: unexpected reviewer highlights with keyboard
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/res/values/disable-fullscreen-keyboard-highlight.xml
Labels: Needs Second Approval

#14173 fix: error at advanced settings
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
Labels: Needs Second Approval

#14162 fix: remove camera permission
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
Labels: Needs Second Approval, Blocked by dependency

#14104 Highlighted Correct Deck
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#14185 Remove DuplicateTextInPreferencesXml lint
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXml.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
Labels: Priority-Low, cleanup

#14257 build: update `targetSdkVersion` to 32
  AnkiDroid/build.gradle
  AnkiDroid/robolectricDownloader.gradle
  api/build.gradle
Labels: Pending Merge

#14264 Use FragmentLifecycleCallbacks to log fragments lifecycles
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
Labels: Needs Second Approval

#14268 shortcut icons updated to be consistent with the UI
  AnkiDroid/src/main/res/drawable/add_shortcut.xml
  AnkiDroid/src/main/res/drawable/browse_shortcut.xml
  AnkiDroid/src/main/res/drawable/review_shortcut.xml
Labels: Pending Merge

#14284 remove scroll setting
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Pending Merge, Strings

#14261 fix: requesting no permissions succeeds
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
  AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsRequestResults.kt
Labels: Review High Priority, Needs Second Approval

#14290 fix: restore scroll position after editing card
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#14291 #13283 Resolve @NeedsTest Issues for flagToDisplay in Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
Labels: Needs Second Approval, squash-merge, New contributor

#14198 Fix importing a shared deck by providing a dedicated download path
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/res/layout/activity_shared_decks.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/xml/filepaths.xml
Labels: Needs Second Approval, Strings

#14296 fix: 'playsound' should replay the sound
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
Labels: Pending Merge

#14304 chore: exclude non-`values` translation files in Android Studio Index/Search
  .gitignore
  .idea/modules.xml
  .idea/modules/AnkiDroid/Anki-Android.AnkiDroid.main.iml
Labels: Needs Second Approval

#14305 Fix typo errors
  .idea/dictionaries/Cath.xml
  AnkiDroid/src/main/assets/scripts/card.js
Labels: Needs Second Approval, New contributor

#14313 fix: 'rebuild' did not update the deck UI
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
Labels: Needs Second Approval

#14317 tests: mark flaky test
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Pending Merge

#14321 dev: add git commit hash to debug info
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Labels: Needs Second Approval

#14315 Add digital eraser support in the Whiteboard
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Needs Second Approval, squash-merge

#14100 Changed Material Dialog with Alert Dialog for CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Labels: Pending Merge, Blocked by dependency

#14365 Dependency updates 20220831
  AnkiDroid/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge
