Repository ankidroid/Anki-Android, pull requests merged in 2023-02, with the labels that each got.

#13190 Fix a typo of the filenames of the notification star icon
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/res/drawable/ic_star_notify.xml
  docs/graphics/src/ic_star_notify.svg
Labels: Pending Merge

#13195 build(deps): revert apache commons-compress to API21-compatible version
  AnkiDroid/build.gradle
Labels: Priority-High, Bug, Reproduced, Needs Second Approval

#13160 Fixed Snackbar not disappearing after changing the deck path in CardBrowser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval, squash-merge, New contributor

#13198 Dependency updates 20220205
  AnkiDroid/build.gradle
  build.gradle
  lint-release.xml
Labels: squash-merge

#13171 fix(ScopedStorage): destination has empty file
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13176 Enable "None" in the gesture list to be translated
  AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, Strings

#12954 Fix manage space activity on parallel and debug builds
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Needs Author Reply, Pending Merge

#13204 Default path to a `files/` subfolder
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13056 Update backend version to 2.1.57
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/BackendSync.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.kt
  build.gradle
  tools/setup-anki-backend.sh
Labels: Strings, squash-merge

#13208 Dependency updates 20230206
  AnkiDroid/build.gradle
  build.gradle
  lint-rules/build.gradle
Labels: Pending Merge

#13074 fixed landscape screen issue with intro screen
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/res/layout-land/introduction_layout.xml
Labels: Needs Second Approval

#13177 Fixed the whiteboard-editor-bug
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Author Reply, Needs Second Approval, squash-merge

#13253 GitHub: Implement Bug Reporting Form
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Priority-Low, Pending Merge

#13260 Revert "Scheduler should be reloaded on full sync"
  AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Labels: Needs Second Approval

#13257 Changed contrast as per given in issue 12476
  AnkiDroid/src/main/res/values/theme_black.xml
Labels: Needs Second Approval, New contributor

#13268 lint: enable 'MonochromeLauncherIcon'
  lint-release.xml
Labels: Priority-Low, Needs Review

#13248 Added function for database error
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Blocked by dependency, Strings, squash-merge

#13251 chore: improve .isActionButton
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ToolbarUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Labels: Priority-Low, Pending Merge

#13138 [KotlinCleanup] - TemporaryModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
Labels: Priority-Low, Pending Merge, cleanup, squash-merge, New contributor

#13267 refactor: extract 'isRobolectric'
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
Labels: Needs Second Approval

#13281 Fix Test Flake (after permission dialog removal)
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Labels: Needs Second Approval, Scoped storage

#13284 fix: AddNoteWidget - wrong method called
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
Labels: Priority-Low, Needs Second Approval

#13280 Dependency updates 20220216
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.kt
  api/build.gradle
  build.gradle
  lint-rules/build.gradle
Labels: Pending Merge, squash-merge

#13228 Fix the status of sticky fields after syncing with AnkiWeb
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, squash-merge, New contributor

#13286 replace `assertThrows` with `assertFailsWith`
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTestAnnotationTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/exception/RetryableExceptionTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAnkiDroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContextTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveConflictedFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserDataJvmTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDeleteFileTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/CreateDirectoriesTest.kt
  AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
  AnkiDroid/src/test/java/com/ichi2/exceptions/AggregateExceptionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ComputationTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.kt
Labels: Priority-Low, Needs Second Approval

#13241 added check which rejects new notes with empty first field
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#13073 Removed Snackbar
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Needs Second Approval, Strings, squash-merge

#13235 Make the notification icon black when its background color is light
  AnkiDroid/src/main/res/drawable/ic_star_notify.xml
Labels: Needs Second Approval

#13287 Update to 2.1.58 backend
  build.gradle
Labels: Pending Merge

#13109 [KotlinCleanup] NoteEditorTabOrderTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
Labels: Priority-Low, cleanup

#13205 Solve `onPreferenceStartFragment` warning
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Priority-Low, Needs Second Approval

#12772 open collective link opening fix
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
Labels: Pending Merge

#13275 Use manually translated language names instead of getting them from java libraries
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/LocaleLinting.kt
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt
Labels: Pending Merge

#13297 ci: temporarily remove `creyD/prettier_action`
  .github/workflows/lint.yml
Labels: Review High Priority

#13290 remove JSON tests
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Pending Merge

#13078 Removed forceful plural use with correct singular/plural form
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval

#13016 Kotlin cleanup of SchedV2Test.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
Labels: Priority-Low, Needs Second Approval, cleanup

#13301 Revert "remove JSON tests"
  AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Labels: Review High Priority, Pending Merge

#13302 NF: Remove some unused files
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingTodayProto.kt
Labels: Priority-Low, Needs Review, cleanup

#13295 Make collection calls async on Preferences
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/BackendNotSupportedException.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
Labels: Pending Merge

#13291 tests: fix emulator tests on API 30
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/GrantPermissions.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13110 Fix resolveService deprecation
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
  AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Labels: Needs Second Approval

#13308 fix readSerializable deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval, squash-merge

#13307 Fix readList deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval

#13311 build(deps): Bump prettier_action to 4.3
  .github/workflows/lint.yml
Labels: Needs Review

#13313 NF: remove trimRight method
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
Labels: Needs Review

#13306 Remove @NeedsTest from a file
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
Labels: Needs Second Approval

#13249 Improve accessibility and styling of note editor toolbar
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
  AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
Labels: Pending Merge, squash-merge

#13318 build(ci): mark 'drawerConflictsIfDown' as flaky
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Needs Review

#13293 Only offer to migrate storage if logged in
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#13322 build(ci): Fix stale messages
  .github/workflows/stale.yml
Labels: Needs Review

#12978 Added Add-Card Option in DeckPickerContextMenu
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Labels: Needs Second Approval

#12991 Stop handling language changes manually
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ReflectionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt
Labels: Pending Merge, squash-merge

#13324 flaky test: drawerConflictsIfUp
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Needs Second Approval

#13326 Use AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Labels: Needs Second Approval

#13310 fix getParcelable deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval

#13327 Changed Var to Val in AbstractDeckTreeNode.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.kt
Labels: Priority-Low, Pending Merge, cleanup, New contributor

#13317 IDE lint: DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceToDowngradeDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Priority-Low, Pending Merge, Strings

#13328 test: mark drawerConflict tests as flaky
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Needs Review

#13300 Storage Migration: Notification to handle failure
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
  AnkiDroid/src/main/java/com/ichi2/exceptions/AggregateException.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
Labels: Review High Priority, Pending Merge, Scoped storage

#13130 added sync disabled icon to be shown during migration
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/drawable/ic_sync_lock_24.xml
Labels: Needs Second Approval, Scoped storage

#12506 Fixed the navigation of filtered deck options activity
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval, squash-merge

#13337 lint: fix 'errors' in build.gradle
  build.gradle
Labels: Priority-Low, Needs Review

#13342 Replaces usages of MaterialDialog with AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
Labels: Needs Author Reply

#13344 test: mark flaky windows tests
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Needs Review

#13343 Replaces usages of MaterialDialog with AlertDialog for BasicImageFieldController.kt,ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Needs Second Approval

#13335 updated sync icon and migration progress
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/drawable/ic_migration_progress.xml
  AnkiDroid/src/main/res/drawable/ic_sync_lock_24.xml
  AnkiDroid/src/main/res/layout/migration_progress_menu_layout.xml
  AnkiDroid/src/main/res/menu/deck_picker.xml
Labels: Review High Priority, Needs Second Approval, squash-merge, Scoped storage

#13321 update CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Priority-Low, Pending Merge, cleanup, squash-merge

#13329 Disable some advanced settings if migrating storage
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Review High Priority, Needs Second Approval, Strings, Scoped storage

#13347 build(ci): reduce PR stale timeout to 21 days
  .github/workflows/stale.yml
Labels: Priority-Low, Needs Second Approval, Dev, squash-merge

#12961 Make "Undo" item's title for whiteboard mode
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Needs Second Approval, Strings

#13361 added `refreshState` call as soon as migration is started
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13338 Changed Material Dialog with Alert Dialog for DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval, squash-merge

#13364 Dependency updates 20220228
  AnkiDroid/build.gradle
  api/build.gradle
  build.gradle
Labels: Pending Merge, squash-merge

#13358 remove unused SyncStatus: 'INCONCLUSIVE'
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Labels: Needs Second Approval

#13366 fix(deps): bump anki upstream to 2.1.60
  build.gradle
Labels: Pending Merge
