Repository ankidroid/Anki-Android, pull requests merged in 2023-01, with the labels that each got.

#13062 [KotlinCleanup] MathFunctionAtom
  AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/MathFunctionAtom.kt
Labels: Priority-Low, Pending Merge, cleanup

#13052 Fix compress format and extension format.
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Needs Second Approval

#13039 TextUtils.join and .isEmpty changed to kotlin methods
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Model.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MethodLogger.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Pending Merge, cleanup, squash-merge, New contributor

#13071 Updated strings from Crowdin 20230106
  AnkiDroid/src/main/res/values-af/01-core.xml
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/04-network.xml
  AnkiDroid/src/main/res/values-ar/09-backup.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rAR/04-network.xml
  AnkiDroid/src/main/res/values-es-rAR/09-backup.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rES/04-network.xml
  AnkiDroid/src/main/res/values-es-rES/09-backup.xml
  AnkiDroid/src/main/res/values-es-rES/10-preferences.xml
  AnkiDroid/src/main/res/values-fil/01-core.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/04-network.xml
  AnkiDroid/src/main/res/values-fr/09-backup.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/04-network.xml
  AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pl/09-backup.xml
  AnkiDroid/src/main/res/values-pl/10-preferences.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-ur/05-feedback.xml
  AnkiDroid/src/main/res/values-uz/01-core.xml
  AnkiDroid/src/main/res/values-vi/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
  AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rTW/04-network.xml
  AnkiDroid/src/main/res/values-zh-rTW/06-statistics.xml
  AnkiDroid/src/main/res/values-zh-rTW/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-zh-rTW/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rTW/17-model-manager.xml
  AnkiDroid/src/main/res/values-zh-rTW/18-standard-models.xml
  docs/marketing/localized_description/marketdescription-ar.txt
  docs/marketing/localized_description/marketdescription-zh-TW.txt
Labels: Needs Review

#12925 Disable shortcut if corresponding deck is deleted
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#13084 Ask to keep data when uninstalling
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Review High Priority, Needs Second Approval, Scoped storage

#13049 update: unit test in DuplicateTextInPreferencesXmlTest.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
Labels: Needs Author Reply, Needs Second Approval

#13114 Enable creating a PR when running the Crowdin translation sync workflow
  .github/workflows/sync_translations.yml
Labels: Pending Merge

#13112 Fix readSparseArray deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Needs Second Approval

#13103 added version code suffix
  AnkiDroid/build.gradle
Labels: Pending Merge, squash-merge

#13113 Fix getParcelableArrayList deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Labels: Pending Merge

#13122 Replace the parallel build scripts with gradle configs
  AnkiDroid/build.gradle
  AnkiDroid/src/main/res/values/constants.xml
  tools/parallel-package-name.sh
  tools/parallel-package-release.sh
Labels: Pending Merge

#13096 Moved recording buttons outside the scroll view as it should always be on the screen.
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
  AnkiDroid/src/main/res/layout/multimedia_edit_field_activity.xml
Labels: Pending Merge

#13124 Fix the command title for "Bury card" action
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
Labels: Needs Second Approval

#12933 Add option to sync media only on unmetered connections
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_sync.xml
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
Labels: Pending Merge, Strings, squash-merge

#13137 STOR-07: Dont show the essential migration snackbar if it was too short
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval, Scoped storage

#13136 Add a BuildConfig option to use legacy storage
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
Labels: Needs Second Approval, Scoped storage

#13055 implement themed icon on Android 13 or higher
  AnkiDroid/src/main/res/drawable-v24/ic_launcher_foreground.xml
  AnkiDroid/src/main/res/drawable-v24/ic_launcher_monochrome.xml
  AnkiDroid/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  AnkiDroid/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: Pending Merge, squash-merge, New contributor

#13099 Line Break in sync message corrected
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge, squash-merge

#13117 [KotlinCleanup] TagsList
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
Labels: Priority-Low, Needs Second Approval, cleanup
