Repository ankidroid/Anki-Android, pull requests merged in 2024-02, with the labels that each got.

#15382 fix: emulator tests (🎉)
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  testlib/src/main/java/com/ichi2/testutils/IgnoreFlakyTestsInCIRule.kt
Labels: Pending Merge

#15388 test(ci, unit): configure windows pagefile correctly
  .github/workflows/tests_unit.yml
Labels: Pending Merge, CI

#15389 Fix browser displayed deck when selected from DeckPicker's context menu
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#15404 fix: crash changing note type
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15410 fix: media not found message
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
Labels: Pending Merge

#15407 fix Crash on opening Previewer in a large deck
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge

#15414 fix : remove `Fonts` from Appearance summary
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings

#15418 feat(whiteboard): S Pen eraser on OneUI 6
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Needs Review

#15419 disable gestures on CardTemplatePreviewer
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
Labels: Needs Review

#15420 previewers: improve nav bar color
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
Labels: Needs Review

#15393 fix: Image Occlusion webView being recreated in orientation changes
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge

#15432 fix snackbar dismiss with FAB
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Needs Second Approval

#15297 fix some bugs in the new previewer + some refactors
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
Labels: Pending Merge, squash-merge

#15439 Dependency updates 20240206
  AnkiDroid/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#15431 Deck SelectionDialog now uses Alert Dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Pending Merge, squash-merge

#15456 Make undo icon gray when the icon is unavailable
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#15462 docs: Google Play Storage restrictions
  AnkiDroid/src/play/AndroidManifest.xml
Labels: Needs Second Approval

#15461 Fix: IllegalArgumentException on with progress dialog dimiss
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#15436 chore: use AlertDialog.Builder.create()
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
Labels: Pending Merge, cleanup

#15467 fix: 'auto focus type in answer' default
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
Labels: Pending Merge

#15376 Removed the Material Dialog Box and Added Alert Box from DeckPickerAnalyticsOption
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt
Labels: Needs Second Approval, squash-merge

#15454 chore: allow translation of SearchPreference
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/20-search-preference.xml
  AnkiDroid/src/main/res/xml/preference_headers.xml
  tools/localization/src/constants.ts
Labels: Pending Merge, Strings

#15477 cleanup: solve some rust cleanups
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Long.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Priority-Low, Needs Second Approval, cleanup, squash-merge

#15479 fix(CardBrowser): selecting a deck twice
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#15489 start ReadText deprecation process
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
Labels: Pending Merge, Strings

#15495 fix: legacy TTS should stop on card flip
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
Labels: Review High Priority, Needs Second Approval

#15379 fix: DeckPicker onSaveInstanceState checks if fab is visible if not makes it visible
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge, squash-merge, New contributor

#15508 Dependency updates 20240315
  AnkiDroid/build.gradle
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#15293 enhancement: show copied to clipboard toast for API ≤ 32
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#15510 chore: ignore 'CardBrowser Scroll Issue 8821'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#15503 Deck Options: add unconditional 'back' confirmation and duplicate save icon
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Pending Merge

#15527 fix: unable to edit note in the Reviewer
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Review High Priority

#15530 fix: onSelectedTags does not hang
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Review High Priority

#15532 test: fix OutOfMemoryError: Java heap space
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Labels: Pending Merge

#15534 docs: previewing in NOTES mode
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Pending Merge

#15531 fix: no need to hide the "show answer" button
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#15540 fix: IPA symbols in Type The Answer
  AnkiDroid/src/main/assets/flashcard.css
  AnkiDroid/src/main/assets/fonts/freefont/FreeMono.ttf
  AnkiDroid/src/main/assets/fonts/freefont/GNU GENERAL PUBLIC LICENSE.txt
Labels: Needs Second Approval

#15543 chore(debug): fix API 24: 'No Android WebView'
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt
Labels: Priority-Low, Needs Review

#15555 fix: navbar color if answer buttons aren't in the bottom
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Needs Second Approval

#15557 fix: wrong input to "type answer into the card"
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Review High Priority

#15561 ci: add 'strings' label for SearchPreferences
  .github/workflows/label.yml
Labels: Priority-Low, Needs Review

#15559 remove noCodeFormatting preference
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_advanced.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/TypeAnswerTest.kt
Labels: Pending Merge, Strings

#15571 fix: crash when leaving previewer if deck is too big
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
Labels: Pending Merge

#15567 fix: Android share menu no longer works for text
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15574 feat: user action reviewer buttons
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/res/drawable/user_action_1.xml
  AnkiDroid/src/main/res/drawable/user_action_2.xml
  AnkiDroid/src/main/res/drawable/user_action_3.xml
  AnkiDroid/src/main/res/drawable/user_action_4.xml
  AnkiDroid/src/main/res/drawable/user_action_5.xml
  AnkiDroid/src/main/res/drawable/user_action_6.xml
  AnkiDroid/src/main/res/drawable/user_action_7.xml
  AnkiDroid/src/main/res/drawable/user_action_8.xml
  AnkiDroid/src/main/res/drawable/user_action_9.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Needs Second Approval

#15575 Test: instrumented test for NoteEditor when text is sent
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval

#15570 fix: copyFileToCache NetworkOnMainThreadException
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
Labels: Pending Merge, squash-merge

#15580 chore: 'User action' category title: make plural
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Pending Merge, Strings

#15581 fix(note-editor): adding a note goes to selected image occlusion type
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Review High Priority, Pending Merge

#15597 Improve Discard Changes Dialog strings
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
Labels: Pending Merge, Strings, squash-merge

#15600 fix: gesture display in dark mode
  AnkiDroid/src/main/res/layout/gesture_display.xml
Labels: Needs Second Approval

#15038 fix: "Background" toggle not working
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/res/drawable/wallpaper_icon.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
Labels: Needs Second Approval

#15587 fix: NPE when adding note via intent
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Needs Author Reply, Pending Merge, Strings

#15606 hack(tts): treat 'speed = 1' as 'use system'
  AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
Labels: Pending Merge

#15605 temp: remove TTS Nag in Reviewer
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Review High Priority, Pending Merge

#15608 Fix bottom padding issues in HelpDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
  AnkiDroid/src/main/res/layout/fragment_help_page.xml
  AnkiDroid/src/main/res/layout/item_help_entry.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/help/HelpDialogTest.kt
Labels: Needs Second Approval

#15614 fix: Card Browser Deck Search - Keyboard does not appear
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Labels: Review High Priority, Needs Second Approval

#15621 Fix: Block error space for TextInputLayout
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/res/layout/my_account.xml
Labels: Pending Merge

#15622 chore: remove hungarian notation
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge, cleanup

#15607 chore: improve 'metered' connection string
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Priority-Low, Needs Second Approval, Strings

#15541 chore: remove `col` from TemplateRenderContext
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
Labels: Pending Merge, cleanup, squash-merge

#15634 Update FileUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
Labels: Needs Second Approval

#15637 hack: fix deck import crash
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
Labels: Review High Priority, Pending Merge

#15639 fix: checkbox style in black theme
  AnkiDroid/src/main/res/values/styles.xml
Labels: Priority-Low, Pending Merge

#15632 return opChanges in setUserFlagForCards
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Needs Second Approval, Queued for Cherry Pick to Stable Branch

#15630 make possible to use `-night` resources
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Needs Second Approval

#15640 feat: rename card templates
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/RenameCardTemplateDialog.kt
  AnkiDroid/src/main/res/menu/card_template_editor.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#15656 Change milestone target for PRs and issues to 2.18
  .github/workflows/milestone.yml
Labels: Pending Merge

#15659 fix: 'window count is over max!!'
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15662 docs: showManageAllFilesScreen - Timber logs
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionItem.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15664 chore: log debug info on startup
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15657 fix: obtaining image name from images
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
Labels: Review High Priority, Needs Second Approval, Queued for Cherry Pick to Stable Branch

#15667 fix: no such column: _display_name
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Review High Priority, Needs Second Approval, squash-merge, New contributor, Queued for Cherry Pick to Stable Branch

#15666 refactor: move exit() to AnkiActivity
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Pending Merge, squash-merge, Queued for Cherry Pick to Stable Branch

#15685 fix(ci): disable cache on all runners
  .github/workflows/tests_unit.yml
Labels: Pending Merge

#15683 Fix: checkbox color tint issue for dark theme
  AnkiDroid/src/main/res/values/styles.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#15644 fix + perf: use file scheme in `<img>` `<audio>`, `<video>` and `<object>`
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#15689 Extension function for listItem in AlertDialog
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Labels: Pending Merge

#15687 fix: image occlusion cards couldn't be previewed in the note editor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, Queued for Cherry Pick to Stable Branch

#15698 Fix: Keep the widgets & shortcuts disabled until storage permission is granted
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
Labels: Needs Second Approval

#15692 Show toast when importing without the app being started at least once
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Review High Priority, Pending Merge, Strings, Queued for Cherry Pick to Stable Branch

#15708 test: ignore NoteEditorIntentTest in CI
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
Labels: Review High Priority, Test process, Queued for Cherry Pick to Stable Branch

#15397 Removed the Material Dialog Box and Added Alert Box from CardBrowserMySearchesDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
  AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml
Labels: Pending Merge, squash-merge

#15709 Update api build.gradle to enable explicitApi()
  api/build.gradle.kts
Labels: Pending Merge, squash-merge

#15633 [Clean Up] : unexpected end of file
  annotations/README.md
Labels: Pending Merge, squash-merge, New contributor
