Repository ankidroid/Anki-Android, pull requests merged in 2024-08, with the labels that each got.

#16679 [GSoC'24] DeckPicker: Implementation of Keyboard Shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Needs Second Approval, GSoC

#16816 [GSoC'24] Refactor: move audio package to multimedia package
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioTimer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioWaveform.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/res/layout/activity_audio_recording.xml
  AnkiDroid/src/main/res/layout/activity_audio_recording_reviewer.xml
  AnkiDroid/src/test/java/com/ichi2/audio/AudioRecordingControllerTest.kt
Labels: Pending Merge, GSoC

#16785 Change the instance cloze builder Regex pattern
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
Labels: Pending Merge

#16818 refactor: Hungarian Notation rename
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
Labels: cleanup

#16814 [GSoC'24] CardBrowser: Shortcut E
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Pending Merge, Strings, GSoC

#16848 docs: dependencies - changelogs (androidx-work)
  gradle/libs.versions.toml
Labels: Pending Merge

#16855 docs: dependencies - changelogs (Apache Commons)
  gradle/libs.versions.toml
Labels: Pending Merge, cleanup

#16830 test: Added test case for requireLong() method at BundleUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
Labels: Needs Second Approval

#16775 fix: deckpicker to use transparent status bar
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
Labels: Pending Merge

#16868 remove Kotlin's "Context Receiver" feature
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/CardsOrNotes.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/internationalization/SentenceCase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserColumnTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardSoundConfigTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt
  build.gradle.kts
Labels: Pending Merge

#16749 [GSoC'24] Enhancement of Media Drop Feature in NoteEditor
  AnkiDroid/build.gradle
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/utils/ClipboardUtilTest.kt
  gradle/libs.versions.toml
  testlib/src/main/AndroidManifest.xml
Labels: Needs Second Approval, Strings, GSoC

#16876 Cleanup junit build dep / bump to 5.11.0
  gradle/libs.versions.toml
Labels: Pending Merge, dependencies

#16877 Dependency updates 20240815
  .github/workflows/lint.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  tools/localization/.eslintrc.js
  tools/localization/eslint.config.mjs
  tools/localization/package.json
  tools/localization/src/constants.ts
  tools/localization/src/update.ts
  tools/localization/src/upload.ts
  tools/localization/yarn.lock
Labels: Pending Merge

#16811 feat(tool): format issue/PR links in Discord
  tools/discord/format-for-discord.sh
  tools/discord/macos-clipboard-to-discord.sh
Labels: Needs Review

#16838 test: fix hangs on Linux
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Labels: Pending Merge

#16857 docs: dependencies - changelogs (AGP)
  gradle/libs.versions.toml
Labels: Pending Merge, cleanup

#16869 [UnitTest]: Ensure MultimediaBottomSheet is shown
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge

#16821 feat: Hide 'Hard' and 'Easy' buttons setting in the new reviewer
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewer.xml
Labels: Pending Merge, Strings

#16882 refactor: Commons Compress Improvements
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
Labels: Pending Merge

#16888 fix: IllegalStateException in audio player
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
Labels: Pending Merge

#16795 [GSoC'24] CardBrowser: Implementation of Keyboard Shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Needs Second Approval, GSoC

#16840 Fix: Tell the users why card type deletion fails when this would orphan note.
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
Labels: Pending Merge, Strings, squash-merge, New contributor

#16906 chore: add tooltip text in instant note editor buttons
  AnkiDroid/src/main/res/layout/instant_editor_dialog.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#16910 test: compare whole string not first char in NoteEditor test
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
Labels: Pending Merge

#16911 docs: add comment on when deprecated code may be removed
  AnkiDroid/src/main/aidl/android/content/pm/IPackageStatsObserver.aidl
Labels: Pending Merge

#16844 fix: unnecessary camera permission check
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#16913 fix: check sign in note editor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#16900 NF: Don't update the deck list when the deck picker is hidden
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#16915 fix: limit parameter of schedule URI returns the same data
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
Labels: Pending Merge, New contributor

#16930 build(deps): document & consolidate 'kotlin' dependency
  gradle/libs.versions.toml
Labels: Priority-Low, Pending Merge

#16726 Document the reason for dynamic shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Pending Merge

#16418 Update:twitter logo
  README.md
  docs/graphics/logos/twitter_logo.png
  docs/graphics/logos/twitter_logo_color.png
Labels: Priority-Low, New contributor

#16400 add toggle auto advance command
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Pending Merge, Strings

#16700 Update top bar setting description
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
Labels: Needs Second Approval, Strings

#16828 Twitter Link changed to X
  README.md
Labels: New contributor

#16929 feat(libAnki): implement decks.cardCount()
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge

#16939 release: switch 2.19 to beta version series, beta play store track
  AnkiDroid/build.gradle
Labels: Pending Merge

#16881 [GSoC'24] : Enhancement of Files Drop Feature in DeckPicker
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Needs Second Approval, GSoC

#16946 NF: remove all onboarding related code
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnboardingFlag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/res/drawable/hand_icon.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
  AnkiDroid/src/main/res/values/19-onboarding.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/OnboardingUtilsTest.kt
Labels: Pending Merge

#16871 Fixed the timebox
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#16977 Add warning to WIP dev options
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Pending Merge

#16975 docs: refine bug report form
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Pending Merge
