Repository ankidroid/Anki-Android, pull requests merged in 2024-10, with the labels that each got.

#17184 Dependency updates 20241002
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17175 fix: Prevent deck creation on 'Enter' key when deck name already exists
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#17173 Fix notetype name being reverted when going to CardTemplateEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#17041 Refactored `DeckPickerWidget` to handle empty state visibility.
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
  AnkiDroid/src/main/res/layout/widget_card_analysis.xml
  AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
  AnkiDroid/src/main/res/values/08-widget.xml
Labels: Pending Merge

#17143 [BUG]:The Set Due Date dialog box is missing its title
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
Labels: Pending Merge

#17195 Fix Android Studio lint errors in `AudioRecordingController.kt`
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
Labels: Pending Merge

#16535 Make permission item fully touchable
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionItem.kt
  AnkiDroid/src/main/res/layout/permission_item.xml
Labels: Pending Merge

#17022 fix:[BUG] Key Labels Not Displaying in Landscape Mode
  AnkiDroid/src/main/res/layout/dialog_key_picker.xml
Labels: Pending Merge

#17064 fix : [Bug] The layout of the Axis Picker screen is not displaying correctly in landscape mode
  AnkiDroid/src/main/res/layout/dialog_axis_picker.xml
Labels: UI, Pending Merge

#16880 [GSoC'24]: Implement Keyboard Shortcuts Helper
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/06-statistics.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
  AnkiDroid/src/main/res/values/08-widget.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, Strings, GSoC

#17200 Refactored `CardAnalysisWidget` to handle empty state visibility in similar way to `DeckPickerWidget`.
  AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
  AnkiDroid/src/main/res/layout/widget_card_analysis.xml
Labels: Pending Merge

#17218 test: update robolectric artifact list / suffix to match current
  AnkiDroid/robolectricDownloader.gradle
Labels: Pending Merge, CI

#17219 Dependency updates 20241009
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17103 Fix: Retain Search Filter After Deleting or Renaming Note Type in ManageNotetypes
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
Labels: Pending Merge

#17211 Multi-Line Support in NavigationDrawer Added
  AnkiDroid/src/main/res/layout/navigation_drawer.xml
Labels: Needs Second Approval

#17113 Fixed TTS Autoplay
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
Labels: Anki Ecosystem Compatibility, Pending Merge

#17237 Updated strings from Crowdin 2024/10/11 22:58
  AnkiDroid/src/main/res/values-be/01-core.xml
  AnkiDroid/src/main/res/values-be/02-strings.xml
  AnkiDroid/src/main/res/values-be/03-dialogs.xml
  AnkiDroid/src/main/res/values-be/06-statistics.xml
  AnkiDroid/src/main/res/values-be/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-be/08-widget.xml
  AnkiDroid/src/main/res/values-be/10-preferences.xml
  AnkiDroid/src/main/res/values-hy/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/06-statistics.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ja/08-widget.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/11-arrays.xml
  AnkiDroid/src/main/res/values-ja/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ko/01-core.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/06-statistics.xml
  AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-tr/08-widget.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
  AnkiDroid/src/main/res/values-tr/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/06-statistics.xml
  AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/08-widget.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/11-arrays.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/06-statistics.xml
  AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#17235 add missing user action message
  AnkiDroid/src/main/assets/scripts/card.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#17198 Enable Tooltip on ActionBar Subtitle for Overflow Text Visibility
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#17234 Help solving "All card options show (end)"
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
Labels: Pending Merge

#17242 Change undo default shortcut to Ctrl+Z
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
Labels: Pending Merge

#17241 replace string with backend version
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#17239 fix: audio recorder UI init twice
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioRecordingFragment.kt
Labels: Review High Priority, Pending Merge

#17247 docs: SingleFragmentActivity & key events
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
Labels: Pending Merge

#17250 Bug: Statistics Zoom Issue#16135
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/NestedScrollingWebView.kt
  AnkiDroid/src/main/res/layout/statistics.xml
Labels: Needs Author Reply, Needs Second Approval, hacktoberfest-accepted, New contributor

#17251 fix: SingleFragmentActivity: fragment has not been initialized
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
Labels: Review High Priority, Pending Merge

#17254 Updated strings from Crowdin 2024/10/14 09:02
  AnkiDroid/src/main/res/values-got/01-core.xml
  AnkiDroid/src/main/res/values-got/02-strings.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/04-network.xml
  AnkiDroid/src/main/res/values-ko/05-feedback.xml
  AnkiDroid/src/main/res/values-ko/06-statistics.xml
  AnkiDroid/src/main/res/values-ko/09-backup.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-ko/11-arrays.xml
  AnkiDroid/src/main/res/values-ml/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/06-statistics.xml
  AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rBR/08-widget.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ta/02-strings.xml
  AnkiDroid/src/main/res/values-ta/03-dialogs.xml
  AnkiDroid/src/main/res/values-ta/06-statistics.xml
  AnkiDroid/src/main/res/values-ta/08-widget.xml
  AnkiDroid/src/main/res/values-te/02-strings.xml
  AnkiDroid/src/main/res/values-te/03-dialogs.xml
  AnkiDroid/src/main/res/values-te/06-statistics.xml
  AnkiDroid/src/main/res/values-te/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-te/08-widget.xml
  AnkiDroid/src/main/res/values-te/10-preferences.xml
  AnkiDroid/src/main/res/values-te/16-multimedia-editor.xml
Labels: Pending Merge

#17259 feat: create and upload un-minified release during publish
  AnkiDroid/build.gradle
  tools/release.sh
Labels: Review High Priority, Needs Review

#17260 Updated strings from Crowdin 2024/10/15 04:25
  AnkiDroid/src/main/res/values-kk/01-core.xml
  AnkiDroid/src/main/res/values-ml/03-dialogs.xml
  AnkiDroid/src/main/res/values-ml/04-network.xml
  AnkiDroid/src/main/res/values-ml/06-statistics.xml
  AnkiDroid/src/main/res/values-ml/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ml/08-widget.xml
  AnkiDroid/src/main/res/values-ml/09-backup.xml
  AnkiDroid/src/main/res/values-ml/10-preferences.xml
  AnkiDroid/src/main/res/values-ml/11-arrays.xml
  AnkiDroid/src/main/res/values-sat/01-core.xml
  AnkiDroid/src/main/res/values-sat/04-network.xml
  AnkiDroid/src/main/res/values-ta/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ta/10-preferences.xml
  AnkiDroid/src/main/res/values-ta/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ta/17-model-manager.xml
  AnkiDroid/src/main/res/values-ta/18-standard-models.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/08-widget.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/11-arrays.xml
  AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-vi/01-core.xml
Labels: Pending Merge

#17258 Improve info shown when collection directory is not accessible
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings

#17266 Revert "fix: preserve debuggability even in minimized release mode"
  AnkiDroid/proguard-rules.pro
Labels: Review High Priority, Needs Review

#17280 fix: image preview was not shown after taking picture
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Review High Priority, Pending Merge

#17277 Fix learn ahead limit not working after updating setting
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
Labels: Review High Priority, Pending Merge

#17288 Updated strings from Crowdin 2024/10/20 16:07
  AnkiDroid/src/main/res/values-af/02-strings.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ckb/02-strings.xml
  AnkiDroid/src/main/res/values-de/01-core.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/03-dialogs.xml
  AnkiDroid/src/main/res/values-de/06-statistics.xml
  AnkiDroid/src/main/res/values-de/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-de/08-widget.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-de/11-arrays.xml
  AnkiDroid/src/main/res/values-de/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-fa/02-strings.xml
  AnkiDroid/src/main/res/values-fa/03-dialogs.xml
  AnkiDroid/src/main/res/values-fa/06-statistics.xml
  AnkiDroid/src/main/res/values-fa/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fa/08-widget.xml
  AnkiDroid/src/main/res/values-fa/09-backup.xml
  AnkiDroid/src/main/res/values-fa/10-preferences.xml
  AnkiDroid/src/main/res/values-fa/11-arrays.xml
  AnkiDroid/src/main/res/values-fa/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-heb/01-core.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-heb/05-feedback.xml
  AnkiDroid/src/main/res/values-heb/10-preferences.xml
  AnkiDroid/src/main/res/values-iw/01-core.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/03-dialogs.xml
  AnkiDroid/src/main/res/values-iw/05-feedback.xml
  AnkiDroid/src/main/res/values-iw/10-preferences.xml
  AnkiDroid/src/main/res/values-kk/01-core.xml
  AnkiDroid/src/main/res/values-pt-rPT/01-core.xml
  AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rPT/06-statistics.xml
  AnkiDroid/src/main/res/values-pt-rPT/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rPT/08-widget.xml
  AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rPT/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rPT/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-sat/01-core.xml
  AnkiDroid/src/main/res/values-sat/02-strings.xml
  AnkiDroid/src/main/res/values-sc/01-core.xml
  AnkiDroid/src/main/res/values-sc/02-strings.xml
  AnkiDroid/src/main/res/values-sc/03-dialogs.xml
  AnkiDroid/src/main/res/values-sc/04-network.xml
  AnkiDroid/src/main/res/values-sc/06-statistics.xml
  AnkiDroid/src/main/res/values-sc/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sc/08-widget.xml
  AnkiDroid/src/main/res/values-sc/10-preferences.xml
  AnkiDroid/src/main/res/values-sc/20-search-preference.xml
  AnkiDroid/src/main/res/values-ur/08-widget.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Labels: Pending Merge

#17289 Updated strings from Crowdin 2024/10/20 18:00
  AnkiDroid/src/main/res/values-fa/02-strings.xml
  AnkiDroid/src/main/res/values-sc/02-strings.xml
  AnkiDroid/src/main/res/values-sc/03-dialogs.xml
  AnkiDroid/src/main/res/values-sc/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-sc/08-widget.xml
  AnkiDroid/src/main/res/values-sc/09-backup.xml
  AnkiDroid/src/main/res/values-sc/10-preferences.xml
  AnkiDroid/src/main/res/values-sc/11-arrays.xml
  AnkiDroid/src/main/res/values-sc/16-multimedia-editor.xml
Labels: Pending Merge

#17290 Dependency updates 20241020
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17287 fix: CardTemplateEditor restores wrong editor view
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#17283 Fix saving changes in NoteEditor after CardTemplateEditor visit
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Review High Priority, Needs Second Approval

#17285 Fixed some Android Studio warnings
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/exception/ConfirmModSchemaException.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.kt
  AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesSimpleTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt
  api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
  api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
Labels: Pending Merge, hacktoberfest-accepted, New contributor

#17296 refactor: remove context from `InstantEditorViewModel`
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
Labels: Pending Merge

#17269 chore: add funding.json for FLOSS/fund
  funding.json
Labels: Pending Merge

#17299 fix: emulator tests: testCustomSchedulerWithCustomData
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
Labels: Pending Merge

#17297 Added SHA256 & SHA1 application certificate fingerprints to README
  README.md
Labels: Pending Merge, hacktoberfest-accepted, squash-merge, New contributor

#17291 refactor: improve logs related to deckPicker in StudyOptionsFragment
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Pending Merge, squash-merge

#17307 Updated strings from Crowdin 2024/10/25 15:28
  AnkiDroid/src/main/res/values-hy/02-strings.xml
  AnkiDroid/src/main/res/values-hy/06-statistics.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  docs/marketing/localized_description/marketdescription-hy-AM.txt
Labels: Pending Merge

#17292 Lint odyssey
  AnkiDroid/build.gradle
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerButtons.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
  AnkiDroid/src/main/res/drawable/edit_text_color_enabled_selector.xml
  gradle/libs.versions.toml
  lint-release.xml
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
  testlib/src/main/java/com/ichi2/testutils/common/FailOnUnhandledExceptionRule.kt
Labels: Needs Review, squash-merge

#17311 test: deck options on back press
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
  AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
Labels: Pending Merge, hacktoberfest-accepted, New contributor

#17313 fix: revert workaround for broken AGP [8.6.1]
  AnkiDroid/src/main/java/com/ichi2/compat/PackageManagerCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
Labels: Pending Merge, cleanup

#17324 Enable filtered decks in widget
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt
Labels: Pending Merge

#17336 Revert "fix: remove ancient image fill-while-zoomable hack"
  AnkiDroid/src/main/assets/flashcard.css
  AnkiDroid/src/main/assets/scripts/card.js
Labels: Review High Priority, Needs Review

#17337 Updated strings from Crowdin 2024/10/31 16:46
  AnkiDroid/src/main/res/values-bn/02-strings.xml
  AnkiDroid/src/main/res/values-bn/03-dialogs.xml
  AnkiDroid/src/main/res/values-bn/04-network.xml
  AnkiDroid/src/main/res/values-bn/11-arrays.xml
  AnkiDroid/src/main/res/values-bn/17-model-manager.xml
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-es-rES/10-preferences.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-fa/02-strings.xml
  AnkiDroid/src/main/res/values-fa/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fa/11-arrays.xml
  AnkiDroid/src/main/res/values-fa/17-model-manager.xml
  AnkiDroid/src/main/res/values-heb/01-core.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-heb/06-statistics.xml
  AnkiDroid/src/main/res/values-heb/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-heb/08-widget.xml
  AnkiDroid/src/main/res/values-heb/10-preferences.xml
  AnkiDroid/src/main/res/values-heb/11-arrays.xml
  AnkiDroid/src/main/res/values-heb/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-iw/01-core.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/03-dialogs.xml
  AnkiDroid/src/main/res/values-iw/06-statistics.xml
  AnkiDroid/src/main/res/values-iw/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-iw/08-widget.xml
  AnkiDroid/src/main/res/values-iw/10-preferences.xml
  AnkiDroid/src/main/res/values-iw/11-arrays.xml
  AnkiDroid/src/main/res/values-iw/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-vi/03-dialogs.xml
  AnkiDroid/src/main/res/values-vi/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-vi/10-preferences.xml
  AnkiDroid/src/main/res/values-vi/16-multimedia-editor.xml
Labels: Pending Merge
