Repository ankidroid/Anki-Android, pull requests merged in 2024-05, with the labels that each got.

#16304 fix: NullPointerException: deckSpinnerSelection
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Review High Priority, Pending Merge

#16287 Undo stroke in drawing editor
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
  AnkiDroid/src/main/res/drawable/eraser.xml
  AnkiDroid/src/main/res/menu/drawing_menu.xml
Labels: Pending Merge, New contributor

#16308 fix(tags-dialog): alignment of checkbox
  AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml
Labels: Needs Second Approval

#16315 Dependency updates 20240501
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#16330 Fix refresh of DeckPicker UI after a new collection import
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#16316 fix: localizations not being added to values-iw
  tools/localization/src/update.ts
Labels: Needs Second Approval, New contributor

#16307 Created test for onSelectedTags.
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Pending Merge, squash-merge

#16341 build(ci): decrease unit test timeout to 30 minutes
  .github/workflows/tests_unit.yml
Labels: Pending Merge

#16338 fix(template-previewer): 'currentCard' has not been initialized
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
Labels: Review High Priority, Pending Merge

#16342 fix: 'iw' is a RTL language
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/ext/XmlContext.kt
Labels: Review High Priority, Pending Merge

#16345 add keyboard shortcuts to flag and mark in previewer
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
Labels: Pending Merge

#16334 fix(audio-recorder): crash if saving immediately
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
Labels: Review High Priority, Pending Merge

#16344 fix sync tooltip text
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt
  AnkiDroid/src/main/res/layout/sync_progress_layout.xml
Labels: Needs Second Approval

#16350 add progress dialog to deck options
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Needs Second Approval

#16370 Guide support and feature requests to the forums
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Pending Merge, squash-merge

#16374 fix: prevent highlight with bluetooth controller
  AnkiDroid/src/main/res/values/disable-fullscreen-keyboard-highlight.xml
Labels: Pending Merge, New contributor

#16317 chore: update a part of libanki
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Pending Merge

#16332 Added ContentDescription for check pronunciation
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
  AnkiDroid/src/main/res/layout/activity_audio_recording.xml
  AnkiDroid/src/main/res/layout/activity_audio_recording_reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#16336 fix: lateinit property viewPager has not been initialized
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Review High Priority, Pending Merge

#16347 fix tts in browser
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge, squash-merge

#16353 fix: CORS issue with JS loading
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
Labels: Pending Merge

#16349 grant audio capture permission to webview
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#16297 feat: Toggle bury
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/sentence-case.xml
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
Labels: Pending Merge, Strings

#16380 fix class not found issue in API 25
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Pending Merge

#16383 Dependency updates 20240512
  gradle/libs.versions.toml
Labels: Pending Merge

#16381 add search keyboard shortcut
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#16371 fix: Inconsistent tag checkbox color
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
Labels: Pending Merge

#15029 enhancement: allow camera access when using image occlusion
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/ImageOcclusionBottomSheetFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImageUtils.kt
  AnkiDroid/src/main/res/drawable/ic_camera.xml
  AnkiDroid/src/main/res/drawable/ic_gallery.xml
  AnkiDroid/src/main/res/drawable/ic_paste.xml
  AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Pending Merge, Blocked by dependency, squash-merge

#16398 fix: IO type reappears when card is added
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Pending Merge

#16402 Update forums links
  .github/ISSUE_TEMPLATE/config.yml
Labels: Pending Merge

#16401 [GSoC'24] chore: extract `ActionMode.Callback` from NoteEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CustomActionModeCallback.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge, GSoC

#16379 fix language country with system default
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilRobolectricTest.kt
Labels: Needs Second Approval, Needs reviewer reply

#16378 improve optimizing presets message
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Pending Merge

#16415 Dependency updates 20240516
  gradle/libs.versions.toml
Labels: Pending Merge

#16413 fix summary overflow
  AnkiDroid/src/main/res/layout/extended_category.xml
Labels: Needs Second Approval

#16422 fix manage notetypes menu
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/res/menu/search.xml
Labels: Pending Merge

#16417 fix: currentCard not initialized
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#16242 AnkiDroid to use flag names like anki
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/res/menu/card_browser.xml
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/menu/previewer.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#16266 Migrated AndroidPermanentlyRevokedPermissionsDialog to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/AndroidPermanentlyRevokedPermissionsDialog.kt
Labels: Pending Merge

#16434 Migrate MaterialDialog to AlertDialog in ModelFieldEditorTest
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
Labels: Needs Review

#16411 fix stats orientation change
  AnkiDroid/src/main/AndroidManifest.xml
Labels: Pending Merge

#16391 Added Unit test for Reviewer.kt.
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Pending Merge, Tests

#16437 fix(note-editor): display 'home' deck if filtered
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#16445 refactor: Kotlin 2.0 deprecations
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/AutoFocusEditTextPreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  lint-rules/build.gradle.kts
Labels: Pending Merge

#16446 fix(note-editor): deck for new cards was not saved
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#16448 refactor: use Parcelable for PreviewerIdsFile
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
Labels: Priority-Low, Pending Merge

#16291 refactor(card-browser): extract 'launchOptions'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge

#16454 tests: fix for Kotlin 2.0
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Labels: Pending Merge

#16464 Dependency updates 20240523
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#16457 fix: reviewer `fetch` and `XMLHttpRequest` issues
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
Labels: Needs Author Reply, Needs Second Approval, squash-merge, Queued for Cherry Pick to Stable Branch

#16368 [GSoC'24] Highlight selected preference setting
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt
  AnkiDroid/src/main/res/xml/preference_headers.xml
Labels: Pending Merge, GSoC

#16453 fix: show search icon instantly
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Labels: Priority-Low, Pending Merge

#16451 Migrate root build file to kotlin dsl
  build.gradle
  build.gradle.kts
  tools/release.sh
Labels: Priority-Low, Pending Merge

#16466 20s Timeout in JvmTest and RobolectricTest
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
Labels: Pending Merge

#16472 Created JS API function to add a specific tag
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
Labels: Pending Merge

#16479 Fix keyboard not appearing for toolbar in TagsDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#16482 fix(tags-dialog): crash handling unicode tags
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#16491 fix(tags-dialog): fix UTFDataFormatException
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/TagTestData.kt
  AnkiDroid/src/test/resources/anking_v11_tags.txt
Labels: Review High Priority, Needs Second Approval, Queued for Cherry Pick to Stable Branch

#16505 Dependency updates 20240530
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#16480 UnitTest : String null test for note editor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge, squash-merge
