Repository ankidroid/Anki-Android, pull requests merged in 2024-03, with the labels that each got.

#15731 fix: remove pref_summary_percentage
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_accessibility.xml
Labels: Review High Priority, Pending Merge, Needs Second Approval, Strings

#15729 show warning inside control dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/GestureSelectionDialogUtils.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt
  AnkiDroid/src/main/java/com/ichi2/ui/KeyPicker.kt
  AnkiDroid/src/main/res/layout/dialog_key_picker.xml
  AnkiDroid/src/main/res/layout/gesture_picker.xml
  AnkiDroid/src/test/java/com/ichi2/ui/KeyPickerTest.kt
Labels: Pending Merge

#15732 fix isScreenSw600dp deprecation
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
  AnkiDroid/src/main/res/values-sw600dp/bools.xml
  AnkiDroid/src/main/res/values/bools.xml
Labels: Needs Second Approval

#15734 fix NoteEditor deprecation
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15735 chore: replace `@RequiresApi` with `@SdkSuppress`
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
Labels: Pending Merge, Needs Review

#15396 Some Dialogs of DatabaseErrorDialog Converted to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Pending Merge, squash-merge

#15742 fix: publish failure - is_big_screen
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
  AnkiDroid/src/androidTest/res/values-sw600dp/bools.xml
  AnkiDroid/src/androidTest/res/values/bools.xml
Labels: Review High Priority

#15744 build(ci): add `lintVitalFullRelease` to lint
  .github/workflows/lint.yml
Labels: Pending Merge

#15747 revert: disable widget if no storage access
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15650 refactor: use `-night` to deduplicate browser flag colors
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/res/values-night/colors.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Priority-Low, Pending Merge, cleanup

#15754 chore(pr-template): make 'Fixes' more intuitive
  .github/pull_request_template.md
Labels: Needs Second Approval, cleanup

#15641 NF: Reposition Card Template Dialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/RepositionCardTemplateDialog.kt
  AnkiDroid/src/main/res/menu/card_template_editor.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Priority-Low, Pending Merge, Strings

#15739 fix: edit Comments field in Image Occlusion note
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15770 chore: update first-run-needed string
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Strings, cleanup, Queued for Cherry Pick to Stable Branch

#15736 turn preference into SliderPreference
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/xml/preferences_accessibility.xml
Labels: Pending Merge, Strings, Queued for Cherry Pick to Stable Branch

#15750 feat: copy card template to clipboard as Markdown
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/res/menu/card_template_editor.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
Labels: Pending Merge, Strings, Queued for Cherry Pick to Stable Branch

#15774 fix: Play store already has 2.18alpha4, bump version
  AnkiDroid/build.gradle
Labels: Needs Review

#15780 fix: assets loading with mixed `<script>` tags
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt
Labels: Review High Priority, Pending Merge

#15785 chore: Failure string as default in `copyToClipboard` method
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
Labels: Needs Second Approval

#15781 fix: Anki Desktop strings: use sentence case
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/internationalization/SentenceCase.kt
  AnkiDroid/src/main/res/values/sentence-case.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
Labels: Needs Second Approval

#15793 fix: new previewer - newline handling
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15799 [Clean Up] : Replacing enum.values() by enum.entries
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Theme.kt
Labels: Pending Merge, squash-merge, New contributor

#15804 chore(log): CardBrowserViewModel
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Priority-Low, Needs Review

#15808 fix: can't create first deck if named 'default'
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/res/layout/dialog_generic_text_input.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings, squash-merge

#15806 Exit confirmation in IO Editor
  AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
Labels: Pending Merge

#15812 chore(ci): translation sync: link activity stream
  .github/workflows/sync_translations.yml
Labels: Priority-Low, Pending Merge

#15816 chore(issue-template): Add link to Anki Forums
  .github/ISSUE_TEMPLATE/config.yml
Labels: Pending Merge

#15765 Fix: Widget - Missing storage permission causing NPE and crashing app
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15817 tests: 'showingCardHidesFullScreen' - flaky on Windows
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Labels: Review High Priority, Pending Merge

#15815 #13282 #15704: Fixes Android Studio Warnings under Kotlin Header
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.kt
  AnkiDroid/src/test/java/com/ichi2/utils/FileOperation.kt
Labels: Pending Merge, cleanup

#15841 allow access to webViewClient on API 23
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#15845 Added CopyURL function to openUrl fun.
  AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt
Labels: Pending Merge, squash-merge

#15842 fix: missing background color on Anki pages
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15837 fix: bad av tags extracting
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#15861 fix: theme follow system configuration
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Labels: Pending Merge

#15873 chore(git-blame): ignore more files
  .git-blame-ignore-revs
Labels: cleanup

#15867 lint: "JavaScript" capitalization
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt
Labels: Priority-Low, cleanup

#15821 Fix: Widget intent not updated if added before storage permission
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetPermissionReceiver.kt
Labels: Review High Priority, Queued for Cherry Pick to Stable Branch

#15894 fix: change context to match application theme
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#15897 [Cleanup]: Fix Android Studio Warnings #13282
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Labels: Pending Merge, squash-merge, New contributor

#15893 UI: add card design to the previewers
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Fragment.kt
  AnkiDroid/src/main/res/layout/previewer.xml
  AnkiDroid/src/main/res/layout/template_previewer.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Pending Merge, Previewer, squash-merge

#15890 fix: image name with unescaped chars
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#15619 feat: sync media in the background
  AnkiDroid/build.gradle
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notifications/NotificationId.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/UniqueWorkNames.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings, Needs a new dev, Needs reviewer reply

#15926 return value from js-api with correct datatype
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
Labels: Pending Merge

#15949 refactor: remove unused code [SyncStatus]
  AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Labels: Pending Merge, cleanup

#15512 Enhacement: allow the apkg packages to be shared with AnkiDroid
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
Labels: Pending Merge

#15957 [Cleanup]: Fix Android Studio Warnings {regarding Constant Conditions} #13282
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt
Labels: Pending Merge, squash-merge

#15960 Align search view close icon align to end
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Labels: Pending Merge

#15969 fix: handle unencoded `#` in file paths
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt
Labels: Needs Second Approval, Queued for Cherry Pick to Stable Branch

#15964 test: ensure constant uniqueness
  AnkiDroid/src/main/java/com/ichi2/anki/notifications/NotificationId.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/UniqueWorkNames.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ConstantUniquenessTest.kt
Labels: Pending Merge, squash-merge

#15973 notify StudyOptionsFragment when deck deleted on tablet
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Pending Merge

#15972 Ask to check if a bug exists in Anki desktop on the bug report template
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Pending Merge, squash-merge

#15979 make js api's new/lrn/rev counts integers
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
  AnkiDroid/src/test/resources/test-js-addon.json
  AnkiDroid/src/test/resources/valid-ankidroid-js-addon-test.json
Labels: Pending Merge

#15982 [Cleanup]: Fix Android Studio Warnings #13282
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
Labels: Needs Author Reply, squash-merge

#15987 refactor: update `libanki/Card.kt` partially
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/utils/LibAnkiAlias.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerTimerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Needs Second Approval, squash-merge

#15909 fix: IO - use absolute path for cached copy
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Labels: Pending Merge

#15966 Migrate version catalog
  AnkiDroid/build.gradle
  AnkiDroid/proguard-rules.pro
  api/build.gradle.kts
  build.gradle
  gradle/libs.versions.toml
  lint-rules/build.gradle.kts
  settings.gradle.kts
  testlib/build.gradle.kts
Labels: Pending Merge, squash-merge

#15789 Feature/add search bar to manage note types
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings, squash-merge, New contributor

#16018 fix(previewers): url loading in API 23
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
Labels: Pending Merge

#16015 fix: DeckOptions on API 23
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#16021 test: tablet layout is based on xlarge not sw600dp values overlay
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
  AnkiDroid/src/androidTest/res/values-sw600dp/bools.xml
  AnkiDroid/src/androidTest/res/values/bools.xml
Labels: Needs Review, Test process

#16024 Dependency updates 20240329
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  lint-release.xml
Labels: Pending Merge, squash-merge

#16027 feat(Statistics): Hide Toolbar on Scroll
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/res/layout/statistics.xml
Labels: Pending Merge
