Repository ankidroid/Anki-Android, pull requests merged in 2024-12, with the labels that each got.

#17402 Block reports sent to ACRA
  .idea/dictionaries/usernames.xml
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ThrowableFilterServiceTest.kt
  build.gradle.kts
Labels: Needs Second Approval, squash-merge

#17495 fix: don't show warning on numpad
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/android/input/Shortcut.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ShortcutTest.kt
Labels: Pending Merge

#17404 Reenable DeckPickerTest
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Pending Merge, Tests

#17537 Dependency updates 20241202
  AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
  gradle/libs.versions.toml
  tools/localization/.gitignore
  tools/localization/.yarn/releases/yarn-4.5.3.cjs
  tools/localization/.yarnrc.yml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17430 NF: Use com.ichi2.anki.Ease as much as possible
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DummyScheduler.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  api/src/main/java/com/ichi2/anki/api/Ease.kt
Labels: Pending Merge

#17434 NF: Use enum for flag everywhere possible
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
Labels: Pending Merge, Needs reviewer reply

#17547 Fixed a weak warning of "The argument can be converted to 'Set' to improve performance" in MediaTest.kt file in Line 131.
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
Labels: Pending Merge, New contributor

#17552 logs: syncing
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
Labels: Pending Merge

#17553 improvement: remove some `getColUnsafe` usages
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge, cleanup

#17554 fix: startActivity
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
Labels: Pending Merge

#17555 refactor: remove 'sched.totalCards'
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
Labels: Pending Merge

#17558 Fix workflow failure when (Has Conflicts) label is already removed
  .github/workflows/conflict.yaml
Labels: Pending Merge

#17564 refactor(integer-dialog): make title non-null
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Labels: Pending Merge, cleanup

#17566 improvement(i18n): link 'Re-sync translations'
  .github/workflows/sync_translations.yml
Labels: Needs Review

#17035 Feat[Multimedia]: render `svg` using webview
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt
  AnkiDroid/src/main/res/layout/fragment_multimedia_image.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge, Strings

#17464 Remove Automatic Display Answer global setting
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerTest.kt
Labels: Pending Merge, Strings

#17279 feat(error-dialog): copy stack trace & debug info
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt
Labels: Pending Merge

#17433 NF: APIResult takes known type only
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
Labels: Pending Merge, JS API

#17572 Some cleaning of Database error dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Labels: Pending Merge

#17568 NF: Remove `else ->` when possible
  AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
Labels: Pending Merge

#17584 add transitions to preferences fragments
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Pending Merge

#17585 add controls icons
  AnkiDroid/src/main/res/drawable/ic_double_arrow_down.xml
  AnkiDroid/src/main/res/drawable/ic_double_arrow_up.xml
  AnkiDroid/src/main/res/drawable/ic_fast_forward.xml
  AnkiDroid/src/main/res/drawable/ic_lightbulb.xml
  AnkiDroid/src/main/res/drawable/ic_lightbulb_stars.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
Labels: Pending Merge

#17588 warn if user action is not set in new reviewer
  AnkiDroid/src/main/assets/scripts/ankidroid.js
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
Labels: Needs Second Approval

#17589 disable fragment animation in safe display mode
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Needs Second Approval

#17590 dev: ignore lint fixes in git blame
  .git-blame-ignore-revs
Labels: Pending Merge, cleanup

#17597 fix(note-editor): restore instance state
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17592 NF: improve the readability of some strings
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Labels: Pending Merge

#17599 fix onBackPressed deprecation of CardTemplateEditor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#17461 Add Restore to Default feature
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/res/menu/card_template_editor.xml
Labels: Anki Ecosystem Compatibility, Needs Second Approval

#17610 fix: currentDeckId broken
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
Labels: Review High Priority, Pending Merge

#17614 Updated strings from Crowdin 2024/12/17 18:10
  AnkiDroid/src/main/res/values-de/11-arrays.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
Labels: Pending Merge

#17595 Improve pre commit hook
  pre-commit
Labels: Pending Merge

#17616 Changed Release order and description of releases page
  tools/release-description.md
  tools/release.sh
Labels: squash-merge

#17619 dev(github): use 'Bug' type for new issues
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Priority-Low, Needs Second Approval

#17624 test(coverage): only fail CI on main repo
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Needs Second Approval

#17622 Dependency updates 20241218
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#17621 build(deps): remove dokka, no longer in use
  api/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Pending Merge, dependencies

#17631 fix(pre-commit): syntax error
  pre-commit
Labels: Review High Priority

#17642 build(ci): add emoji to pinned items to reorder
  .github/workflows/conflict.yaml
  .github/workflows/label.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/sync_translations.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Priority-Low, Needs Review

#17623 fix: Navigate Up versus Close
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Labels: Needs Second Approval

#17655 Minor fixup for release-description.md
  tools/release-description.md
Labels: Needs Second Approval

#17648 [Cleanup]: Resolve Android Studio Warnings (#13282)
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
Labels: Pending Merge, New contributor

#17661 rename ViewerAction.EDIT_NOTE
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
Labels: Needs Second Approval

#17675 Simplify CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Pending Merge

#17674 Pre commit hook typo correction
  pre-commit
Labels: Review High Priority, Pending Merge

#17672 Add Rounded Backgrounds to Widgets for Consistent UI Across APIs
  AnkiDroid/src/main/res/drawable/widget_card_analysis_drawable.jpg
  AnkiDroid/src/main/res/drawable/widget_card_analysis_drawable.png
  AnkiDroid/src/main/res/drawable/widget_card_analysis_rounded_background.xml
  AnkiDroid/src/main/res/drawable/widget_card_analysis_rounded_inner_background.xml
  AnkiDroid/src/main/res/drawable/widget_deck_picker_drawable.jpg
  AnkiDroid/src/main/res/drawable/widget_deck_picker_drawable.png
  AnkiDroid/src/main/res/drawable/widget_deck_picker_rounded_background.xml
  AnkiDroid/src/main/res/layout/widget_card_analysis.xml
  AnkiDroid/src/main/res/layout/widget_card_analysis_drawable_v31.xml
  AnkiDroid/src/main/res/layout/widget_deck_picker_drawable_v31.xml
  AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
Labels: Widget, Pending Merge

#17686 feat(debug-info): log more device info & reduce vertical space used
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Labels: Needs Review

#17679 refactor: fix a number of KotlinCleanups
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldBase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.kt
Labels: Needs Second Approval, cleanup

#17689 NF: Simplify `currentDeckId`
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Labels: Needs Second Approval

#17684 Rename `m` to noteType
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
Labels: Pending Merge

#17682 Fixes #Issue-17520 Ensures testlib is built
  AnkiDroid/build.gradle
  AnkiDroid/jacoco.gradle
  build.gradle.kts
Labels: Needs Second Approval
