Repository ankidroid/Anki-Android, pull requests merged in 2024-01, with the labels that each got.

#15114 Title in progress dialog
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/res/values/04-network.xml
Labels: Pending Merge, Strings

#15123 Follow-up: Fix Android Studio warnings for redundant constructors
  AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
  AnkiDroid/src/main/java/com/ichi2/anki/exception/StorageAccessException.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ServiceUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/FullDraggableContainerFix.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SortOrderUtil.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt
  AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/NetworkUtils.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Pending Merge

#15129 Enable zoom in anki pages
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
Labels: Pending Merge

#15122 Improve text/csv importer functionality
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
Labels: Pending Merge

#15030 Disable the save button and previewer button if note type is `Image occlusion`
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge, squash-merge

#15136 fix editor shift tab
  AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
Labels: Pending Merge

#15065 Updated MaterialDialog to AlertDialog in SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
Labels: Needs Second Approval, New contributor

#15148 move ConfirmationDialog to material
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Labels: Needs Second Approval

#15150 test: mark typedLanguageIsSet as flaky
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Labels: Review High Priority, Pending Merge

#15149 move DeckPickerBackupNoSpaceLeftDialog to alert dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Labels: Pending Merge

#15087 Autofocus keyboard in Resume State only when "type in answer" checked ✅
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#15151 fix Browser Options dialog color
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Pending Merge

#15077 refactor: Browser current query text
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Pending Merge, squash-merge

#15140 fix: new previewer not showing when only one card is previewed + change buttons behavior to match Anki Desktop
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/res/layout/previewer.xml
Labels: Pending Merge, squash-merge

#15131 fix: mathjax render
  AnkiDroid/src/main/assets/mathjax/conf.js
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
Labels: Pending Merge

#15124 fix: Deck Options screen flickers in dark mode
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
Labels: Pending Merge

#15128 chore(dev): remove card.html
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#14740 new audio recorder and player
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioTimer.kt
  AnkiDroid/src/main/res/drawable/ic_pause_white_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_play_arrow_white_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_rec.xml
  AnkiDroid/src/main/res/drawable/ic_rec_stop.xml
  AnkiDroid/src/main/res/drawable/ic_replay.xml
  AnkiDroid/src/main/res/drawable/ic_stop_white_24dp.xml
  AnkiDroid/src/main/res/drawable/round_done_24.xml
  AnkiDroid/src/main/res/layout/activity_audio_recording.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/colors.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
  AnkiDroid/src/test/java/com/ichi2/audio/AudioRecordingControllerTest.kt
Labels: Pending Merge, Strings

#15158 tests: use shared-preferences-mock
  AnkiDroid/build.gradle
  AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
  AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
Labels: Needs Second Approval

#15155 add deck title back
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
Labels: Needs Second Approval, Strings

#15146 fix: remove menu icons
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/res/drawable/ic_action_suspend_dropdown.xml
  AnkiDroid/src/main/res/drawable/ic_card_reschedule_white.xml
  AnkiDroid/src/main/res/drawable/ic_flip_to_back_dropdown.xml
  AnkiDroid/src/main/res/drawable/ic_pause_circle_outline.xml
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/menu/reviewer_bury.xml
  AnkiDroid/src/main/res/menu/reviewer_schedule.xml
  AnkiDroid/src/main/res/menu/reviewer_suspend.xml
Labels: Pending Merge, squash-merge

#15180 cleanup: remove unused 'MutableTime'
  AnkiDroid/src/test/java/com/ichi2/testutils/MutableTime.kt
Labels: Pending Merge, cleanup

#15179 fix: whiteboard not drawing
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Labels: Review High Priority, Pending Merge

#15181 cleanup: Hungarian Notation - all but 5 files
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldControllerBase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/async/AsyncOperation.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Needs Second Approval, cleanup, squash-merge

#15182 NF: remove col = col
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
Labels: Pending Merge, cleanup

#15193 add stats button title
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
Labels: Pending Merge

#15204 Dependency updates 20240111
  AnkiDroid/build.gradle
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  build.gradle
  tools/localization/yarn.lock
Labels: Pending Merge

#15230 refactor: remove FirefoxSnackbarWorkaround
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/workarounds/FirefoxSnackbarWorkaround.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#15249 Fix ExportReadyDialog restore from Bundle
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
Labels: Pending Merge

#15258 chore: log pre-coroutine stack trace when in DEBUG mode
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#15259 fix: DeckPicker storage error on first run
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#15252 Allow AnkiDroid to register itself to open tsv/csv files
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
Labels: Pending Merge, squash-merge

#15269 chore: early return in `filterUrl`
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Pending Merge

#15265 fix: Media check file list dark mode appearance
  AnkiDroid/src/main/res/layout/media_check_dialog_body.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Pending Merge

#15224 Switch the auto advance feature to use the settings in the deck options
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewing.xml
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerActionTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
Labels: Pending Merge, Strings, squash-merge

#15274 fix: undo delete deck action in snackbar
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#15282 build(deps): update all javascript deps
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#15067 Use the new M3 adding errors & end mode icon to clear text field
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/res/layout/my_account.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/MyAccountTest.kt
Labels: Needs Second Approval, Strings

#15283 fix: stats not appearing
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
Labels: Review High Priority, Pending Merge

#15275 chore: convert InsertFieldDialog to AlertDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
  AnkiDroid/src/main/res/layout/dialog_generic_recycler_view.xml
Labels: Needs Second Approval

#15260 [Enhancement] Icon updation for enable/disable whiteboard as per issue #15253
  AnkiDroid/src/main/res/drawable/ic_enable_whiteboard.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
Labels: Needs Second Approval

#15271 chore: reset analytics opt-in
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
Labels: Needs Second Approval

#15268 fix(CardBrowser): retain selection when toggling 'mark'
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Needs Second Approval

#15289 fix: eternal load when editing a note from the new previewer
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#15255 Remove the brand icons
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
  AnkiDroid/src/main/res/drawable/discord.xml
  AnkiDroid/src/main/res/drawable/facebook.xml
  AnkiDroid/src/main/res/drawable/ic_link.xml
  AnkiDroid/src/main/res/drawable/reddit.xml
  AnkiDroid/src/main/res/drawable/twitter.xml
Labels: Pending Merge, squash-merge

#15280 refactor: remove `getColUnsafe` calls
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Needs Second Approval, cleanup

#15254 refactor: use Context receivers to remove `this` within `withCol` [Experimental API]
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/model/CardsOrNotes.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardSoundConfigTest.kt
  build.gradle
Labels: Pending Merge, cleanup, squash-merge, Needs reviewer reply

#15238 Color of Bottom Window changes based on the theme of the app.
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Pending Merge, squash-merge

#15295 chore: remove `processInefficientImage`
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt
Labels: Needs Second Approval, Strings

#15304 Support customizing preview delays for Again, Hard, and Good buttons
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/filtered_deck_options.xml
  AnkiDroid/src/main/res/xml/cram_deck_options.xml
Labels: Pending Merge, Strings, squash-merge

#15299 fix: play tags shown in card browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt
Labels: Pending Merge

#15173 build(deps): AGP 8.2.2 w/JDK21 compatibility, switch CI to JDK21
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
  .github/workflows/update-gradle-wrapper.yml
  build.gradle
Labels: Blocked by dependency, Has Conflicts

#15315 fix: Card Browser results flashing
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Review High Priority, Pending Merge

#15311 feat: enable fullscreen in <video> tags
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Labels: Review High Priority, Pending Merge

#15325 i18n sync workflow on ubuntu / bump javascript deps
  .github/workflows/sync_translations.yml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#15327 chore(deps): switch i18n workflow to use node 20
  .github/workflows/sync_translations.yml
Labels: Pending Merge

#15292 fix: "Invalid input: card was modified"
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/OnlyOnce.kt
  AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt
Labels: Pending Merge

#15333 [Bug Fix] Fixed AlertDialog theme color made darker
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
Labels: Pending Merge, squash-merge

#15339 chore(deps): keep npm dependency updates to one PR if non-breaking
  .github/dependabot.yml
Labels: Pending Merge

#15347 chore: add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: Pending Merge, cleanup

#15340 NoteEditor/CardTemplateEditor: Color Nav bar
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#15251 chore: remove `col` from Note
  AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge, cleanup

#15341 typo: action name (tests)
  .github/workflows/tests_unit.yml
Labels: Needs Review, cleanup

#15367 test(ci): upgrade macOS runner to M1 & macOS 14
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
Labels: Needs Second Approval

#15366 Fix: API30 tts `availableVoices` to return empty set to avoid crash
  AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
Labels: Needs Second Approval

#15338 Add AnkiDroid API LGPL License to Readme
  README.md
Labels: Pending Merge, New contributor

#15373 ci: add flaky annotation to two really flaky reviewer tests
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Review High Priority, Test process, CI

#15334 Removed the Material Dialog Box and Added Alert Box from Backup Prompt Dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
Labels: Pending Merge, squash-merge

#15374 build(ci): use stable job names
  .github/workflows/tests_unit.yml
Labels: Pending Merge

#15369 build(ci): remove `IN_PROCESS` compiler execution strategy
  build.gradle
Labels: Needs Review
