Repository ankidroid/Anki-Android, pull requests merged in 2024-11, with the labels that each got.

#17333 chore: forward-port to compileSdk 35
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
  gradle/libs.versions.toml
Labels: Needs Review, Deprecation, dependencies

#17356 Update milestone targets to 2.20
  .github/workflows/milestone.yml
Labels: Needs Review

#17177 Anki 24.10rc2 support
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserColumn.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserColumnTest.kt
  gradle/libs.versions.toml
Labels: squash-merge

#17362 Dependency updates 20241105
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: squash-merge

#17365 Make Introduction Screen Adaptable for Larger Text Sizes
  AnkiDroid/src/main/res/layout-land/introduction_layout.xml
  AnkiDroid/src/main/res/layout/introduction_layout.xml
Labels: Pending Merge

#17395 NF: Add `.attach_pid*` to gitignore
  .gitignore
Labels: Pending Merge

#17400 logs: `showError`
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Pending Merge

#17396 Fix: Activity Not found exception
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17398 fix: invalid file issue on pasting file
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17407 Fix TabLayoutMediator attached before adapter initialization in CardT…
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17371 Test that all TS backend functions are handled
  .idea/dictionaries/android.xml
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendDeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
Labels: Needs Review, Needs Second Approval, Dev, Backend Related

#17411 fix: PostRequestHandler
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
Labels: Review High Priority

#17413 fix(manage-space): crash if `getPackageSizeInfo` fails
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#17409 Fix image occlusion cards being added to wrong deck
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17422 IntentHandler decides which reviewer is used.
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
Labels: Needs Author Reply, Pending Merge

#17429 Expose exceptions thrown during caching of imported files
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt
Labels: Priority-Low, Needs Second Approval, Queued for Cherry Pick to Stable Branch

#17308 FIX: Refactored DeckPickerWidget to enable ellipsize in all fields, improving text clarity and avoiding truncation issues for a cleaner, more readable layout.
  AnkiDroid/src/main/res/layout/widget_item_deck_main.xml
Labels: Pending Merge

#17441 Handle failures to parse system WebView version
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
  AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17436 Revert lint rule changes
  AnkiDroid/src/main/AndroidManifest.xml
  lint-release.xml
  testlib/src/main/AndroidManifest.xml
Labels: Needs Review, squash-merge, New contributor

#17449 Update robolectric downloads
  AnkiDroid/robolectricDownloader.gradle
  gradle/libs.versions.toml
Labels: Pending Merge, Dev, CI, dependencies

#17457 Remove legacy collection loading code from AnkiFragment
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/layout/note_editor.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17406 fix: unable to crop shared images
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Needs Second Approval, Queued for Cherry Pick to Stable Branch

#17442 Implemented some libanki TODOs
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
Labels: Pending Merge

#17467 Fix huge image crashes, allow adding large images, fixup large image size formatting
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17473 Handle locale name being empty in preferences
  AnkiDroid/src/main/java/com/ichi2/anki/LanguageUtils.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#17479 Updated strings from Crowdin 2024/11/22 16:30
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rAR/04-network.xml
  AnkiDroid/src/main/res/values-es-rAR/06-statistics.xml
  AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rAR/08-widget.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rAR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rES/04-network.xml
  AnkiDroid/src/main/res/values-es-rES/06-statistics.xml
  AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rES/08-widget.xml
  AnkiDroid/src/main/res/values-es-rES/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/11-arrays.xml
  AnkiDroid/src/main/res/values-es-rES/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-hy/07-cardbrowser.xml
Labels: Pending Merge

#17477 chore: add triage information for unexplained startup crash
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17480 Fix more potential ActivityNotFoundExceptions
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17481 fix: avoid crash if intent sent with no extras
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17485 Dependency updates 20241123
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17482 fix: avoid crash by converting lateinit to nullable
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17470 fix: stop reporting storage access exceptions to acrarium
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
Labels: Review High Priority, Needs Second Approval, Queued for Cherry Pick to Stable Branch, 2.19

#17488 fix: use default constructor / factory + Arguments init style
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17501 Updated strings from Crowdin 2024/11/26 15:27
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-ml/08-widget.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
Labels: Pending Merge

#17496 Restore info related to cards counts in study options
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#17509 build(deps): adopt anki24.11rc2
  gradle/libs.versions.toml
Labels: Pending Merge

#17508 fix: attach custom study dialog fragment factory in SinglePageActivity to avoid crash
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch, 2.19

#17513 refactor: add/use default params for `withProgress`
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
Labels: Needs Review, cleanup, squash-merge

#17518 logs: CustomStudyDialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Labels: Priority-Low, cleanup

#17519 build: fix testlib build issues
  testlib/build.gradle.kts
Labels: Needs Review, squash-merge

#17403 Fix: DeckPicker-NullPointerException in onQueryTextChange
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval, Queued for Cherry Pick to Stable Branch, 2.19

#17510 refactor [squash]: remove CreateCustomStudySessionListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
Labels: Pending Merge, cleanup, squash-merge

#17523 test: close Scenarios after use to reduce memory pressure
  AnkiDroid/src/androidTest/java/com/ichi2/anki/FilteredDeckOptionsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
Labels: Needs Review
