Repository ankidroid/Anki-Android, pull requests merged in 2024-07, with the labels that each got.

#16587 [GSoC'24] Enhacement: Instant Editor UX improvements
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt
  AnkiDroid/src/main/res/layout/instant_editor_dialog.xml
Labels: Pending Merge, GSoC

#16689 Clarify note type ui model
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeUiModel.kt
Labels: Pending Merge

#16425 [GSoC'24] Refactor DeckPicker to Single Menu Layout
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/res/menu/deck_picker.xml
  AnkiDroid/src/main/res/menu/study_options_fragment.xml
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings, GSoC

#16718 Dependency updates 20240710
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#16684 Fix: Autoplay audio on card previews only when setting is enabled
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
Labels: Pending Merge

#16704 Fixed keyboard done button during creation or renaming of deck
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/main/res/layout/dialog_generic_text_input.xml
Labels: Pending Merge, squash-merge

#16728 Improve SliderPreference value display
  AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
  AnkiDroid/src/main/res/layout/preference_slider.xml
Labels: Pending Merge

#16727 NF: NoteEditor onKeyUp return true
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/test/java/com/ichi2/utils/KeyUtilsTest.kt
Labels: Pending Merge

#16731 Cleaning note editor related code
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Labels: Needs Second Approval

#16729 restrict deck option links
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Pending Merge

#16740 Fix Android Studio Warnings
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
Labels: Pending Merge

#16730 Fixe NPE in note editor
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#16745 [GSoC'24] Refactor: use prefill value in integer dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Labels: Pending Merge, GSoC

#16685 Remove StdModels related code
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt
  AnkiDroid/src/main/res/values/18-standard-models.xml
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
Labels: Priority-Low, Pending Merge, Strings

#16748 Adding commit of wildcards removal in ignore-revs
  .git-blame-ignore-revs
Labels: Pending Merge

#16754 refactor(note-editor): improve nullability
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#16752 Change conflicts workflow to allow more PRs to be checked
  .github/workflows/conflict.yaml
Labels: Needs Second Approval

#16572 Small cleaning of codes
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
Labels: Pending Merge

#16736 [GSoC'24] Refactor: cloze builder pattern for words
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
Labels: Pending Merge, GSoC

#16755 Dependency updates 20240718
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Pending Merge, squash-merge

#16735 [GSoC'24] Enhancement: add long press listener on cloze button
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings, GSoC

#16759 Remove "app.brant.amazonappstorepublisher" plugin
  AnkiDroid/build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Needs Second Approval

#16763 fix: "MissingDefaultResource" lint: `iw`
  lint-release.xml
Labels: Review High Priority

#16738 Fix: update set due date card snackbar
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#16757 Dynamicaly set in sentence case... Flag,Toggle Witeboard,Abort Learning
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
  AnkiDroid/src/main/res/values/sentence-case.xml
Labels: Pending Merge

#16765 fix: `Processing...` popup in app startup
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#16760 [GSoC'24] Feature: enable instant editor for public use
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Pending Merge, GSoC

#16771 improve deleted deck message
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#16750 [GSoC'24] Refactor: Consolidate media paths into a single variable
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/MediaClipTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Labels: Needs Second Approval, GSoC

#16773 Make newer "Gallery" labels translatable from Crowdin
  AnkiDroid/src/main/res/layout/bottomsheet_multimedia.xml
  AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
Labels: Pending Merge

#16783 [GSoC'24] rename pager
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
  AnkiDroid/src/main/res/layout/card_template_editor_activity.xml
  AnkiDroid/src/main/res/layout/dialog_set_due_date.xml
Labels: Needs Review, GSoC

#16545 [GSoC'24] Introducing AnalyticsWidgetProvider as ancestor of all widget classes.
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/test/java/com/ichi2/anki/widget/AnalyticalWidgetProviderTest.kt
Labels: Needs Second Approval, GSoC

#16779 [GSoC'24] Fix: cloze number incorrect on undo
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
Labels: Pending Merge, GSoC

#16722 [GSoC'24] CardTemplateEditor: Implementation of Keyboard Shortcuts
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Needs Second Approval, GSoC

#16712 [GSoC'24] Add Right-Click Support to Long Click Listeners
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
Labels: Needs Second Approval, GSoC
