Repository ankidroid/Anki-Android, pull requests merged in 2024-09, with the labels that each got.

#17009 Change donate icon to heart
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
  AnkiDroid/src/main/res/drawable/ic_donate_black_24dp.xml
  AnkiDroid/src/main/res/drawable/ic_round_favorite_24.xml
Labels: Pending Merge

#17007 Fix: Ensure "Media Sync Aborted" Message Displays Correctly After Canceling Media Sync
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
Labels: Needs Second Approval

#17006 fix menu in template editor
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/res/layout-xlarge/card_template_editor.xml
  AnkiDroid/src/main/res/layout/card_template_editor.xml
  AnkiDroid/src/main/res/layout/card_template_editor_top.xml
Labels: Needs Second Approval

#17008 add filtered deck option to browser
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/res/menu/card_browser.xml
Labels: Pending Merge

#16958 Notify the UI that a sync was done
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt
Labels: Pending Merge

#17027 refactor: remove dead code
  AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
Labels: Priority-Low, Pending Merge, cleanup

#17004 Dependency updates 20240830
  .github/workflows/compare_apk_size.yml
  .github/workflows/lint.yml
  .github/workflows/tests_emulator.yml
  .github/workflows/tests_unit.yml
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17043 docs(bug-report): improve link to issues
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: Pending Merge

#17047 fix export menu item
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#17046 fix filtered decks not appearing in browser deck selection dialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
Labels: Needs Second Approval

#17032 docs(opencollective): note that the payment process has been updated
  .github/workflows/opencollective_notices.yml
Labels: Pending Merge, Dev, squash-merge

#17071 Dependency updates 20240916
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/VideoPlayerTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#17016 remove all cards count subtitle
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#16994 Note editor back button request confirmation only in case of change
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#17036 fix: Single review activity instance
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
Labels: Pending Merge

#15648 Feature: Allow changing deck name in statistics screen
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/res/layout/item_stats_deck.xml
  AnkiDroid/src/main/res/layout/statistics.xml
Labels: Pending Merge

#17088 partial fix for flaky test: `testLoadSavedPreferences`
  AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
  AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt
  AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge

#17061 fix: export option dialog have text overlapping issue and last checkbox is not visible in landscope mode
  AnkiDroid/src/main/res/layout/dialog_export_options.xml
Labels: UI, Pending Merge

#17134 Fix android studio warnings - AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
Labels: Pending Merge, New contributor

#17106 Clarify the reviewer window title
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#17137 Dependency updates 20240925
  AnkiDroid/src/main/java/com/ichi2/compat/PackageManagerCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, squash-merge

#17102 Upper case to "cards selected by"
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Pending Merge, Strings

#17139 fix: match tag control label to actual action
  AnkiDroid/src/main/res/xml/preferences_controls.xml
Labels: Pending Merge

#17136 fix(deck-download): handle "Daily limit exceeded; please try again tomorrow." correctly
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Labels: Pending Merge

#17117 Rephrase "Abort learning"
  AnkiDroid/src/main/res/values/11-arrays.xml
Labels: Pending Merge, Strings

#17105 "+n buried" becomes `plurals`
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#16714 refactor: mount receivers
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Labels: Pending Merge

#17125 Enable searching for backups related settings
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_backup_limits.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
Labels: Needs Second Approval

#17115 Fix notetype field not being used as sort field
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
Labels: Needs Second Approval

#17146 Fix inconsistent Toolbar background color
  AnkiDroid/src/main/res/layout/locale_selection_dialog.xml
Labels: Needs Second Approval

#17161 Improve Manage note type with big text
  AnkiDroid/src/main/res/layout/item_manage_note_type.xml
Labels: Pending Merge

#17165 fix: multimedia bottomsheet nav bar color transparency
  AnkiDroid/src/main/res/values/styles.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
Labels: Pending Merge

#17164 improvement(lint): 'TranslationTypo' - link to Crowdin
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/Crowdin.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/utils/CrowdinLanguageTagTest.kt
  tools/localization/src/update.ts
Labels: Pending Merge

#17167 Make browser options scrollable for larger text size.
  AnkiDroid/src/main/res/layout/browser_options_dialog.xml
Labels: Pending Merge

#17141 feat: show discard dialog in case multimedia changes
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioRecordingFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Pending Merge

#17121 Language name starts with a upper case
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Labels: Needs Author Reply, Needs Second Approval

#17169 lint: better link to Crowdin
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
Labels: Pending Merge
