Repository ankidroid/Anki-Android, pull requests merged in 2025-09, with the labels that each got.

#19166 Update active decks related methods with backend code
  libanki/src/main/java/com/ichi2/anki/libanki/Decks.kt
  libanki/src/main/java/com/ichi2/anki/libanki/sched/Scheduler.kt
Labels: Pending Merge

#19199 feat(new study screen): replay media command/menu action
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/res/values/ids.xml
Labels: Pending Merge

#19203 Fix crash in ControlSettingsFragment due to required browse/statistics preferences
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
Labels: Needs Review

#19228 fix(study screen): zoom
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
Labels: Pending Merge

#19232 Fix changing the deck of cards in browser
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt
Labels: Pending Merge

#19258 Updated strings from Crowdin 2025/09/21 16:32
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
  AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
Labels: Pending Merge

#19266 fix: stop FAB from covering review reminders
  AnkiDroid/src/main/res/layout/fragment_schedule_reminders.xml
Labels: Pending Merge, GSoC

#19265 fix: respect 24h time display preference
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleRemindersAdapter.kt
Labels: Pending Merge, GSoC

#19280 style: decrease ScheduleReminders font size
  AnkiDroid/src/main/res/layout/schedule_reminders_list_item.xml
Labels: Pending Merge, GSoC

#19275 refactor: clear empty review reminder maps
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt
Labels: Needs Review, GSoC

#19276 feat(reminders): canUserAccessDeck
  AnkiDroid/src/main/java/com/ichi2/anki/DeckUtils.kt
  libanki/src/main/java/com/ichi2/anki/libanki/Decks.kt
Labels: Pending Merge, GSoC
