Repository ankidroid/Anki-Android, pull requests merged in 2025-03, with the labels that each got.

#18040 Updated strings from Crowdin 2025/03/02 08:32
  AnkiDroid/src/main/res/values-ar/08-widget.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ka/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/04-network.xml
  AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/08-widget.xml
  AnkiDroid/src/main/res/values-ka/09-backup.xml
  AnkiDroid/src/main/res/values-ka/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/11-arrays.xml
  AnkiDroid/src/main/res/values-ka/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ka/17-model-manager.xml
  AnkiDroid/src/main/res/values-ko/01-core.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/04-network.xml
  AnkiDroid/src/main/res/values-ko/05-feedback.xml
  AnkiDroid/src/main/res/values-ko/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ko/08-widget.xml
  AnkiDroid/src/main/res/values-ko/09-backup.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-ko/11-arrays.xml
  AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ko/17-model-manager.xml
  AnkiDroid/src/main/res/values-ko/18-standard-models.xml
  AnkiDroid/src/main/res/values-ko/20-search-preference.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
Labels: Pending Merge

#18045 fix: change local variables from var to val
  AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FieldTest.kt
Labels: New contributor

#18042 [Cleanup]: Remove Android Studio Warning
  AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt
Labels: Pending Merge, New contributor

#18043 fix(new reviewer): snackbar position if answer buttons are hidden
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
  AnkiDroid/src/main/res/layout/reviewer2.xml
Labels: Needs Second Approval

#18017 refactor: move Reviewer menu logic to a Repository class
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/MenuDisplayType.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuRepository.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuView.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/reviewer/MenuDisplayTypeTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuRepositoryTest.kt
Labels: Pending Merge

#18068 Updated strings from Crowdin 2025/03/07 17:47
  AnkiDroid/src/main/res/values-de/01-core.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-or/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-or/08-widget.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
Labels: Pending Merge

#18072 NF: set "play" variant as default
  AnkiDroid/build.gradle
Labels: Pending Merge

#18071 Added Background Remove Option
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_appearance.xml
Labels: Pending Merge, Strings

#18027 fix: "Toggle whiteboard" control icon & label do not match
  AnkiDroid/src/main/res/xml/preferences_controls.xml
Labels: Pending Merge

#18083 Replace getColUnsafe with withCol
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#18087 minor fix: remove extra space in newer string
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#18092 lint: fix trailing spaces in /values
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/17-model-manager.xml
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt
Labels: Pending Merge, Strings

#18099 test(preferences): add unit tests for getOrSetLong logic
  AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
Labels: Pending Merge

#18066 fixed the The anki card menu can't be found from the search bar..
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: squash-merge, New contributor

#18116 Updated strings from Crowdin 2025/03/16 16:13
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/06-statistics.xml
  AnkiDroid/src/main/res/values-da/01-core.xml
  AnkiDroid/src/main/res/values-de/01-core.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-ga/01-core.xml
  AnkiDroid/src/main/res/values-ga/03-dialogs.xml
  AnkiDroid/src/main/res/values-gu/01-core.xml
  AnkiDroid/src/main/res/values-hi/01-core.xml
  AnkiDroid/src/main/res/values-hu/02-strings.xml
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-kn/01-core.xml
  AnkiDroid/src/main/res/values-ml/01-core.xml
  AnkiDroid/src/main/res/values-mr/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rPT/17-model-manager.xml
  AnkiDroid/src/main/res/values-sat/01-core.xml
  AnkiDroid/src/main/res/values-sat/02-strings.xml
  AnkiDroid/src/main/res/values-ta/01-core.xml
  AnkiDroid/src/main/res/values-te/01-core.xml
  AnkiDroid/src/main/res/values-tg/01-core.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tt/01-core.xml
  AnkiDroid/src/main/res/values-ur/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/17-model-manager.xml
  AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
Labels: Pending Merge

#17351 Manual-Download-link
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
  AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/constants.xml
  AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt
Labels: Needs Second Approval, Strings, squash-merge, New contributor, Needs reviewer reply

#18115 NF: rename `modelId` to `noteTypeId`
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Labels: Pending Merge

#18111 NF: Rename model to note type in android tests
  AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/NoteTypeEditorContextMenuTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/NotetypeTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteTypeEditorContextMenu.kt
Labels: Pending Merge

#18097 Move file deletion on background thread
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
Labels: Pending Merge

#18135 Updated strings from Crowdin 2025/03/18 18:06
  AnkiDroid/src/main/res/values-be/03-dialogs.xml
  AnkiDroid/src/main/res/values-ca/03-dialogs.xml
  AnkiDroid/src/main/res/values-ca/10-preferences.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-fa/02-strings.xml
  AnkiDroid/src/main/res/values-fa/09-backup.xml
  AnkiDroid/src/main/res/values-gu/01-core.xml
  AnkiDroid/src/main/res/values-hi/10-preferences.xml
  AnkiDroid/src/main/res/values-hu/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ko/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-mr/01-core.xml
  AnkiDroid/src/main/res/values-nl/02-strings.xml
  AnkiDroid/src/main/res/values-nl/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/01-core.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  AnkiDroid/src/main/res/values-sat/02-strings.xml
  AnkiDroid/src/main/res/values-sat/03-dialogs.xml
  AnkiDroid/src/main/res/values-sat/10-preferences.xml
  AnkiDroid/src/main/res/values-sc/02-strings.xml
  AnkiDroid/src/main/res/values-sc/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-vi/02-strings.xml
  AnkiDroid/src/main/res/values-vi/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Labels: Pending Merge

#18141 fix: Kotlin 2.1.20 Upgrade Errors
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
Labels: Pending Merge

#18142 Remove unused code from BackupManager
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
Labels: Priority-Low, cleanup

#18136 fix(lint-crowdin): more links to translations
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/Crowdin.kt
Labels: Pending Merge

#18096 Enforce user-facing locale checks via lint; fixes #8917
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AxisValueDisplay.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
  lint-release.xml
  lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/rules/LocaleRootDetector.kt
  lint-rules/src/test/java/com/ichi2/anki/lint/rules/LocaleRootDetectorTest.kt
Labels: Needs Second Approval, New contributor

#18104 Fixed android studio warning, converting toSet for performance
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt
Labels: Pending Merge, squash-merge, New contributor

#18148 Updated strings from Crowdin 2025/03/23 17:42
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/03-dialogs.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-heb/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-heb/10-preferences.xml
  AnkiDroid/src/main/res/values-heb/17-model-manager.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/03-dialogs.xml
  AnkiDroid/src/main/res/values-iw/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-iw/10-preferences.xml
  AnkiDroid/src/main/res/values-iw/17-model-manager.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-ko/02-strings.xml
  AnkiDroid/src/main/res/values-ko/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ko/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/17-model-manager.xml
Labels: Pending Merge

#18056 Only show Backup prompt dialog if there is no one-way or auto sync at startup
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge

#18147 Showing Badge for Blank Card Fronts in Previewer
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/previewer/TemplatePreviewerViewModelTest.kt
Labels: Pending Merge, New contributor

#18038 Remove warning
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/AcraAnalyticsInteraction.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
Labels: Pending Merge, New contributor

#18163 build(deps): adopt latest Anki-Android-Backend 0.1.52-anki25.02
  gradle/libs.versions.toml
Labels: Pending Merge

#18170 fix: remove unused line in reviewer2.xml
  AnkiDroid/src/main/res/layout/reviewer2.xml
Labels: Pending Merge

#17887 Refactored de-duplicate .csv/.tsv values both in IntentHandler and in ImportFileSelectionFragment.
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/MimeTypeUtils.kt
Labels: Pending Merge, New contributor

#18179 Add utility method for setting a fragment result listener in a FragmentActivity
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/FindAndReplaceDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/FragmentResult.kt
Labels: Priority-Low, Pending Merge, cleanup
