Repository ankidroid/Anki-Android, pull requests merged in 2025-02, with the labels that each got.

#17874 Fix: Enable sharing .txt files for import in AnkiDroid
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
Labels: Pending Merge

#17914 Fix more ActivityNotFoundExceptions
  AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt
  AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
Labels: Needs Review

#17905 DeckOption become closable if it's not loaded
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Pending Merge

#17916 Updated strings from Crowdin 2025/02/04 16:28
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-es-rAR/20-search-preference.xml
  AnkiDroid/src/main/res/values-fi/01-core.xml
  AnkiDroid/src/main/res/values-fi/02-strings.xml
  AnkiDroid/src/main/res/values-fi/03-dialogs.xml
  AnkiDroid/src/main/res/values-fi/04-network.xml
  AnkiDroid/src/main/res/values-fi/06-statistics.xml
  AnkiDroid/src/main/res/values-fi/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fi/08-widget.xml
  AnkiDroid/src/main/res/values-fi/09-backup.xml
  AnkiDroid/src/main/res/values-fi/10-preferences.xml
  AnkiDroid/src/main/res/values-fi/11-arrays.xml
  AnkiDroid/src/main/res/values-fi/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fi/20-search-preference.xml
  AnkiDroid/src/main/res/values-heb/01-core.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-heb/10-preferences.xml
  AnkiDroid/src/main/res/values-iw/01-core.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-iw/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ka/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/04-network.xml
  AnkiDroid/src/main/res/values-ka/06-statistics.xml
  AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/08-widget.xml
  AnkiDroid/src/main/res/values-ka/10-preferences.xml
  AnkiDroid/src/main/res/values-ka/11-arrays.xml
  AnkiDroid/src/main/res/values-ru/01-core.xml
  AnkiDroid/src/main/res/values-ru/02-strings.xml
  AnkiDroid/src/main/res/values-ru/03-dialogs.xml
  AnkiDroid/src/main/res/values-ru/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ru/10-preferences.xml
  AnkiDroid/src/main/res/values-ru/11-arrays.xml
  AnkiDroid/src/main/res/values-ug/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/08-widget.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  docs/marketing/localized_description/marketdescription-uk.txt
Labels: Pending Merge

#17923 Updated strings from Crowdin 2025/02/07 09:16
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fil/01-core.xml
  AnkiDroid/src/main/res/values-fil/02-strings.xml
Labels: Pending Merge

#17856 Don't allow empty name in flag
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt
Labels: Pending Merge

#17852 Fix getsize() and getMetrics deprecations
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt
Labels: Pending Merge

#17792 Add Auto-Scroll Support for RecyclerView in Multiselect View
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#17938 Updated strings from Crowdin 2025/02/08 09:07
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
Labels: Pending Merge

#17900 enhancement: improve reposition field dialog
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/res/values/17-model-manager.xml
Labels: Pending Merge, Strings

#17919 Enable full report about empty cards
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
  AnkiDroid/src/main/res/layout/dialog_empty_cards.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
Labels: Pending Merge, Strings

#17926 refactor: use Android's minTouchTargetSize
  AnkiDroid/src/main/res/layout/browser_columns_selection_entry.xml
  AnkiDroid/src/main/res/layout/note_editor.xml
  AnkiDroid/src/main/res/layout/reviewer2.xml
  AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
  AnkiDroid/src/main/res/layout/sync_progress_layout.xml
  AnkiDroid/src/main/res/values/dimens.xml
Labels: Priority-Low, Needs Second Approval, cleanup

#17904 Fix: Card Browser Border and Header Height.
  AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
  AnkiDroid/src/main/res/drawable/browser_heading_bottom_divider.xml
  AnkiDroid/src/main/res/layout/browser_column_cell.xml
  AnkiDroid/src/main/res/layout/browser_column_divider.xml
  AnkiDroid/src/main/res/layout/browser_column_heading.xml
  AnkiDroid/src/main/res/layout/card_browser.xml
Labels: Needs Second Approval

#17936 fix: instant note editor tap mode inconsistency
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
Labels: Needs Second Approval

#17940 fix(new reviewer): box frame style bottom margin
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Layout.kt
  AnkiDroid/src/main/res/layout/reviewer2.xml
Labels: Pending Merge

#17942 fix(settings): disable ignoreDisplayCutout when necessary
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt
Labels: Pending Merge

#17930 fix(sync): notification getting stuck
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
Labels: Pending Merge

#17932 fix(preferences): status bar color
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
Labels: Pending Merge

#17945 Updated strings from Crowdin 2025/02/09 13:24
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/06-statistics.xml
  AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
Labels: Pending Merge

#17925 refactor: add `Destination` interface
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfoDestination.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Destination.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge

#17935 fix: instant note editor to restore text when orientation changes
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
Labels: Pending Merge

#17951 fix(new reviewer): suspend/bury submenus
  AnkiDroid/proguard-rules.pro
Labels: Pending Merge

#17953 Correct matchesJsonValue
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt
Labels: Needs Second Approval

#17842 feat: Improve Check Media dialog
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/res/layout/media_check_dialog_body.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/sentence-case.xml
Labels: Needs Second Approval, Strings, squash-merge

#17958 Dependency updates 20250210
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#17960 feat: Allow fine tuning of the unbury action in congrats screen
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
Labels: Pending Merge

#17966 Fix : Deck Picker Arrow doesn't rotate on expanding and collapsing the deck.
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
Labels: Pending Merge

#17973 Updated strings from Crowdin 2025/02/13 22:55
  AnkiDroid/src/main/res/values-es-rAR/01-core.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/01-core.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rES/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
Labels: Pending Merge

#17962 Enable feature complete repositioning of new cards
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/RepositionCardFragment.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/main/res/layout/fragment_reposition_card.xml
  AnkiDroid/src/main/res/values/03-dialogs.xml
  AnkiDroid/src/main/res/values/sentence-case.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge, Strings

#17971 Fixes #17970 - Pass DeckId to NoteEditor From Snackbar
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#17978 fixup: improve ControlPreference style
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
  AnkiDroid/src/main/res/layout/control_preference.xml
  AnkiDroid/src/main/res/layout/control_preference_list_item.xml
Labels: Needs Review

#17988 bump: update searchpreference version to 2.7.1 and fix#17967
  gradle/libs.versions.toml
Labels: Pending Merge

#17961 Added fallback-release-keystore.jks file as a fallback for release builds
  .github/workflows/tests_emulator.yml
  AnkiDroid/build.gradle
  tools/fallback-release-keystore.jks
Labels: Needs Author Reply

#17964 NF: Correct `reps` documentation
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
Labels: Pending Merge

#17990 build(deps): adopt backend 1.51-anki25.02
  gradle/libs.versions.toml
Labels: Needs Review

#17991 Dependency updates 20250216
  gradle/libs.versions.toml
Labels: Pending Merge, squash-merge

#17985 Fix color scheme for empty cards report dialog
  .idea/dictionaries/android.xml
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
  AnkiDroid/src/main/res/layout/dialog_empty_cards.xml
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/EmptyCardsReportTest.kt
Labels: Pending Merge

#17995 docs: showManageAllFilesScreen error case
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
Labels: Priority-Low, Needs Review

#17957 NF: remove TODO comment
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
Labels: Needs Review

#17986 Refactor: Card Analysis Widget for more clean look.
  AnkiDroid/src/main/res/layout/widget_card_analysis.xml
  AnkiDroid/src/main/res/layout/widget_card_analysis_drawable_v31.xml
  AnkiDroid/src/main/res/xml/widget_provider_card_analysis.xml
Labels: Widget, Needs Second Approval

#17987 fix:focus keyboard on edit description dialog
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt
Labels: Pending Merge

#17997 fix: Top side of card is cut off when "Center align" enabled & content is long
  AnkiDroid/src/main/assets/flashcard.css
Labels: Pending Merge

#18023 Updated strings from Crowdin 2025/02/25 14:13
  AnkiDroid/src/main/res/values-de/11-arrays.xml
  AnkiDroid/src/main/res/values-fr/01-core.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fr/11-arrays.xml
  AnkiDroid/src/main/res/values-km/01-core.xml
  AnkiDroid/src/main/res/values-km/02-strings.xml
  AnkiDroid/src/main/res/values-km/03-dialogs.xml
  AnkiDroid/src/main/res/values-km/04-network.xml
  AnkiDroid/src/main/res/values-km/05-feedback.xml
  AnkiDroid/src/main/res/values-km/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-km/08-widget.xml
  AnkiDroid/src/main/res/values-km/09-backup.xml
  AnkiDroid/src/main/res/values-km/10-preferences.xml
  AnkiDroid/src/main/res/values-km/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
Labels: Pending Merge

#17795 JS function to setTags and getTags
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge

#18022 Fix SharedDecksActivity toolbar color for dark themes
  AnkiDroid/src/main/res/layout/activity_shared_decks.xml
Labels: Pending Merge
