Repository ankidroid/Anki-Android, pull requests merged in 2025-08, with the labels that each got.

#19015 Fix: Disable 'E' edit shortcut in CardBrowser split mode to prevent unwanted save dialog
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge

#19024 Add logging for crowdin project languages
  tools/localization/src/download.ts
Labels: Pending Merge

#19027 Fix crowdin languages access
  tools/localization/src/download.ts
Labels: Needs Second Approval

#19035 Updated strings from Crowdin 2025/08/03 02:32
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ar/11-arrays.xml
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ar/17-model-manager.xml
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/10-preferences.xml
  AnkiDroid/src/main/res/values-or/01-core.xml
  AnkiDroid/src/main/res/values-or/02-strings.xml
  AnkiDroid/src/main/res/values-or/03-dialogs.xml
  AnkiDroid/src/main/res/values-or/04-network.xml
  AnkiDroid/src/main/res/values-or/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-or/08-widget.xml
  AnkiDroid/src/main/res/values-or/10-preferences.xml
  AnkiDroid/src/main/res/values-or/11-arrays.xml
  AnkiDroid/src/main/res/values-or/17-model-manager.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/01-core.xml
  AnkiDroid/src/main/res/values-uk/02-strings.xml
  AnkiDroid/src/main/res/values-uk/03-dialogs.xml
  AnkiDroid/src/main/res/values-uk/05-feedback.xml
  AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uk/08-widget.xml
  AnkiDroid/src/main/res/values-uk/09-backup.xml
  AnkiDroid/src/main/res/values-uk/10-preferences.xml
  AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-uk/17-model-manager.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-or.txt
  docs/marketing/localized_description/marketdescription-uk.txt
Labels: Pending Merge

#19020 feat(filtered-decks): Sort by ascending/descending retrievability
  AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
  libanki/src/main/java/com/ichi2/anki/libanki/Deck.kt
Labels: Pending Merge, Strings

#19011 refactor(new study screen): extract menu setup
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerMenu.kt
Labels: Pending Merge

#18951 fix: hide save button in fragmented activity to prevent duplication
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge, GSoC

#19051 chore(field-editor): add layout preview
  AnkiDroid/src/main/res/layout/note_type_field_editor.xml
Labels: Pending Merge, cleanup

#19047 refactor: prepare AnkiActivity for review reminders
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
Labels: Needs Second Approval, GSoC

#19055 fix(deck-picker): hide resizing divider when collection is empty
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
Labels: Pending Merge, GSoC

#19046 Indicate a field that is used to sort notes.
  AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
  AnkiDroid/src/main/res/drawable/ic_sort.xml
  AnkiDroid/src/main/res/layout/note_type_field_editor_list_item.xml
Labels: Pending Merge, squash-merge, New contributor

#19058 improvement(libanki-collection): upstream DB maintenance code
  libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
Labels: Pending Merge

#19070 refactor(card-browser): extract 'save search' to ViewModel
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge

#19114 refactor: delete ReminderService
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge, GSoC

#19106 fix(resizable-pane): prevent parent from intercepting touch events during resizing drag
  AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizablePaneManager.kt
Labels: Pending Merge, GSoC

#19133 Remove fragmented parameter from DeckPickerViewModel
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/deckpicker/DeckPickerViewModelTest.kt
Labels: Pending Merge

#19135 logs: trashFiles
  libanki/src/main/java/com/ichi2/anki/libanki/Media.kt
Labels: Pending Merge

#19137 fix(tests): flaky test
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Labels: Pending Merge

#19115 feat(reminders): create global scope helper
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Labels: Needs Second Approval, GSoC

#18856 feat(reminders): ReviewReminder schema migration
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt
Labels: Needs Second Approval, GSoC

#19155 chore: add support for vibration USAGE
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/AudioRecordView.kt
  AnkiDroid/src/main/java/com/ichi2/compat/BaseCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
  AnkiDroid/src/main/java/com/ichi2/compat/VibrationAttributesCompat.kt
Labels: Needs Second Approval

#19146 Fix study finish snackbar not appearing in tablet mode
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Pending Merge
