Repository ankidroid/Anki-Android, pull requests merged in 2025-04, with the labels that each got.

#18195 Dependency updates 20250402
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#18196 Updated strings from Crowdin 2025/04/02 11:51
  AnkiDroid/src/main/res/values-cs/01-core.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/03-dialogs.xml
  AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/17-model-manager.xml
  AnkiDroid/src/main/res/values-gu/01-core.xml
  AnkiDroid/src/main/res/values-gu/02-strings.xml
  AnkiDroid/src/main/res/values-gu/06-statistics.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-pl/01-core.xml
  AnkiDroid/src/main/res/values-pl/02-strings.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/06-statistics.xml
  AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pl/08-widget.xml
  AnkiDroid/src/main/res/values-pl/10-preferences.xml
  AnkiDroid/src/main/res/values-pl/11-arrays.xml
  AnkiDroid/src/main/res/values-pl/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-pl/17-model-manager.xml
  AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/02-strings.xml
  AnkiDroid/src/main/res/values-ug/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-ug/17-model-manager.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
  docs/marketing/localized_description/marketdescription-pl.txt
Labels: Pending Merge

#18172 Fix memory leak by stopping server in pageFragment by onDestroy
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
Labels: Pending Merge, New contributor

#17877 feat: allow pasting images as png
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Needs Second Approval, Strings, squash-merge

#18198 test: ignore flaky tests
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#18190 feat: use `NotificationChannelCompat.Builder` for channel creation
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
  AnkiDroid/src/main/java/com/ichi2/compat/BaseCompat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
Labels: Pending Merge

#18207 Fix Android Studio warnings in `PageFragment.kt`
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
Labels: Pending Merge, New contributor

#18201 fix: freeze when syncing when notifications permission is missing
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
  AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
Labels: Pending Merge

#18204 Fix Android Studio Warnings in InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
Labels: Pending Merge, New contributor

#18200 Refactor $PRE_RELEASE to $RELEASE_TYPE & fix SC2088
  .github/workflows/publish.yml
  tools/release.sh
Labels: Pending Merge

#18175 Add mathjax block and mathjax chemistry
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Labels: Pending Merge, New contributor

#18057 Managed back stack for parent fragments in the app settings
  AnkiDroid/src/androidTest/java/com/ichi2/anki/preferences/PreferencesNavigationTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Pending Merge, New contributor

#18144 Duplicate Due column Fix
  AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Pending Merge

#18214 Updated strings from Crowdin 2025/04/06 08:45
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-cs/03-dialogs.xml
  AnkiDroid/src/main/res/values-cs/06-statistics.xml
  AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-cs/08-widget.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/17-model-manager.xml
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-de/03-dialogs.xml
  AnkiDroid/src/main/res/values-de/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-de/10-preferences.xml
  AnkiDroid/src/main/res/values-de/17-model-manager.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rAR/17-model-manager.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rES/17-model-manager.xml
  AnkiDroid/src/main/res/values-gl/01-core.xml
  AnkiDroid/src/main/res/values-gl/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#18208 Converted previewer empty front indicator to text
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings

#18180 Refactor locale selection dialog
  .idea/dictionaries/davidallison.xml
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/ui/RecyclerSingleTouchAdapter.kt
  AnkiDroid/src/main/res/layout/locale_dialog_fragment_textview.xml
  AnkiDroid/src/main/res/layout/locale_selection_dialog.xml
Labels: Priority-Low, Pending Merge

#18209 fix: axis picker
  AnkiDroid/src/main/res/layout/dialog_axis_picker.xml
Labels: Pending Merge

#18213 fix: dismiss axis dialog after selecting
  AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Labels: Needs Second Approval

#18162 Fix background image visibility based on collection state #18073
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge, squash-merge

#18007 Fixed the empty regular deck check, now uses foreach to check all the…
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
Labels: Pending Merge, New contributor

#18226 Updated strings from Crowdin 2025/04/13 08:57
  AnkiDroid/src/main/res/values-gl/01-core.xml
  AnkiDroid/src/main/res/values-gl/02-strings.xml
  AnkiDroid/src/main/res/values-gl/03-dialogs.xml
  AnkiDroid/src/main/res/values-gl/04-network.xml
  AnkiDroid/src/main/res/values-gl/05-feedback.xml
  AnkiDroid/src/main/res/values-gl/06-statistics.xml
  AnkiDroid/src/main/res/values-gl/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/20-search-preference.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#18236 Updated strings from Crowdin 2025/04/19 05:41
  AnkiDroid/src/main/res/values-de/02-strings.xml
  AnkiDroid/src/main/res/values-gl/02-strings.xml
  AnkiDroid/src/main/res/values-gl/03-dialogs.xml
  AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-gl/18-standard-models.xml
  AnkiDroid/src/main/res/values-lv/01-core.xml
  AnkiDroid/src/main/res/values-lv/02-strings.xml
  AnkiDroid/src/main/res/values-lv/03-dialogs.xml
  AnkiDroid/src/main/res/values-lv/04-network.xml
  AnkiDroid/src/main/res/values-lv/05-feedback.xml
  AnkiDroid/src/main/res/values-lv/06-statistics.xml
  AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-lv/08-widget.xml
  AnkiDroid/src/main/res/values-lv/09-backup.xml
  AnkiDroid/src/main/res/values-lv/10-preferences.xml
  AnkiDroid/src/main/res/values-lv/11-arrays.xml
  AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-lv/17-model-manager.xml
  AnkiDroid/src/main/res/values-lv/18-standard-models.xml
  AnkiDroid/src/main/res/values-lv/20-search-preference.xml
  AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
  AnkiDroid/src/main/res/values-th/01-core.xml
  AnkiDroid/src/main/res/values-th/02-strings.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-ug/02-strings.xml
  AnkiDroid/src/main/res/values-ug/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
Labels: Pending Merge

#18239 NF: rename model in files related to editors
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Labels: Pending Merge

#18250 fix: Updated visibility for buried card counts in Study Options
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Labels: Pending Merge

#18257 Updated strings from Crowdin 2025/04/27 09:34
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/03-dialogs.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/11-arrays.xml
  AnkiDroid/src/main/res/values-fr/02-strings.xml
  AnkiDroid/src/main/res/values-fr/17-model-manager.xml
  AnkiDroid/src/main/res/values-ka/01-core.xml
  AnkiDroid/src/main/res/values-ka/02-strings.xml
  AnkiDroid/src/main/res/values-ka/03-dialogs.xml
  AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ka/10-preferences.xml
  AnkiDroid/src/main/res/values-lv/01-core.xml
  AnkiDroid/src/main/res/values-lv/02-strings.xml
  AnkiDroid/src/main/res/values-lv/03-dialogs.xml
  AnkiDroid/src/main/res/values-lv/04-network.xml
  AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-lv/08-widget.xml
  AnkiDroid/src/main/res/values-lv/10-preferences.xml
  AnkiDroid/src/main/res/values-lv/11-arrays.xml
  AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-pt-rBR/17-model-manager.xml
  AnkiDroid/src/main/res/values-ro/01-core.xml
  AnkiDroid/src/main/res/values-ro/03-dialogs.xml
  docs/marketing/localized_description/marketdescription-lv.txt
Labels: Pending Merge

#18004 NoteTypeJson becomes a value class
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/NotetypeTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/TypeAnswer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/NoteTypeSpinnerUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CardTemplates.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Field.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
  AnkiDroid/src/main/java/com/ichi2/utils/NamedJSONComparator.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/NoteWithColTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
Labels: Pending Merge, squash-merge

#18113 NF: rename `model` into `noteType` in unit tests
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
Labels: Pending Merge

#18171 Add sorting by deck name to card browser
  AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Pending Merge, Strings
