Repository ankidroid/Anki-Android, pull requests merged in 2025-05, with the labels that each got.

#18260 Fix AlertDialog background color for black theme
  AnkiDroid/src/main/res/values/theme_black.xml
Labels: Pending Merge

#17917 Fix: Added robust keyboard visibility detection using WindowInsetsCompat.
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Review, Needs Second Approval

#18256 Add a dev option to add useless note
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Needs Second Approval

#18295 Dependency updates 20250509
  .github/workflows/lint.yml
  AnkiDroid/jacoco.gradle
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge

#18272 fix(card-template-editor): change Ctrl+A to Ctrl+N
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#18203 refactor: move time utils to common
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
  AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
  common/src/main/java/com/ichi2/anki/common/time/SystemTime.kt
  common/src/main/java/com/ichi2/anki/common/time/Time.kt
  common/src/main/java/com/ichi2/anki/common/time/TimeManager.kt
Labels: Needs Second Approval

#18300 build(deps): adopt anki upstream 25.02.4
  gradle/libs.versions.toml
Labels: Pending Merge, dependencies

#18269 Escape quotes in the deck name for card browser's search syntax
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge

#18268 Fix the handling of quotes while renaming a deck
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Labels: Pending Merge

#18274 fix(new reviewer): default keybinds
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
Labels: Pending Merge

#18310 Replace dp conversion utilities with Dp class
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/snackbar/SensibleSwipeDismissBehavior.kt
  AnkiDroid/src/main/java/com/ichi2/ui/AxisValueDisplay.kt
  AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
  AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt
Labels: Priority-Low, Pending Merge, cleanup

#18183 fix:bottom alignment
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#18305 Cause gesture to ask on which side it is executed
  AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
Labels: Pending Merge

#18330 Updated strings from Crowdin 2025/05/17 07:26
  AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fr/03-dialogs.xml
  AnkiDroid/src/main/res/values-fr/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-fr/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-gl/08-widget.xml
  AnkiDroid/src/main/res/values-gl/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/11-arrays.xml
  AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-lv/02-strings.xml
  AnkiDroid/src/main/res/values-lv/03-dialogs.xml
  AnkiDroid/src/main/res/values-nl/01-core.xml
  AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml
  docs/marketing/localized_description/marketdescription-eo.txt
  docs/marketing/localized_description/marketdescription-fr.txt
  docs/marketing/localized_description/marketdescription-gl.txt
  docs/marketing/localized_description/marketdescription-tr.txt
Labels: Pending Merge

#18321 fix(reposition-dialog): adds ScrollView to dialog
  AnkiDroid/src/main/res/layout/fragment_reposition_card.xml
Labels: Pending Merge

#18277 chore(libanki): update Tags methods
  AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
Labels: Pending Merge

#18336 refactor: use `CheckMediaResponse` instead of custom data class
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
Labels: Pending Merge

#18328 feat(card-browser): two-taps to change columns
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt
  AnkiDroid/src/main/res/layout/item_column_selection.xml
  AnkiDroid/src/main/res/values/07-cardbrowser.xml
Labels: Pending Merge, Strings

#18299 Focus on start input field with selected text while repositioning, and show keyboard
  AnkiDroid/src/main/java/com/ichi2/anki/browser/RepositionCardFragment.kt
Labels: Pending Merge

#18313 feat: add licenses wiki page link
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings

#18327 Developer option for review reminders
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Pending Merge, GSoC

#18365 Updated strings from Crowdin 2025/05/24 07:33
  AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/01-core.xml
  AnkiDroid/src/main/res/values-gl/03-dialogs.xml
  AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-gl/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/11-arrays.xml
  AnkiDroid/src/main/res/values-gl/17-model-manager.xml
  AnkiDroid/src/main/res/values-heb/02-strings.xml
  AnkiDroid/src/main/res/values-heb/03-dialogs.xml
  AnkiDroid/src/main/res/values-heb/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-heb/10-preferences.xml
  AnkiDroid/src/main/res/values-iw/02-strings.xml
  AnkiDroid/src/main/res/values-iw/03-dialogs.xml
  AnkiDroid/src/main/res/values-iw/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-iw/10-preferences.xml
  AnkiDroid/src/main/res/values-lt/01-core.xml
  AnkiDroid/src/main/res/values-lv/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-he.txt
Labels: Pending Merge

#18381 Updated strings from Crowdin 2025/05/29 09:08
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/03-dialogs.xml
  AnkiDroid/src/main/res/values-eo/08-widget.xml
  AnkiDroid/src/main/res/values-eo/09-backup.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rAR/08-widget.xml
  AnkiDroid/src/main/res/values-es-rAR/09-backup.xml
  AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml
  AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-es-rES/08-widget.xml
  AnkiDroid/src/main/res/values-es-rES/09-backup.xml
  AnkiDroid/src/main/res/values-es-rES/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/08-widget.xml
  AnkiDroid/src/main/res/values-gl/09-backup.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/17-model-manager.xml
  AnkiDroid/src/main/res/values-lt/01-core.xml
  AnkiDroid/src/main/res/values-lt/02-strings.xml
  AnkiDroid/src/main/res/values-lt/03-dialogs.xml
  AnkiDroid/src/main/res/values-lt/04-network.xml
  AnkiDroid/src/main/res/values-lt/05-feedback.xml
  AnkiDroid/src/main/res/values-lt/06-statistics.xml
  AnkiDroid/src/main/res/values-lt/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-lt/08-widget.xml
  AnkiDroid/src/main/res/values-lt/09-backup.xml
  AnkiDroid/src/main/res/values-lt/10-preferences.xml
  AnkiDroid/src/main/res/values-lt/11-arrays.xml
  AnkiDroid/src/main/res/values-lt/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-lt/17-model-manager.xml
  AnkiDroid/src/main/res/values-lt/20-search-preference.xml
  AnkiDroid/src/main/res/values-lv/02-strings.xml
  AnkiDroid/src/main/res/values-lv/03-dialogs.xml
  AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-lv/08-widget.xml
  AnkiDroid/src/main/res/values-lv/09-backup.xml
  AnkiDroid/src/main/res/values-lv/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/03-dialogs.xml
  AnkiDroid/src/main/res/values-tr/08-widget.xml
  AnkiDroid/src/main/res/values-tr/09-backup.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/08-widget.xml
  AnkiDroid/src/main/res/values-zh-rCN/09-backup.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-es-AR.txt
  docs/marketing/localized_description/marketdescription-es-ES.txt
  docs/marketing/localized_description/marketdescription-ja.txt
  docs/marketing/localized_description/marketdescription-lt.txt
  docs/marketing/localized_description/marketdescription-ru.txt
Labels: Pending Merge

#18391 NF: remove CardTemplateJson
  AnkiDroid/src/main/java/com/ichi2/anki/utils/CardTemplateJson.kt
Labels: Pending Merge

#18387 Add tooltip in note editor
  AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
  AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge, Strings
