Repository ankidroid/Anki-Android, pull requests merged in 2025-07, with the labels that each got.

#18733 refactor(new reviewer): misc refactors
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
Labels: Pending Merge

#18739 fix(release): Unable to start activity: MultimediaActivity
  AnkiDroid/proguard-rules.pro
Labels: Queued for Cherry Pick to Stable Branch

#18743 fix(release): Unable to start activity: MultimediaActivity
  AnkiDroid/proguard-rules.pro
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/ParcelableUtils.kt
  AnkiDroid/src/main/java/com/ichi2/compat/CompatV28.kt
  AnkiDroid/src/test/java/com/ichi2/anki/utils/ext/ParcelableUtilsTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18753 fix(card-browser): [tablet] menu crashed when no note editor
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Queued for Cherry Pick to Stable Branch

#18364 Created ReviewRemindersDatabase and ReviewReminder
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
  AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt
Labels: Needs Second Approval, GSoC

#18736 fix(new reviewer): answer button size
  AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_reviewer.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
Labels: Pending Merge

#18763 fix(filtered-decks): handle duplicate name on creation
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18757 fix(filtered-decks): [API33+] rebuild after 'back' press
  AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18778 Updated strings from Crowdin 2025/07/05 13:12
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/04-network.xml
  AnkiDroid/src/main/res/values-ar/05-feedback.xml
  AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ar/08-widget.xml
  AnkiDroid/src/main/res/values-ar/09-backup.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ar/11-arrays.xml
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ar/17-model-manager.xml
  AnkiDroid/src/main/res/values-ar/18-standard-models.xml
  AnkiDroid/src/main/res/values-ar/20-search-preference.xml
  AnkiDroid/src/main/res/values-es-rAR/02-strings.xml
  AnkiDroid/src/main/res/values-es-rES/02-strings.xml
  AnkiDroid/src/main/res/values-ko/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rBR/08-widget.xml
  AnkiDroid/src/main/res/values-pt-rBR/09-backup.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-tr/02-strings.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/17-model-manager.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-uz/01-core.xml
  AnkiDroid/src/main/res/values-uz/02-strings.xml
  AnkiDroid/src/main/res/values-uz/10-preferences.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-ar.txt
  docs/marketing/localized_description/marketdescription-es-AR.txt
  docs/marketing/localized_description/marketdescription-es-ES.txt
  docs/marketing/localized_description/marketdescription-gl.txt
  docs/marketing/localized_description/marketdescription-pt-BR.txt
  docs/marketing/localized_description/marketdescription-tr.txt
  docs/marketing/localized_description/marketdescription-ug.txt
  docs/marketing/localized_description/marketdescription-uz.txt
  docs/marketing/localized_description/marketdescription-zh-CN.txt
Labels: Pending Merge

#18760 Potential fix for Softlock in the deck options when trying to view the manual offline
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18751 fix: img max width in previewers and new reviewer
  AnkiDroid/src/main/assets/ankidroid.css
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18717 Fixed 'Change Column' does not restore state correctly
  AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt
Labels: squash-merge, New contributor, Queued for Cherry Pick to Stable Branch

#18765 fix(new reviewer): don't discard touches
  AnkiDroid/src/main/assets/scripts/ankidroid.js
Labels: Pending Merge

#18741 feat(new reviewer): card zoom
  AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
Labels: Pending Merge

#18764 fix(deck-picker): 'undo' menu item not updated
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18786 tweak(preferences): remove general from 'Controls'
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
Labels: Priority-Low, Pending Merge

#18795 chore: use same icon for 'Replay media'
  AnkiDroid/src/main/res/xml/preferences_previewer_controls.xml
Labels: Pending Merge

#18798 move 'Full screen navigation drawer' setting
  AnkiDroid/src/main/res/xml/preferences_controls.xml
  AnkiDroid/src/main/res/xml/preferences_general.xml
Labels: Priority-Low, Pending Merge

#18796 fix: controls settings being removed after selecting tab
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
Labels: Pending Merge

#18823 Rename NoteEditor to NoteEditorFragment
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/NoteEditorFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
  AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Note Editor, Review High Priority, Pending Merge, GSoC

#18831 chore: use 2.22 milestone labels
  .github/workflows/milestone.yml
Labels: Pending Merge

#18829 ReviewRemindersScope for ScheduleReminders entry
  AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleRemindersDestination.kt
Labels: Pending Merge, GSoC

#18827 Improve ReviewRemindersDatabase docstrings
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
Labels: Pending Merge, GSoC

#18826 feat: display user-facing FSRS version
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/Fsrs.kt
  AnkiDroid/src/test/java/com/ichi2/anki/scheduling/FsrsTest.kt
Labels: Pending Merge

#18857 Updated strings from Crowdin 2025/07/12 06:19
  AnkiDroid/src/main/res/values-ar/01-core.xml
  AnkiDroid/src/main/res/values-ar/02-strings.xml
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/04-network.xml
  AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ar/09-backup.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ar/17-model-manager.xml
  AnkiDroid/src/main/res/values-ar/20-search-preference.xml
  AnkiDroid/src/main/res/values-eo/01-core.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-fa/01-core.xml
  AnkiDroid/src/main/res/values-gl/17-model-manager.xml
  AnkiDroid/src/main/res/values-ja/01-core.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-nn/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rBR/01-core.xml
  AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/01-core.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-tr/11-arrays.xml
  AnkiDroid/src/main/res/values-ug/01-core.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-uz/03-dialogs.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
  docs/marketing/localized_description/marketdescription-ar.txt
  docs/marketing/localized_description/marketdescription-eo.txt
Labels: Pending Merge

#18833 fix: Image cropper screen action bar color is inconsistent with the preceding screen's one
  AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
  AnkiDroid/src/main/res/drawable/ic_flip_horizontal.xml
  AnkiDroid/src/main/res/drawable/ic_rotate_right.xml
  AnkiDroid/src/main/res/layout/fragment_image_cropper.xml
  AnkiDroid/src/main/res/menu/image_cropper_menu.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Labels: Pending Merge, Strings

#18850 refactor: remove granular snooze settings
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt
Labels: Needs Second Approval, GSoC

#18849 improve study shortcut
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Labels: Needs Second Approval

#18803 Added a toast message when a card is created
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
  AnkiDroid/src/main/res/values/02-strings.xml
Labels: Pending Merge, Strings, New contributor

#18824 fix: instant editor cloze number incrementing on undo
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch, Instant Editor

#18863 build(deps): adopt Anki-Android-Backend 0.1.58-anki25.07.2
  gradle/libs.versions.toml
Labels: Blocked by dependency, dependencies

#18851 refactor: clean up ReviewReminderScope.DeckSpecific.getDeckName
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
Labels: Pending Merge, GSoC

#18868 fix: "x cards shown" snackbar isn't automatically dismissed
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge, New contributor

#18872 lint: better trim() usage
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt
Labels: Pending Merge, cleanup

#18874 logs: diagnostics for collectionLoadError
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
Labels: Pending Merge

#18854 feat(reminders): add ScheduleReminders DeckSpinner init method
  AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
Labels: Needs Second Approval, GSoC

#18878 test(ci): dynamic iteration control for emulator tests
  .github/workflows/tests_emulator.yml
Labels: Pending Merge

#18871 fix(widget): disable "material you" if using MIUI
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
  AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
  AnkiDroid/src/main/java/com/ichi2/widget/WidgetUtils.kt
  AnkiDroid/src/main/res/drawable-v31/ic_anki_unthemed.xml
  AnkiDroid/src/main/res/drawable-v31/ic_anki_unthemed_finish.xml
  AnkiDroid/src/main/res/layout-v31/widget_small_unthemed.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18576 feat(card-browser): add select all/none toggle in header
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/res/drawable/ic_deselect_white.xml
  AnkiDroid/src/main/res/drawable/ic_select_all_white.xml
  AnkiDroid/src/main/res/layout/cardbrowser.xml
  AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge, Licenses

#18883 test: use api36 emulator for tests
  .github/workflows/tests_emulator.yml
Labels: Pending Merge, Dev

#18893 fix(sync): invalid sync server
  AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18900 Rename note_editor.xml to note_editor_fragment.xml
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
  AnkiDroid/src/main/res/layout/note_editor_fragment.xml
Labels: Needs Second Approval, GSoC

#18877 libanki Compat: Collection.kt (sched/DB/Import/Export)
  AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  libanki/src/main/java/com/ichi2/anki/libanki/BackendImportExport.kt
  libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
Labels: Pending Merge

#18905 fix: "Undo" tooltip doesn't show its target
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#18853 refactor: delete bulk deletion, use separate prefs file
  AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt
Labels: Needs Second Approval, GSoC

#18916 docs(libanki): Link ID to main class
  libanki/src/main/java/com/ichi2/anki/libanki/PythonTypes.kt
Labels: Priority-Low, Pending Merge, cleanup

#18918 Text share to AnkiDroid should launch note editor
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18902 libanki compat: Collection Part 2 (Image Occlusion/Object Helpers/Utils/Notes)
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
  libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
Labels: Priority-Low, Pending Merge

#18923 refactor(tests): extract utils from NoteTypeTest
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/libanki/CollectionTest.kt
  AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
  libanki/testutils/src/main/java/com/ichi2/anki/libanki/testutils/ext/Collection.kt
Labels: Priority-Low, Pending Merge, cleanup

#18932 Updated strings from Crowdin 2025/07/21 15:33
  AnkiDroid/src/main/res/values-ar/03-dialogs.xml
  AnkiDroid/src/main/res/values-ar/04-network.xml
  AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ar/08-widget.xml
  AnkiDroid/src/main/res/values-ar/10-preferences.xml
  AnkiDroid/src/main/res/values-cs/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/01-core.xml
  AnkiDroid/src/main/res/values-gl/02-strings.xml
  AnkiDroid/src/main/res/values-gl/03-dialogs.xml
  AnkiDroid/src/main/res/values-gl/10-preferences.xml
  AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-tr/10-preferences.xml
  AnkiDroid/src/main/res/values-ug/02-strings.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-vi/01-core.xml
  AnkiDroid/src/main/res/values-vi/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Labels: Pending Merge

#18940 chore: ignore more Kotlin migrations in `git blame`
  .git-blame-ignore-revs
Labels: Pending Merge

#18939 refactor: prepare BootService for review reminders
  AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
  common/src/main/java/com/ichi2/anki/common/annotations/LegacyNotifications.kt
Labels: Pending Merge, GSoC

#18954 fix: `Study by card state or tag` dropdown menu is prone to overflow
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/res/layout/multiline_spinner_item.xml
Labels: Pending Merge

#18966 build(deps): anki25.07.5 backend
  gradle/libs.versions.toml
Labels: Pending Merge

#18976 NF: Resizable Screens
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Pending Merge, GSoC

#18971 fix: preferences panels overlaying each other on large screens
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18991 fix(libanki): create `collection.media` on collection init
  libanki/src/main/java/com/ichi2/anki/libanki/Media.kt
  libanki/src/test/java/com/ichi2/anki/libanki/CollectionOnDiskTest.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18993 fix: sync worker not initialized crash
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18956 Update 10-preferences.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
Labels: Strings, New contributor

#19006 build(deps): bump test dependencies in a group
  AnkiDroid/proguard-test-rules.pro
  gradle/libs.versions.toml
Labels: dependencies
