Repository ankidroid/Anki-Android, pull requests merged in 2025-06, with the labels that each got.

#18392 NF: Correct NoteType cache
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
Labels: Pending Merge

#18388 NF: rename Model to NoteType in file
  AnkiDroid/src/main/AndroidManifest.xml
  AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteTypeEditorContextMenu.kt
  AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
  AnkiDroid/src/main/res/layout/note_type_field_editor.xml
  AnkiDroid/src/main/res/layout/note_type_field_editor_list_item.xml
  AnkiDroid/src/main/res/menu/note_type_editor.xml
  AnkiDroid/src/main/res/values/17-model-manager.xml
  AnkiDroid/src/test/java/com/ichi2/anki/NoteTypeFieldEditorTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/NoteTypeTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Labels: Pending Merge, Strings

#18406 fix(previewer): update after IO changes
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
Labels: Needs Second Approval

#18404 chore: Update Apache changelog URLs to new structure
  gradle/libs.versions.toml
Labels: Needs Second Approval, New contributor

#18298 Allow search to show subdecks if they match the searched term
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DeckNodeTest.kt
Labels: Needs Second Approval

#18309 Fix crash when using the study keyboard shortcut on an empty collection
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Needs Second Approval

#18255 Avoid context leak in TTS Player by using ApplicationContext
  AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
Labels: Pending Merge

#18165 Fix #15993: Scroll position wrong after editing
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Needs Second Approval, New contributor

#17107 Add comment to core
  AnkiDroid/src/main/res/values/01-core.xml
Labels: Pending Merge, Strings

#18355 Fix/non dismissible keyboard
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Labels: Pending Merge, New contributor

#18354 Fix: Enter triggers OK without extra press
  AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
  AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Labels: Pending Merge, New contributor

#18350 NF: use File as much as possible
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionIntegrityStorageCheck.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioRecordingFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/AndroidPermanentlyRevokedPermissionsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
  AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/TgzPackageExtractTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.kt
Labels: Priority-Low, cleanup

#18417 fix(custom-study): defer loading of 'customStudyDefaults'
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Labels: Pending Merge

#18434 Dependency updates 20250606
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: Pending Merge

#18436 Updated strings from Crowdin 2025/06/06 15:30
  AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-eo/10-preferences.xml
  AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-fil/02-strings.xml
  AnkiDroid/src/main/res/values-fil/03-dialogs.xml
  AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-lv/10-preferences.xml
  AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml
  docs/marketing/localized_description/marketdescription-lv.txt
Labels: Pending Merge

#18403 Replace "reviewer" by "Study screen" in string
  AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
  AnkiDroid/src/main/res/values/01-core.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/10-preferences.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/attrs.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/values/theme_black.xml
  AnkiDroid/src/main/res/values/theme_dark.xml
  AnkiDroid/src/main/res/values/theme_light.xml
  AnkiDroid/src/main/res/values/theme_plain.xml
  AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Labels: Pending Merge, Strings

#18450 Fix lint warnings related to trim() function
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
  api/src/main/java/com/ichi2/anki/api/Utils.kt
  lint-rules/src/main/java/com/ichi2/anki/lint/utils/StringFormatDetector.kt
Labels: Priority-Low, cleanup

#18452 improvement(browse): remove bottom padding
  AnkiDroid/src/main/res/layout/cardbrowser.xml
Labels: Pending Merge

#18461 fix: Remove 'shake device' maracas emoji [<= API 30]
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
Labels: Pending Merge

#18453 fix(browser): keep scroll position after editing note
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
Labels: Pending Merge

#18466 improvement(preferences): add 'close' animation
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Pending Merge

#18448 feat: use Noto Sans Mono font for type-in-answer
  AnkiDroid/src/main/assets/ankidroid.css
  AnkiDroid/src/main/assets/flashcard.css
  AnkiDroid/src/main/assets/fonts/freefont/FreeMono.ttf
  AnkiDroid/src/main/assets/fonts/freefont/GNU GENERAL PUBLIC LICENSE.txt
  AnkiDroid/src/main/assets/fonts/noto/NotoSansMono.ttf
  AnkiDroid/src/main/assets/fonts/noto/OFL.txt
Labels: Pending Merge

#18468 feat(settings): change fragment transition
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Needs Second Approval

#18430 Deck toggles should not show when inapplicable in a search
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt
  AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/DeckNodeTest.kt
Labels: Pending Merge, New contributor

#18473 fix(new reviewer): keybinds triggered when using type answer
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
Labels: Pending Merge

#18470 Dependency updates 20250610
  .github/workflows/lint.yml
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: Pending Merge, dependencies, squash-merge

#18474 refactor(card-browser): move 'available decks' to ViewModel
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Labels: Review High Priority, Pending Merge

#18478 fix(reviewer): allow disabling 'voice playback' if app bar button removed
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Labels: Pending Merge

#18483 fix(tags): nesting broken if casing differed
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
Labels: Review High Priority, Pending Merge

#18493 Updated strings from Crowdin 2025/06/13 03:52
  AnkiDroid/src/main/res/values-gl/02-strings.xml
  AnkiDroid/src/main/res/values-gl/03-dialogs.xml
  AnkiDroid/src/main/res/values-gl/04-network.xml
  AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-gl/08-widget.xml
  AnkiDroid/src/main/res/values-gl/11-arrays.xml
  AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-ja/03-dialogs.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
Labels: Pending Merge

#18503 fix(field-editor): changes after languageHint crashed
  AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
Labels: Pending Merge

#18508 fix: controls settings crash in landscape mode
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt
  AnkiDroid/src/main/res/layout/controls_tab_layout.xml
  AnkiDroid/src/main/res/layout/tab_layout.xml
  AnkiDroid/src/main/res/xml/preferences_controls.xml
Labels: Review High Priority, Needs Second Approval

#18515 fix: remove long gesture remnant after upgrade
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
Labels: Pending Merge

#18521 build(deps): 0.1.53-anki25.02.7 / display panics in ACRA
  gradle/libs.versions.toml
Labels: Pending Merge

#18540 Fix two ui issues when using the black theme
  AnkiDroid/src/main/res/drawable/black_round_alert_dialog_background.xml
  AnkiDroid/src/main/res/values/theme_black.xml
Labels: Pending Merge

#18544 improvement(debug-info): improve newlines
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Labels: Pending Merge

#18550 chore: move link to constants.xml
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SchedulerUpgradeDialog.kt
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/constants.xml
Labels: Pending Merge, Strings

#18516 feat: media check to show trash count
  AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckAdapter.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
  AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
  AnkiDroid/src/main/res/layout/activity_shared_decks.xml
  AnkiDroid/src/main/res/layout/fragment_media_check.xml
  AnkiDroid/src/main/res/menu/media_check_menu.xml
  AnkiDroid/src/main/res/values/sentence-case.xml
  AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
Labels: Pending Merge

#18564 chore: improve logging of invalid index issue in new reviewer
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt
Labels: Pending Merge

#18571 chore: improve more the logging of invalid index issue in new reviewer
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt
Labels: Pending Merge

#18573 improvement(accessibility): FAB
  AnkiDroid/src/main/res/layout/floating_add_button.xml
Labels: Pending Merge

#18585 Updated strings from Crowdin 2025/06/22 07:11
  AnkiDroid/src/main/res/values-cs/02-strings.xml
  AnkiDroid/src/main/res/values-hu/01-core.xml
  AnkiDroid/src/main/res/values-hu/02-strings.xml
  AnkiDroid/src/main/res/values-hu/03-dialogs.xml
  AnkiDroid/src/main/res/values-hu/04-network.xml
  AnkiDroid/src/main/res/values-hu/10-preferences.xml
  AnkiDroid/src/main/res/values-pl/03-dialogs.xml
  AnkiDroid/src/main/res/values-pl/10-preferences.xml
  AnkiDroid/src/main/res/values-pl/11-arrays.xml
  AnkiDroid/src/main/res/values-pl/17-model-manager.xml
  AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml
  AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml
  AnkiDroid/src/main/res/values-pt-rPT/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
  AnkiDroid/src/main/res/values-pt-rPT/11-arrays.xml
  AnkiDroid/src/main/res/values-pt-rPT/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-pt-rPT/17-model-manager.xml
  AnkiDroid/src/main/res/values-ug/02-strings.xml
  AnkiDroid/src/main/res/values-ug/03-dialogs.xml
  AnkiDroid/src/main/res/values-ug/10-preferences.xml
  AnkiDroid/src/main/res/values-ug/17-model-manager.xml
  AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
  docs/marketing/localized_description/marketdescription-pl.txt
Labels: Pending Merge

#18002 feat: add eraser action
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
  AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
  AnkiDroid/src/main/res/drawable/ic_arrow_u_left_top.xml
  AnkiDroid/src/main/res/drawable/ic_eraser.xml
  AnkiDroid/src/main/res/menu/reviewer.xml
  AnkiDroid/src/main/res/values/02-strings.xml
  AnkiDroid/src/main/res/values/11-arrays.xml
  AnkiDroid/src/main/res/values/preferences.xml
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
  AnkiDroid/src/main/res/xml/preferences_reviewer_controls.xml
  AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Labels: Pending Merge, Reviewer, Strings, Licenses

#18587 fix(deck-picker): clicking on an empty filtered deck
  AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18581 fix(preferences): fragment back stack being reset
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18608 refactor: move `ifZero` to `common` module
  AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
  common/src/main/java/com/ichi2/anki/common/utils/ext/Long.kt
  common/src/test/java/com/ichi2/anki/common/utils/ext/LongTest.kt
Labels: Pending Merge

#18597 fix(new reviewer): gestures crash when scrolled
  AnkiDroid/src/main/assets/scripts/ankidroid.js
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18582 fix(custom-study): stop disabling 'extend' options
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18619 fix: show answer command side
  AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
Labels: Needs Review, Queued for Cherry Pick to Stable Branch

#18617 fix(card-browser): remove 'default search'
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
  AnkiDroid/src/main/res/layout/browser_options_dialog.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18629 Updated strings from Crowdin 2025/06/24 06:02
  AnkiDroid/src/main/res/values-el/01-core.xml
  AnkiDroid/src/main/res/values-el/02-strings.xml
  AnkiDroid/src/main/res/values-el/03-dialogs.xml
  AnkiDroid/src/main/res/values-el/04-network.xml
  AnkiDroid/src/main/res/values-el/05-feedback.xml
  AnkiDroid/src/main/res/values-el/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-el/08-widget.xml
  AnkiDroid/src/main/res/values-el/09-backup.xml
  AnkiDroid/src/main/res/values-el/10-preferences.xml
  AnkiDroid/src/main/res/values-el/11-arrays.xml
  AnkiDroid/src/main/res/values-el/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-el/17-model-manager.xml
  AnkiDroid/src/main/res/values-eo/02-strings.xml
  AnkiDroid/src/main/res/values-eo/11-arrays.xml
  AnkiDroid/src/main/res/values-hu/02-strings.xml
  AnkiDroid/src/main/res/values-hu/03-dialogs.xml
  AnkiDroid/src/main/res/values-hu/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-ja/02-strings.xml
  AnkiDroid/src/main/res/values-ja/10-preferences.xml
  AnkiDroid/src/main/res/values-ja/11-arrays.xml
  AnkiDroid/src/main/res/values-ky/01-core.xml
  AnkiDroid/src/main/res/values-uz/01-core.xml
  AnkiDroid/src/main/res/values-uz/02-strings.xml
  AnkiDroid/src/main/res/values-uz/03-dialogs.xml
  AnkiDroid/src/main/res/values-uz/04-network.xml
  AnkiDroid/src/main/res/values-uz/05-feedback.xml
  AnkiDroid/src/main/res/values-uz/06-statistics.xml
  AnkiDroid/src/main/res/values-uz/07-cardbrowser.xml
  AnkiDroid/src/main/res/values-uz/08-widget.xml
  AnkiDroid/src/main/res/values-uz/09-backup.xml
  AnkiDroid/src/main/res/values-uz/10-preferences.xml
  AnkiDroid/src/main/res/values-uz/11-arrays.xml
  AnkiDroid/src/main/res/values-uz/16-multimedia-editor.xml
  AnkiDroid/src/main/res/values-uz/17-model-manager.xml
  AnkiDroid/src/main/res/values-uz/18-standard-models.xml
  AnkiDroid/src/main/res/values-uz/20-search-preference.xml
  AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
  AnkiDroid/src/main/res/values-zh-rCN/11-arrays.xml
  docs/marketing/localized_description/marketdescription-el.txt
  docs/marketing/localized_description/marketdescription-uz.txt
Labels: Pending Merge

#18019 fix: decode media names before inserting into the database
  AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18624 Deprecate noteId var from getNoteTags in Js-API
  AnkiDroid/src/main/assets/scripts/js-api.js
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt
Labels: Tags, Pending Merge, JS API, Queued for Cherry Pick to Stable Branch

#18606 refactor(libanki): inline unnecessary methods
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Labels: Pending Merge

#18510 feat(new reviewer): answer timer
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimerStatus.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
  AnkiDroid/src/main/res/layout/reviewer2.xml
Labels: Pending Merge

#18656 refactor: move `StringUtil` to `common` module
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
  common/build.gradle.kts
  common/src/main/java/com/ichi2/anki/common/utils/StringUtils.kt
  common/src/test/java/com/ichi2/anki/common/utils/StringUtilsTest.kt
Labels: Pending Merge

#18570 build(ci): Github Actions Summary: Unit Test Results
  build.gradle.kts
Labels: Pending Merge

#18661 perf: speed up i18nResourcesRaw
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
Labels: Pending Merge

#18662 i18n: update Uzbek language name
  AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18665 fix(browser): maybe fix crash after editing note
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18663 refactor: move `Ease` to `libAnki` module
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
  AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/DummyScheduler.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Ease.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/EaseTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
Labels: Pending Merge

#18664 refactor: move JSON functionality to `common` module
  AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/LanguageHintService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/JSONObject.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Field.kt
  AnkiDroid/src/test/java/com/ichi2/anki/utils/ext/JSONObjectTest.kt
  common/src/main/java/com/ichi2/anki/common/utils/ext/JSONObject.kt
Labels: Pending Merge

#18657 refactor: move `undoableOp` to `AnkiDroid` module
  AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
  AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
  AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/observability/OpChangesNotifier.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
  AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
  AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
  AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
  AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
  AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
  AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt
Labels: Pending Merge

#18674 refactor: move `CollectionFiles` to `libAnki` module
  AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
  AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/CollectionFiles.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
Labels: Needs Review

#18679 dev: improve commit speed
  AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Labels: Pending Merge

#18678 refactor(libanki): use correct const
  AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
Labels: Priority-Low, Needs Review

#18677 refactor: reimplement 'htmlEncode' in `common`
  AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/VideoPlayer.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
  AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.kt
  common/src/main/java/com/ichi2/anki/common/utils/StringUtils.kt
Labels: Needs Second Approval

#18669 In card template editor, set the cursor at the start
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Labels: Pending Merge

#18687 improvement: 'auto advance' menu visibility
  AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Labels: Review High Priority, Pending Merge, Queued for Cherry Pick to Stable Branch

#18689 Dependency updates 20250627
  AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
  tools/localization/package.json
  tools/localization/yarn.lock
Labels: squash-merge

#18683 libanki: add notetype change methods and tests
  AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
  AnkiDroid/src/test/java/com/ichi2/libanki/NotetypesTest.kt
Labels: Pending Merge

#18702 dev(export): no crash report if 'check media' required
  AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt
  AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch

#18696 fix: multimedia URI `SecurityException`
  AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
  AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Labels: Needs Author Reply, Queued for Cherry Pick to Stable Branch

#18710 improvement(settings): add icons to controls tabs
  AnkiDroid/src/main/res/layout/controls_tab_layout.xml
Labels: Pending Merge, Queued for Cherry Pick to Stable Branch
